// Focus the planner on routes, required stores, and completed visit targets.
document.querySelector('.depot-tag')?.remove();document.querySelector('.fixed-endpoints')?.remove();
depotChoice.querySelector('input').after(document.createTextNode(''));depotChoice.lastChild.textContent='營業所起始';
document.querySelector('.report-controls>button')?.remove();
const workingDays=document.getElementById('reportDays').parentElement;workingDays.replaceChildren(document.createTextNode('剩餘工作日 '),document.getElementById('reportDays'),document.createTextNode(' 天'));
const focusedReport=renderReport;
renderReport=function(){focusedReport();const rows=scopeRecords(),s=summarizeVisitRows(rows),chart=document.getElementById('visitChart');chart.innerHTML='<div class="chart-content"><div class="visit-donut" role="img" aria-label="應訪 '+s.needed+' 間，已達標 '+s.met+' 間，達標率 '+(s.percent??0)+'%" style="--progress:'+(s.percent||0)+'%;--covered:100%;'+(s.needed?'':'background:#dce5ea;')+'"><div><b>'+(s.percent===null?'—':s.percent+'%')+'</b><span>達標率</span></div></div><div class="visit-count-grid"><div>總客戶數<b>'+s.total+'</b></div><button onclick="showVisitRequirement(\'required\')">應訪<b>'+s.needed+'</b></button><button onclick="showVisitRequirement(\'met\')">已達標<b>'+s.met+'</b></button><button onclick="showVisitRequirement(\'missing\')">缺訪<b>'+s.short+'</b></button>'+(s.unset?'<button class="needs-frequency" onclick="showVisitRequirement(\'unset\')">待設訪頻<b>'+s.unset+'</b></button>':'')+'</div></div>';
 const missing=rows.filter(x=>visitGap(x)>0).sort((a,b)=>visitGap(b)-visitGap(a)||a.name.localeCompare(b.name,'zh-Hant')),priority=document.getElementById('priorityStore');priority.replaceChildren();if(missing.length){const x=missing[0],info=document.createElement('div');info.innerHTML='<b class="priority-name">'+esc(x.name)+'</b><span class="priority-gap">'+visitGap(x)+' <small>次缺訪</small></span>';const add=makeAction(chosen.has(x.code)?'已加入':'＋ 加入行程',()=>choose(x.code,true));add.disabled=chosen.has(x.code);priority.append(info,add);}else priority.textContent='目前無缺訪';
 const groups=new Map();for(const x of rows){const name=x.channel||x.group||'未分類',list=groups.get(name)||[];list.push(x);groups.set(name,list);}const box=document.getElementById('channelReport');box.innerHTML='<table><thead><tr><th>通路</th><th>總客戶</th><th>應訪</th><th>已達標</th><th>缺訪</th><th>達標率</th></tr></thead><tbody></tbody></table>';const body=box.querySelector('tbody'),chips=document.getElementById('scheduleChannels');chips.replaceChildren();for(const [name,list] of [['全通路',rows],...[...groups].sort((a,b)=>a[0].localeCompare(b[0],'zh-Hant'))]){const v=summarizeVisitRows(list),tr=document.createElement('tr');tr.innerHTML='<th><button>'+esc(name)+'</button></th>'+['total','needed','met','short'].map(k=>'<td>'+v[k]+'</td>').join('')+'<td>'+(v.percent===null?'—':v.percent+'%')+'</td>';const action=()=>{channelFocus=name==='全通路'?'':name;groups.clear();document.getElementById('search').value='';document.getElementById('visitStatus').value='all';switchView('list');render();};tr.querySelector('button').onclick=action;body.append(tr);const b=makeAction(name,action);b.innerHTML='<b>'+esc(name)+'</b><span>應訪 '+v.needed+' · 已達標 '+v.met+' · 缺訪 '+v.short+'</span>';b.classList.toggle('active',channelFocus===(name==='全通路'?'':name));chips.append(b);}
};
const focusedWorkPanel=renderWorkPanel;
renderWorkPanel=function(){focusedWorkPanel();const panel=document.getElementById('workDashboard');panel.querySelector('.work-stats + p')?.remove();panel.querySelector('#workDailyChart')?.closest('article')?.remove();panel.querySelector('.work-channel-summary')?.remove();};
// Each account can keep its own depot without placing an address form on the map.
const depotDialog=document.createElement('div');depotDialog.id='depotDrawer';depotDialog.className='modal credential-drawer';depotDialog.innerHTML='<div class="dialog"><button class="drawer-close" onclick="closeModal(\'depotDrawer\')" aria-label="關閉出發點">✕</button><h2>我的營業所</h2><form id="depotForm"><div class="formgrid"><label>名稱<input id="depotName" maxlength="100" required></label><label>地址<input id="depotAddress" maxlength="300"></label><label>緯度<input id="depotLat" type="number" step="any" min="-90" max="90" required></label><label>經度<input id="depotLng" type="number" step="any" min="-180" max="180" required></label></div><footer><button type="button" onclick="fillDepotSettings(DEFAULT_DEPOT)">龍潭營業所</button><button class="primary" type="submit">儲存</button></footer></form></div>';document.body.append(depotDialog);
function fillDepotSettings(d){document.getElementById('depotName').value=d.name;document.getElementById('depotAddress').value=d.address||'';document.getElementById('depotLat').value=d.gps[0];document.getElementById('depotLng').value=d.gps[1];}
const depotSettingsButton=makeAction('我的營業所',()=>{fillDepotSettings(DEPOT);openModal('depotDrawer');});depotSettingsButton.id='personalDepotButton';document.querySelector('#compactSettings .wide-settings').prepend(depotSettingsButton);
document.getElementById('depotForm').onsubmit=async e=>{e.preventDefault();if(!plannerAccessReady())return;const d={name:document.getElementById('depotName').value.trim(),address:document.getElementById('depotAddress').value.trim(),gps:[Number(document.getElementById('depotLat').value),Number(document.getElementById('depotLng').value)]};if(!d.name||!validGps(d.gps))return toast('請填寫名稱與有效座標');DEPOT=d;abortAutoRoute();autoRouteDone='';autoRouteGeometry=null;removeRouteLine();routeHint='';depotMarker?.setLatLng(d.gps);depotMarker?.bindPopup(esc(d.name));await saveAutoPreference();persistTrip();fitNext=true;closeModal('depotDrawer');render();};
const depotChange=document.getElementById('depotStartChoice').onchange;document.getElementById('depotStartChoice').onchange=async e=>{await depotChange(e);persistTrip();};
// Discreet signature and an accessible release history.
const releaseButton=makeAction('v1.16',()=>openModal('releaseHistory'));releaseButton.id='releaseButton';releaseButton.setAttribute('aria-label','版本 v1.16，查看更新紀錄');const credit=document.createElement('div');credit.className='planner-credit';credit.innerHTML='<span class="luke-signature">Luke_Tien</span>';credit.append(releaseButton);document.querySelector('header').append(credit);
const releases=[['1.16','2026-10-04 22:28','精簡地圖與訪況；應訪／已達標總覽；工作自檢精簡；個人營業所與起始選項；管理者移除權限及重新加入；署名與版本紀錄。'],['1.15','2026-10-04','打卡時間作為到點、工作完成日期作為離點；停留與跨店時間重疊檢查。'],['1.14','2026-10-04','一鍵更新本月與上月工作；衛星訊號依公司欄位判定；臨時點備註必填。'],['1.13','2026-10-04','管理總覽整合各訪員路線、訪況與登入紀錄。'],['1.12','2026-10-04','新增工作自檢與一鍵更新工作紀錄。'],['1.0–1.11','2026-10-02～2026-10-04','Google 個人同步、業務王帳號、一鍵更新、手機排程、共享訪頻與智慧安排。']];
const releaseHistory=document.createElement('div');releaseHistory.id='releaseHistory';releaseHistory.className='modal credential-drawer';releaseHistory.innerHTML='<div class="dialog"><button class="drawer-close" onclick="closeModal(\'releaseHistory\')" aria-label="關閉更新紀錄">✕</button><h2>更新紀錄</h2>'+releases.map(([version,time,note])=>'<article class="release-entry"><b>v'+version+'</b><time>'+time+'</time><p>'+note+'</p></article>').join('')+'</div>';document.body.append(releaseHistory);
const focusedStyle=document.createElement('style');focusedStyle.textContent=`#calendarNote{display:none!important}.overview-grid{grid-template-columns:minmax(0,1fr) 180px;align-items:start}.overview-grid .priority-card{padding:14px;min-height:170px}.priority-card h3{font-size:13px;margin-bottom:12px}.priority-name{display:block;font-size:15px;line-height:1.5}.priority-gap{display:block;color:var(--red);font-size:24px;margin:6px 0}.priority-gap small{font-size:11px;font-weight:400}.priority-card button{width:100%;font-size:12px;min-height:36px;padding:5px}.visit-count-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.visit-count-grid .needs-frequency{grid-column:1/-1}.channel-visit-table tr>*{display:table-cell!important}.work-chart-grid{grid-template-columns:1fr}.planner-credit{display:flex;align-items:center;gap:10px;color:#788b89}.luke-signature{font-family:'Segoe Script','Brush Script MT',cursive;font-style:italic;font-size:17px;opacity:.65}.planner-credit button{min-height:26px;padding:2px 6px;font-size:10px;font-weight:400;border:0;background:none;color:#788b89}.release-entry{padding:16px 0;border-bottom:1px solid var(--line)}.release-entry time{display:block;font-size:11px;color:var(--muted);margin:6px 0}.release-entry p{font-size:13px;line-height:1.7}.route-note{white-space:nowrap;font-size:12px;padding:9px 10px}.depot-choice{grid-column:auto!important;min-height:40px}.wide-settings #personalDepotButton{min-width:120px}#panel-map #tripRouteHint{display:none!important}@media(max-width:600px){.overview-grid{grid-template-columns:1fr}.overview-grid .priority-card{width:165px;min-height:155px;justify-self:end}.visit-count-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.channel-visit-table th,.channel-visit-table td{padding:6px 4px!important;font-size:11px}.channel-visit-table th:first-child{max-width:100px}.chart-content{align-items:center}.planner-credit{gap:4px}.luke-signature{font-size:13px}.planner-credit button{font-size:9px}.brand{gap:7px}header{padding:10px!important;gap:6px}.brand h1{font-size:17px}.route-controls{display:flex!important;flex-wrap:wrap}.route-controls .depot-choice{font-size:12px}.route-controls>button{flex:1}.wide-settings{display:flex;flex-wrap:wrap}.wide-settings #personalDepotButton{min-width:0}}`;document.head.append(focusedStyle);render();
// Removing access is reversible: retained account data become available after explicit rejoining.
let membershipUid=null,membershipReady=false,membershipRevoked=false,membershipControl=null,membershipStop=null;
const membershipRef=uid=>firebaseApi.doc(firestore,'route_map_test_users',uid,'settings','accessControl');
const membershipAccess=plannerAccessReady;plannerAccessReady=function(){return membershipReady&&!membershipRevoked&&membershipAccess();};
const membershipGate=refreshAccountGate;refreshAccountGate=function(){membershipGate();if(cloudUser&&!membershipReady){document.getElementById('gateMessage').textContent='正在確認帳號…';document.getElementById('gateAction').disabled=true;}else if(cloudUser&&membershipRevoked){document.getElementById('gateMessage').textContent='網站使用權限已移除';const action=document.getElementById('gateAction');action.disabled=false;action.textContent='重新加入';action.onclick=rejoinPlanner;}};
async function rejoinPlanner(){const uid=cloudUser?.uid;if(!uid||!membershipReady||!membershipRevoked)return;const button=document.getElementById('gateAction');button.disabled=true;try{await firebaseApi.runTransaction(firestore,async t=>{const ref=membershipRef(uid),old=await t.get(ref);if(!old.exists()||old.data().active!==false)return;t.set(ref,{...old.data(),active:true,joinedAt:firebaseApi.serverTimestamp()});});if(cloudUser?.uid!==uid)return;await loadTtlBinding();autoPreferenceKey=null;initializeAutoPreference();lastSharedUser=null;await connectSharedAccount();await loadFromCloud(true);connectWorkAccount(true);render();}catch{document.getElementById('gateStatus').textContent='重新加入未完成，請稍後重試';}finally{button.disabled=false;}}
function connectMembership(){const uid=cloudUser?.uid||null;if(uid===membershipUid&&membershipStop)return;if(!firebaseApi)return;membershipStop?.();membershipStop=null;membershipUid=uid;membershipReady=!uid;membershipRevoked=false;membershipControl=null;if(!uid){refreshAccountGate();return;}membershipStop=firebaseApi.onSnapshot(membershipRef(uid),snap=>{if(cloudUser?.uid!==uid)return;membershipControl=snap.exists()?snap.data():null;membershipReady=true;membershipRevoked=membershipControl?.active===false;if(membershipRevoked){if(visitSyncBusy)cancelVisitSync();abortAutoRoute();clearTimeout(autoSaveTimer);autoSaveBlocked=true;workListener?.();workListener=null;workUser=null;autoPreferenceStop?.();autoPreferenceStop=null;autoPreferenceKey=null;}else autoSaveBlocked=false;refreshAccountGate();if(!membershipRevoked)render();},()=>{if(cloudUser?.uid!==uid)return;membershipReady=false;refreshAccountGate();document.getElementById('gateMessage').textContent='無法確認網站權限，請重新整理';});refreshAccountGate();}
const membershipWork=connectWorkAccount;connectWorkAccount=function(force=false){if(membershipRevoked)return;return membershipWork(force);};
const membershipSave=saveToCloud;saveToCloud=async function(){if(membershipRevoked)return;return membershipSave();};
let removePlannerTarget=null;
const removePlannerDialog=document.createElement('div');removePlannerDialog.id='removePlannerDialog';removePlannerDialog.className='modal';removePlannerDialog.innerHTML='<div class="dialog"><h2>移除使用權限</h2><p id="removePlannerEmail"></p><p class="notice">對方會停止使用本站，資料保留，之後可重新加入。</p><footer><button onclick="closeModal(\'removePlannerDialog\')">取消</button><button id="removePlannerSubmit" class="primary">移除權限</button></footer></div>';document.body.append(removePlannerDialog);
function openRemovePlanner(person){if(!isPlannerAdmin()||!plannerAccessReady()||person.uid===cloudUser.uid)return;removePlannerTarget={uid:person.uid,email:person.email,adminUid:cloudUser.uid};document.getElementById('removePlannerEmail').textContent=person.email;openModal('removePlannerDialog');}
document.getElementById('removePlannerSubmit').onclick=async()=>{const target=removePlannerTarget;if(!target||!isPlannerAdmin()||cloudUser.uid!==target.adminUid||target.uid===cloudUser.uid)return;const button=document.getElementById('removePlannerSubmit');button.disabled=true;try{await firebaseApi.runTransaction(firestore,async t=>{const ref=membershipRef(target.uid),old=await t.get(ref);if(!isPlannerAdmin()||cloudUser.uid!==target.adminUid)throw Error('帳號已變更');t.set(ref,{active:false,revision:(old.exists()?old.data().revision||0:0)+1,revokedAt:firebaseApi.serverTimestamp(),revokedBy:target.adminUid});});closeModal('removePlannerDialog');removePlannerTarget=null;toast('已移除使用權限');}catch{toast('移除未完成，請稍後重試');}finally{button.disabled=false;}};
const accessStyle=document.createElement('style');accessStyle.textContent='.manager-person-row{display:flex;align-items:center;gap:8px}.manager-person-row .manager-visitor{flex:1;min-width:0}.manager-person-row .remove-planner{font-size:12px;flex:none;color:var(--red)}@media(max-width:600px){.manager-person-row{position:relative;display:block}.manager-person-row .remove-planner{margin:0 0 8px;min-height:34px;padding:6px 10px}}';document.head.append(accessStyle);setInterval(connectMembership,500);connectMembership();refreshAccountGate();
