// Inline rule editing, independent administration, and focused customer table.
settingsTabs.classList.add('hide');
const adminPanel=document.createElement('section');adminPanel.id='panel-admin';adminPanel.className='panel';adminPanel.innerHTML='<div class="intro"><h2>登入紀錄</h2></div>';adminPanel.append(adminCard);document.querySelector('main.shell').append(adminPanel);
for(const nav of document.querySelectorAll('.tabs,.bottomnav')){const b=document.createElement('button');b.dataset.view='admin';b.className='admin-main-tab hide';b.innerHTML=nav.classList.contains('bottomnav')?'<span class="icon">◷</span><span>登入紀錄</span>':'登入紀錄';b.onclick=()=>switchView('admin');nav.append(b);}
const adminPageSwitch=switchView;switchView=function(view){if(view==='admin'){if(!isPlannerAdmin()||!plannerAccessReady())return;document.querySelectorAll('.panel').forEach(e=>e.classList.remove('active'));adminPanel.classList.add('active');activeView='admin';document.body.dataset.mobileView='admin';settingsAdminSelected=true;adminCard.classList.remove('hide');document.querySelectorAll('.tabs [data-view],.bottomnav [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view==='admin');b.setAttribute('aria-current',b.dataset.view==='admin'?'page':'false');});loadAdminHistory();}else{adminPanel.classList.remove('active');settingsAdminSelected=false;settingsContent.classList.remove('hide');adminPageSwitch(view);}};
const adminPageGate=refreshAccountGate;refreshAccountGate=function(){settingsAdminSelected=activeView==='admin'&&isPlannerAdmin();adminPageGate();document.querySelectorAll('.admin-main-tab').forEach(b=>b.classList.toggle('hide',!isPlannerAdmin()));document.body.classList.toggle('has-admin-tab',isPlannerAdmin());if(activeView==='admin'&&!isPlannerAdmin())switchView('data');};
// Rules remain in document flow, with only the global-change confirmation as a dialog.
const inlineRules=document.createElement('details');inlineRules.id='inlineRules';inlineRules.open=true;inlineRules.innerHTML='<summary>訪頻規則</summary><div class="inline-rule-content"></div>';ruleCard.querySelector('.data-actions').remove();ruleCard.append(inlineRules);const ruleDialog=rulesModal.querySelector('.dialog');ruleDialog.querySelector('h2').remove();ruleDialog.querySelector('.notice')?.remove();inlineRules.querySelector('div').append(...ruleDialog.children);inlineRules.querySelector('footer button:not(.primary)').textContent='還原';
const inlineModalOpen=openModal,inlineModalClose=closeModal;openModal=function(id){if(id==='rulesModal'){inlineRules.open=true;return;}inlineModalOpen(id);};closeModal=function(id){if(id==='rulesModal'){if(reportRulePairs().length)inlineRulesDraft();return;}inlineModalClose(id);};const inlineRulesDraft=openRules;openRules=function(){inlineRulesDraft();if(reportRulePairs().length){switchView('data');inlineRules.open=true;inlineRules.scrollIntoView({block:'start',behavior:'smooth'});}};
let inlineRuleSource='';function refreshInlineRules(){if(!plannerAccessReady())return;const pairs=reportRulePairs(),signature=JSON.stringify([cloudUser.uid,sharedRuleRevision,pairs]);if(!pairs.length){document.getElementById('frequencyRows').textContent='更新訪況後顯示規則';inlineRuleSource='';return;}if(signature===inlineRuleSource||inlineRules.contains(document.activeElement))return;inlineRuleSource=signature;inlineRulesDraft();}
const depotChoice=document.createElement('label');depotChoice.className='depot-choice';depotChoice.innerHTML='<input id="depotStartChoice" type="checkbox" checked>營業所作為起點';document.querySelector('.route-controls').append(depotChoice);
document.getElementById('depotStartChoice').onchange=async e=>{if(!autoPreferenceReady)return;autoDepotStart=e.target.checked;localStorage.setItem(depotPreferenceStorage(),String(autoDepotStart));abortAutoRoute();autoRouteDone='';autoRouteGeometry=null;removeRouteLine();routeHint='';render();await saveAutoPreference();};
const originTrip=renderTrip;renderTrip=function(){originTrip();if(!autoDepotStart)document.querySelector('#tripList>.depot-stop')?.remove();};
function mapVisitState(x){return visitGap(x)>0?'missing':x.frequencyMissing||frequencyFor(x)?.period==='none'?'unregulated':'met';}
const visitStateMap=updateMap;updateMap=function(fit){visitStateMap(fit);mapRows.forEach((x,i)=>{const state=mapVisitState(x),label=state==='missing'?'缺訪 '+visitGap(x)+' 次':state==='met'?'已達標':'無規定或未設定訪頻';markers.get(x.code)?.setIcon(L.divIcon({className:'',html:'<div class="pin visit-'+state+'" data-store-code="'+esc(x.code)+'" aria-label="'+esc(x.name+' · '+label)+'">'+(i+1)+'</div>',iconSize:[32,32],iconAnchor:[16,16]}));});};
document.querySelector('.legend').innerHTML='<span><i style="background:#be4d38"></i>缺訪</span><span><i style="background:#087f68"></i>已達標</span><span><i style="background:#78858b"></i>無規定／未設定</span>';
const listPanel=document.getElementById('panel-list'),listTools=listPanel.querySelector('.listtools'),fullTableHead=listPanel.querySelector('.store-table-head');
const customerHeader=document.createElement('div');customerHeader.className='customer-table-header';customerHeader.innerHTML='<h3>客戶清單</h3>';customerHeader.append(document.querySelector('.selection-total'));listPanel.insertBefore(customerHeader,listTools);const fullSearch=document.querySelector('.searchfield');fullSearch.classList.add('customer-search');fullSearch.firstChild.textContent='找店家';listPanel.insertBefore(fullSearch,listTools);
const mobileChannels=document.getElementById('scheduleChannels');listPanel.insertBefore(mobileChannels,customerHeader);selectionSummary.classList.add('hide');listPanel.querySelector(':scope>.card').classList.add('hide');document.getElementById('visitStatus').value='all';
document.getElementById('search').oninput=()=>{if(document.getElementById('search').value.trim()){channelFocus='';groups.clear();document.getElementById('visitStatus').value='all';}render();};
const metricLabels=document.createElement('div');metricLabels.className='table-metric-labels';metricLabels.innerHTML='<span>週期</span><span>應訪</span><span>已訪</span><span>缺訪</span>';fullTableHead.children[3].append(metricLabels);
const polishedRender=render;render=function(){polishedRender();const choice=document.getElementById('depotStartChoice');if(choice){choice.checked=autoDepotStart;choice.disabled=!autoPreferenceReady;}refreshInlineRules();};
const redesignStyle=document.createElement('style');redesignStyle.textContent=`
.wide-settings{display:block;padding:20px}#inlineRules{margin-top:14px;border-top:1px solid var(--line)}#inlineRules summary{font-size:17px;font-weight:700;padding:16px 0;cursor:pointer}.inline-rule-content footer{position:static;background:transparent;display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.inline-rule-content .frequency-row{grid-template-columns:minmax(120px,1.3fr) minmax(110px,1fr) 110px 150px 70px}.inline-rule-content button{min-width:0}#inlineRules .counter button{min-width:44px}.depot-choice{display:flex;align-items:center;gap:8px;font-size:13px;min-height:40px;cursor:pointer}.depot-choice input{width:20px;height:20px;min-height:0}.pin.visit-missing{background:#be4d38}.pin.visit-met{background:#087f68}.pin.visit-unregulated{background:#78858b}.customer-table-header{display:flex;align-items:center;justify-content:space-between;margin:20px 0 10px}.customer-table-header h3{margin:0;font-size:19px}.customer-table-header .selection-total{margin:0;font-size:13px}.customer-table-header strong{font-size:21px;margin-left:6px}.customer-search{display:block;width:100%;font-size:13px;color:var(--muted);margin:0 0 10px}.customer-search input{margin-top:6px;width:100%;min-height:46px}.table-metric-labels{display:grid;grid-template-columns:38px repeat(3,1fr);gap:8px;text-align:center;font-size:11px;opacity:.85;margin-top:6px}.store-table-head,.store,.store.selected{grid-template-columns:36px minmax(160px,1fr) 150px 270px 60px}.table-controls{gap:6px}#channelReport{gap:8px;margin:12px 0 16px}#channelReport button{min-width:0;min-height:52px;padding:9px 14px}#scheduleChannels{display:none}.report-controls{display:flex;justify-content:flex-start;align-items:flex-end;gap:10px}.report-controls label{max-width:150px;flex:1}.report-controls>button{margin-left:auto}.overview-grid{margin:14px 0;gap:14px}.overview-grid .card{padding:20px}.overview-grid .priority-number{margin:8px 0}.chart-content{gap:20px}#panel-admin{overflow-wrap:anywhere}body[data-mobile-view="admin"] .syncbar{display:none!important}.tabs .admin-main-tab{min-width:120px}.has-admin-tab .bottomnav{grid-template-columns:repeat(5,minmax(0,1fr))}
@media(max-width:600px){.inline-rule-content .frequency-row{grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:8px;padding:12px 0}.inline-rule-content .frequency-row>button{grid-column:2}.inline-rule-content .counter{min-width:0}#inlineRules .counter button{min-width:38px;width:38px}.inline-rule-content .frequency-row select{font-size:14px;padding:8px}.wide-settings{padding:14px}.store-table-head,.store,.store.selected{grid-template-columns:30px minmax(95px,1fr) minmax(130px,1fr);gap:6px}.store-table-head>span:nth-child(1){grid-column:1}.store-table-head>span:nth-child(2){grid-column:2}.store-table-head>span:nth-child(4){grid-column:3}.table-metric-labels{grid-template-columns:22px repeat(3,1fr);gap:2px;font-size:10px}.storeidentity h3{font-size:15px}.storeidentity .meta{font-size:10px}.table-controls select{font-size:12px}body[data-mobile-view="map"] .route-controls{grid-template-columns:1fr 1fr}body[data-mobile-view="map"] .depot-choice{grid-column:1/-1;min-height:32px;font-size:12px}body[data-mobile-view="list"] #scheduleChannels{display:flex;flex-wrap:nowrap;overflow-x:auto;gap:8px;margin:8px 0 12px;padding-bottom:4px}#scheduleChannels button{flex:none;width:auto;min-width:138px;padding:9px 12px;min-height:52px}#scheduleChannels span{white-space:nowrap}body[data-mobile-view="report"] .customer-table-header,body[data-mobile-view="report"] .customer-search,body[data-mobile-view="report"] #scheduleChannels{display:none!important}.customer-table-header{margin-top:12px}.customer-search input{min-height:46px}#channelReport{margin-bottom:14px}.report-controls{display:grid;grid-template-columns:1fr 1fr}.report-controls label{max-width:none}.report-controls button{grid-column:1/-1;margin:0}.overview-grid .card{padding:16px}.has-admin-tab .bottomnav button{font-size:11px;padding:6px 1px}.has-admin-tab .bottomnav .icon{font-size:18px}}
`;document.head.append(redesignStyle);refreshAccountGate();render();
