// Automatic round trips by default; the per-account opt-out persists across days.
let autoAuthResolved=false,autoRouteEnabled=true,autoPreferenceReady=false,autoPreferenceKey=null,autoPreferenceStop=null;
let autoRouteTimer=null,autoRouteController=null,autoRouteRequest='',autoRouteQueued='',autoRouteDone='',autoRouteGeometry=null,autoRoutePreferenceSaving=0,autoPreferenceSaveGeneration=0;
const autoPreferenceStorage=()=>accountKey()+'-auto-route';
const autoRoutePreferenceRef=()=>firebaseApi.doc(cloudCollection('settings'),'routePreferences');
function autoRouteSignature(){return JSON.stringify([cloudUser?.uid||'guest',routeDate,document.getElementById('ownerFilter').value,selectedRecords().map(x=>[String(x.code),validGps(x.gps)?x.gps:null]).sort((a,b)=>a[0].localeCompare(b[0]))]);}
function abortAutoRoute(){clearTimeout(autoRouteTimer);autoRouteTimer=null;autoRouteQueued='';autoRouteController?.abort();autoRouteController=null;autoRouteRequest='';routeBusy=false;}
function updateAutoRouteButton(){document.querySelectorAll('.suggestBtn').forEach(b=>{b.textContent=autoAuthResolved&&autoPreferenceReady?(autoRouteEnabled?'取消自動安排':'開啟自動安排'):'載入設定…';b.disabled=!autoAuthResolved||!autoPreferenceReady;b.setAttribute('aria-pressed',String(autoRouteEnabled));b.setAttribute('aria-label',autoRouteEnabled?'取消自動路線安排':'開啟自動路線安排');b.classList.toggle('primary',autoRouteEnabled);});}
function initializeAutoPreference(){const key=accountKey();if(autoPreferenceKey===key)return;autoPreferenceStop?.();autoPreferenceStop=null;abortAutoRoute();autoRouteDone='';autoRouteGeometry=null;removeRouteLine();autoPreferenceKey=key;autoRoutePreferenceSaving=0;autoRouteEnabled=localStorage.getItem(autoPreferenceStorage())!=='false';autoPreferenceReady=!cloudUser;updateAutoRouteButton();if(cloudUser&&firebaseApi){const uid=cloudUser.uid;autoPreferenceStop=firebaseApi.onSnapshot(autoRoutePreferenceRef(),snap=>{if(cloudUser?.uid!==uid||autoRoutePreferenceSaving)return;const enabled=snap.exists()?snap.data().autoRouteEnabled!==false:localStorage.getItem(autoPreferenceStorage())!=='false';autoPreferenceReady=true;if(enabled!==autoRouteEnabled){abortAutoRoute();autoRouteDone='';autoRouteGeometry=null;removeRouteLine();routeHint='';}autoRouteEnabled=enabled;localStorage.setItem(autoPreferenceStorage(),String(enabled));render();},()=>{if(cloudUser?.uid===uid){autoPreferenceReady=true;render();}});}}
async function saveAutoPreference(){if(!cloudUser)return;const user=cloudUser,enabled=autoRouteEnabled,generation=++autoPreferenceSaveGeneration;autoRoutePreferenceSaving=generation;try{const batch=firebaseApi.writeBatch(firestore);batch.set(autoRoutePreferenceRef(),{autoRouteEnabled:enabled,updatedAt:firebaseApi.serverTimestamp()});await batch.commit();}catch{if(cloudUser?.uid===user.uid)toast('自動安排設定已保留在此裝置；連線後請再切換一次以同步');}finally{if(autoRoutePreferenceSaving===generation)autoRoutePreferenceSaving=0;}}
async function toggleAutoRoute(){initializeAutoPreference();autoRouteEnabled=!autoRouteEnabled;autoPreferenceReady=true;localStorage.setItem(autoPreferenceStorage(),String(autoRouteEnabled));abortAutoRoute();autoRouteDone='';autoRouteGeometry=null;removeRouteLine();routeHint='';render();await saveAutoPreference();}
document.querySelectorAll('.suggestBtn').forEach(b=>b.onclick=toggleAutoRoute);
suggestRoute=async function(){if(!autoRouteEnabled)return;return arrangeAutomaticRoute();};
function scheduleAutomaticRoute(){if(typeof plannerAccessReady==='function'&&!plannerAccessReady())return;initializeAutoPreference();updateAutoRouteButton();if(!autoAuthResolved||!autoPreferenceReady||!autoRouteEnabled)return;const selected=selectedRecords(),signature=autoRouteSignature();if(!selected.some(x=>validGps(x.gps))){abortAutoRoute();autoRouteDone='';autoRouteGeometry=null;removeRouteLine();routeHint='';return;}if(signature===autoRouteDone){if(activeView==='map'&&map&&autoRouteGeometry&&!routeLine)routeLine=L.geoJSON(autoRouteGeometry,{style:{color:'#2563eb',weight:5,opacity:.8}}).addTo(map);return;}if(signature===autoRouteQueued||signature===autoRouteRequest)return;abortAutoRoute();autoRouteQueued=signature;autoRouteTimer=setTimeout(()=>{autoRouteQueued='';arrangeAutomaticRoute();},450);}
async function arrangeAutomaticRoute(){if(!autoRouteEnabled||!autoPreferenceReady)return;const signature=autoRouteSignature(),selected=selectedRecords(),rows=selected.filter(x=>validGps(x.gps));if(!rows.length)return;abortAutoRoute();const controller=new AbortController();autoRouteController=controller;autoRouteRequest=signature;routeBusy=true;render();let timeout;try{let ordered=orderByDistance(rows,DEPOT.gps),points=[DEPOT.gps,...ordered.map(x=>x.gps)],route=null;if(points.length<=40){timeout=setTimeout(()=>controller.abort('timeout'),18000);try{const response=await fetch('https://router.project-osrm.org/trip/v1/driving/'+points.map(p=>p[1]+','+p[0]).join(';')+'?source=first&destination=any&roundtrip=true&geometries=geojson&overview=full',{signal:controller.signal});const data=await response.json();if(!response.ok||data.code!=='Ok'||data.waypoints?.length!==points.length||!data.trips?.[0])throw Error('no route');ordered=data.waypoints.map((x,i)=>({i,order:x.waypoint_index})).filter(x=>x.i>0).sort((a,b)=>a.order-b.order).map(x=>ordered[x.i-1]);route=data.trips[0];}catch{if(controller.signal.aborted&&controller.signal.reason!=='timeout')return;}finally{clearTimeout(timeout);}}
if(!autoRouteEnabled||signature!==autoRouteSignature()||autoRouteController!==controller)return;
const next=[...ordered.map(x=>x.code),...selected.filter(x=>!validGps(x.gps)).map(x=>x.code)];autoRouteDone=signature;autoRouteGeometry=route?.geometry||null;
if(JSON.stringify([...chosen])!==JSON.stringify(next)){chosen=new Set(next);persistTrip();}else removeRouteLine();
routeHint=route?'自動安排 · 營業所往返 '+(route.distance/1000).toFixed(1)+' 公里 · 約 '+Math.ceil(route.duration/60)+' 分鐘（未含停留與即時交通）':'自動安排 · 依直線距離排序，含營業所往返';if(selected.length>rows.length)routeHint+=' · '+(selected.length-rows.length)+' 間缺座標';fitNext=true;render();if(activeView==='map'&&map)fitMap();
}finally{clearTimeout(timeout);if(autoRouteController===controller){autoRouteController=null;autoRouteRequest='';routeBusy=false;render();}}}
const automaticPersistTrip=persistTrip;persistTrip=function(){if(!routeBusy){autoRouteDone='';autoRouteGeometry=null;}automaticPersistTrip();};
const automaticRender=render;render=function(){automaticRender();scheduleAutomaticRoute();};
const automaticSwitchView=switchView;switchView=function(view){automaticSwitchView(view);scheduleAutomaticRoute();};
const automaticLoadFromCloud=loadFromCloud;loadFromCloud=async function(initial=false){initializeAutoPreference();if(cloudUser){const uid=cloudUser.uid;try{const pref=await firebaseApi.getDoc(autoRoutePreferenceRef());if(cloudUser?.uid===uid&&!autoRoutePreferenceSaving){autoRouteEnabled=pref.exists()?pref.data().autoRouteEnabled!==false:localStorage.getItem(autoPreferenceStorage())!=='false';autoPreferenceReady=true;localStorage.setItem(autoPreferenceStorage(),String(autoRouteEnabled));}}catch{autoPreferenceReady=true;}}autoRouteDone='';autoRouteGeometry=null;abortAutoRoute();await automaticLoadFromCloud(initial);scheduleAutomaticRoute();};
window.addEventListener('pagehide',()=>abortAutoRoute());initCloud().then(()=>authApi.onAuthStateChanged(cloudAuth,()=>{autoAuthResolved=true;initializeAutoPreference();render();})).catch(()=>{autoAuthResolved=true;autoPreferenceReady=true;render();});render();
