// Test-page enhancements. All cloud writes stay under route_map_test_users/{uid}.
let autoSaveTimer=null,editGeneration=0,autoSaveBlocked=false;
function todayRouteDate(){let t=taipeiToday();return [t.year,String(t.month).padStart(2,'0'),String(t.day).padStart(2,'0')].join('-')}
function scheduleCloudSave(){clearTimeout(autoSaveTimer);if(cloudUser&&!autoSaveBlocked)autoSaveTimer=setTimeout(()=>{if(cloudBusy){scheduleCloudSave();return}if(localDirty)saveToCloud()},600)}
const LOCAL_BASE='route-map-test-account-';
let cloudUser=null,authApi=null,cloudAuth=null,cloudInitPromise=null,cloudBusy=false,cloudRevision=0;
let customerMaster=null,customerMasterDirty=false;
let closedStoreCodes=new Set(),pendingClosedStores=new Set();
let pendingCustomers=new Set(),pendingVisits=new Set(),localDirty=false,routeLine=null,routeHint='',routeBusy=false;
let reportYear=new Date().getFullYear(),routeDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
// Weekday red dates extracted and checked against the official DGPA 2026/2027 XLSX calendars.
const holidaysByYear={2026:['01-01','02-16','02-17','02-18','02-19','02-20','02-27','04-03','04-06','05-01','06-19','09-25','09-28','10-09','10-26','12-25'],2027:['01-01','02-04','02-05','02-08','02-09','02-10','03-01','04-05','04-06','04-30','06-09','09-15','09-28','10-11','10-25','12-24','12-31']};
function taipeiToday(now=new Date()){let p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);return Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]))}
function remainingWorkdays(year,m,now=new Date()){if(!holidaysByYear[year])return null;let t=taipeiToday(now),from=Date.UTC(year,m-1,1),last=Date.UTC(year,m,0),today=Date.UTC(t.year,t.month-1,t.day);if(last<today)return 0;let count=0;for(let d=new Date(Math.max(from,today));d.getTime()<=last;d.setUTCDate(d.getUTCDate()+1)){let md=String(d.getUTCMonth()+1).padStart(2,'0')+'-'+String(d.getUTCDate()).padStart(2,'0');if(d.getUTCDay()!==0&&d.getUTCDay()!==6&&!holidaysByYear[year].includes(md))count++}return count}
work=function(){return remainingWorkdays(reportYear,month)};
function visitCount(x){return isQuarterly(x)?qVisits(x):x.actual}
function visitGap(x){return Math.max(0,x.req-visitCount(x))}
mergedSources=function(){let map=new Map;for(let x of [...excel,...db,...customerDb]){if(!x.code)continue;map.set(String(x.code),{...map.get(String(x.code)),...x})}let visits=new Map(excel.filter(x=>(x.year||reportYear)===reportYear).map(x=>[String(x.code),x.visits]));return [...map.values()].map(x=>({...x,visits:visits.has(String(x.code))?visits.get(String(x.code)):((x.year||reportYear)===reportYear?x.visits:Array(12).fill(0))}))};
function accountKey(){return LOCAL_BASE+(cloudUser?.uid||'guest')}
function cacheState(){localStorage.setItem(accountKey(),JSON.stringify({closedStoreCodes:[...closedStoreCodes],pendingClosedStores:[...pendingClosedStores],db,gps,customerDb,excel,customerMaster,customerMasterDirty,responsibility:document.getElementById('ownerFilter').value,chosen:[...chosen],ruleConfig,month,reportYear,routeDate,cloudRevision,pendingCustomers:[...pendingCustomers],pendingVisits:[...pendingVisits],localDirty}))}
function restoreState(s){closedStoreCodes=new Set(s.closedStoreCodes||[]);pendingClosedStores=new Set(s.pendingClosedStores||[]);customerMaster=s.customerMaster||null;customerMasterDirty=!!s.customerMasterDirty;db=s.db||[];gps=s.gps||{};customerDb=s.customerDb||[];excel=s.excel||[];chosen=new Set(s.chosen||[]);ruleConfig=s.ruleConfig||structuredClone(DEFAULT_RULES);month=s.month||taipeiToday().month;reportYear=s.reportYear||taipeiToday().year;routeDate=todayRouteDate();if(s.routeDate!==routeDate)chosen.clear();cloudRevision=s.routeDate===routeDate?(s.cloudRevision||0):0;pendingCustomers=new Set(s.pendingCustomers||[]);pendingVisits=new Set(s.pendingVisits||[]);localDirty=!!s.localDirty;document.getElementById('monthSelect').value=String(month);document.getElementById('reportMonth').value=String(month);document.getElementById('reportYear').value=String(reportYear);document.getElementById('routeDate').value=routeDate;document.getElementById('search').value='';groups.clear();routeHint='';removeRouteLine();render();document.getElementById('ownerFilter').value=('responsibility' in s)?s.responsibility:(customerMaster?.preferredOwner||'');render()}
function dirty(){editGeneration++;localDirty=true;cacheState();updateCloudUi();scheduleCloudSave()}
save=function(){dirty()};
persistTrip=function(){dirty();routeHint='';removeRouteLine()};
function markCustomers(items){items.forEach(x=>pendingCustomers.add(String(x.code)));dirty()}
function upsertCustomers(items){let map=new Map(customerDb.map(x=>[String(x.code),x]));items.forEach(x=>{let code=String(x.code).trim();map.set(code,{...x,code});delete gps[code];db=db.filter(z=>String(z.code)!==code)});customerDb=[...map.values()];markCustomers(items);render()}
function cleanCustomer(x){let fields=['code','name','type','channel','grade','status','address','owner','source','gpsSource'];let result=Object.fromEntries(fields.map(k=>[k,String(x[k]??'')]));result.gps=validGps(gps[x.code]||x.gps)?(gps[x.code]||x.gps).map(Number):null;result.companyCurrent=x.companyCurrent!==false;return result}
function cloudMessage(error){let code=error?.code||'';if(code.includes('permission-denied'))return 'Firebase 尚未授權測試區：請設定 Firestore 規則';if(code.includes('configuration-not-found'))return 'Firebase Authentication 尚未完成設定，請由專案管理者啟用 Google 登入';if(code.includes('unauthorized-domain'))return '請在 Firebase Authentication 加入 solortian.github.io 授權網域';if(code.includes('operation-not-allowed'))return '請在 Firebase Authentication 啟用 Google 登入';if(code.includes('popup-blocked'))return '瀏覽器封鎖登入視窗，請允許彈出視窗後重試';if(code.includes('popup-closed')||code.includes('cancelled-popup'))return '登入已取消，資料仍保存在此裝置';return '雲端操作失敗，請檢查網路後重試；本機資料仍保留'}
function updateCloudUi(message){document.querySelectorAll('.loginBtn').forEach(b=>{b.textContent=cloudUser?'登出':'Google 登入';b.disabled=cloudBusy});document.querySelectorAll('.cloudSave').forEach(b=>b.disabled=cloudBusy||!cloudUser);document.querySelectorAll('.cloudLoad').forEach(b=>b.disabled=cloudBusy||!cloudUser);document.getElementById('accountName').textContent=cloudUser?(cloudUser.displayName||cloudUser.email||'已登入'):'未登入';if(message)document.getElementById('cloudDetail').textContent=message;document.getElementById('firebaseStatus').textContent=cloudUser?(localDirty?(autoSaveBlocked?'同步暫停 · 草稿已保留':cloudBusy?'正在自動儲存…':'等待自動儲存…'):'已同步'):'本機草稿 · 登入後可跨裝置保存'}
async function initCloud(){if(cloudInitPromise)return cloudInitPromise;cloudInitPromise=(async()=>{let [appSdk,fsSdk,asdk]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js')]);let app=appSdk.getApps().find(a=>a.name==='route-map-test')||appSdk.initializeApp(FIREBASE_CONFIG,'route-map-test');firebaseApi=typeof sharedPlannerFirestore==='function'?sharedPlannerFirestore(fsSdk):fsSdk;firestore=fsSdk.getFirestore(app);authApi=asdk;cloudAuth=asdk.getAuth(app);asdk.onAuthStateChanged(cloudAuth,async user=>{cacheState();cloudUser=user;let cached=JSON.parse(localStorage.getItem(accountKey())||'null');restoreState(cached||{});updateCloudUi(user?'今天行程自動載入，調整後自動儲存。':'本機草稿可先試用，登入後可複製草稿並上傳。');autoSaveBlocked=false;if(user){clearTimeout(autoSaveTimer);localDirty=false;pendingCustomers.clear();pendingVisits.clear();pendingClosedStores.clear();try{await loadFromCloud(true)}catch(e){updateCloudUi(cloudMessage(e))}}});return app})().catch(e=>{cloudInitPromise=null;throw e});return cloudInitPromise}
async function loginCloud(){try{await initCloud();if(cloudUser){await authApi.signOut(cloudAuth);return}let provider=new authApi.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await authApi.signInWithPopup(cloudAuth,provider)}catch(e){updateCloudUi(cloudMessage(e));toast(cloudMessage(e))}}
function copyGuestDraft(){if(!cloudUser)return toast('請先 Google 登入');let draft=JSON.parse(localStorage.getItem(LOCAL_BASE+'guest')||'null');if(!draft)return toast('沒有可複製的本機草稿');let revision=cloudRevision;restoreState(draft);cloudRevision=revision;markCustomers(mergedSources());excel.forEach(x=>pendingVisits.add(String(x.code)));dirty();toast('已複製草稿，正在自動同步')}
function cloudCollection(name){if(!cloudUser)throw Error('未登入');return firebaseApi.collection(firestore,'route_map_test_users',cloudUser.uid,name)}
function routeRef(){return firebaseApi.doc(cloudCollection('routes'),routeDate)}
async function saveToCloud(){if(!cloudUser)return toast('請先 Google 登入');if(cloudBusy)return;cloudBusy=true;updateCloudUi('正在上傳客戶、訪況與行程…');let revision=cloudRevision,generation=editGeneration,savingDate=routeDate,savingRef=routeRef(),ordered=[...chosen],routeData={codes:[...chosen],month,reportYear,depot:structuredClone(DEPOT),depotStart:autoDepotStart,owner:document.getElementById('ownerFilter').value};try{let byCode=new Map([...excel,...db,...customerDb].map(x=>[String(x.code),x])),writes=[];if(customerMasterDirty&&customerMaster)writes.push({ref:firebaseApi.doc(cloudCollection('settings'),'customerMaster'),data:{...customerMaster,updatedAt:firebaseApi.serverTimestamp()}});for(let code of pendingCustomers){let x=byCode.get(code);if(x)writes.push({ref:firebaseApi.doc(cloudCollection('customers'),encodeURIComponent(code)),data:{...cleanCustomer(x),updatedAt:firebaseApi.serverTimestamp()}})}for(let code of pendingVisits){for(let x of excel.filter(z=>String(z.code)===code))writes.push({ref:firebaseApi.doc(cloudCollection('visits'),String(x.year||reportYear)+'_'+encodeURIComponent(code)),data:{...cleanCustomer(x),year:x.year||reportYear,visits:x.visits||Array(12).fill(0),updatedAt:firebaseApi.serverTimestamp()}})}if(pendingClosedStores.size){const allVisits=await firebaseApi.getDocs(cloudCollection('visits'));for(const code of pendingClosedStores){writes.push({ref:firebaseApi.doc(cloudCollection('customers'),encodeURIComponent(code)),remove:true});for(const d of allVisits.docs){const x=d.data();if(String(x.code)===code)writes.push({ref:firebaseApi.doc(cloudCollection('visits'),String(x.year||reportYear)+'_'+encodeURIComponent(code)),remove:true});}}writes.push({ref:firebaseApi.doc(cloudCollection('settings'),'closedStores'),data:{codes:[...closedStoreCodes],updatedAt:firebaseApi.serverTimestamp()}});}for(let i=0;i<writes.length;i+=400){let batch=firebaseApi.writeBatch(firestore);writes.slice(i,i+400).forEach(w=>w.remove?batch.delete(w.ref):batch.set(w.ref,w.data));await batch.commit()}if(ordered.length>300)throw Error('行程最多 300 店');await firebaseApi.runTransaction(firestore,async t=>{let old=await t.get(savingRef);revision=(old.exists()?old.data().revision||0:0);t.set(savingRef,{...routeData,revision:revision+1,updatedAt:firebaseApi.serverTimestamp()})});if(routeDate===savingDate)cloudRevision=revision+1;if(editGeneration===generation){pendingCustomers.clear();pendingVisits.clear();pendingClosedStores.clear();customerMasterDirty=false;localDirty=false;}cacheState();updateCloudUi('今天的行程已自動儲存；手機登入同一帳號即可使用。')}catch(e){autoSaveBlocked=true;updateCloudUi(cloudMessage(e));document.getElementById('syncRecovery').classList.remove('hide')}finally{cloudBusy=false;updateCloudUi();if(localDirty&&!autoSaveBlocked)scheduleCloudSave()}}
async function loadFromCloud(initial=false){if(!cloudUser)return toast('請先 Google 登入');if(cloudBusy)return;clearTimeout(autoSaveTimer);cloudBusy=true;let loadingGeneration=editGeneration;updateCloudUi('正在載入 Firebase 資料…');try{let [customers,visits,trip,master,frequency,closed]=await Promise.all([firebaseApi.getDocs(cloudCollection('customers')),firebaseApi.getDocs(cloudCollection('visits')),firebaseApi.getDoc(routeRef()),firebaseApi.getDoc(firebaseApi.doc(cloudCollection('settings'),'customerMaster')),firebaseApi.getDoc(firebaseApi.doc(cloudCollection('settings'),'frequencyRules')),firebaseApi.getDoc(firebaseApi.doc(cloudCollection('settings'),'closedStores'))]);if(editGeneration!==loadingGeneration){return}closedStoreCodes=new Set(closed.exists()?closed.data().codes||[]:[]);pendingClosedStores.clear();customerMaster=master.exists()?master.data():null;customerMasterDirty=false;let year=trip.exists()?trip.data().reportYear||reportYear:reportYear;customerDb=customers.docs.map(d=>d.data());excel=visits.docs.map(d=>d.data());db=[];gps={};pendingCustomers.clear();pendingVisits.clear();if(trip.exists()){let s=trip.data();chosen=new Set(s.codes||[]);month=s.month||month;reportYear=year;ruleConfig=s.ruleConfig||ruleConfig;cloudRevision=s.revision||0}else{chosen.clear();cloudRevision=0}if(frequency.exists())ruleConfig=frequency.data().ruleConfig||ruleConfig;localDirty=false;purgeClosedStores([...customerDb,...excel,...db]);cacheState();document.getElementById('monthSelect').value=String(month);document.getElementById('reportYear').value=String(reportYear);render();document.getElementById('ownerFilter').value=trip.exists()?trip.data().owner||'':customerMaster?.preferredOwner||'';render();fitNext=true;if(activeView==='map')updateMap(true);updateCloudUi(trip.exists()?'已載入 '+routeDate+' 的雲端行程與最新客戶資料':'已載入客戶資料；'+routeDate+' 尚無儲存行程');}catch(e){updateCloudUi(cloudMessage(e));if(!initial)toast(cloudMessage(e))}finally{cloudBusy=false;updateCloudUi();if(localDirty&&!autoSaveBlocked)scheduleCloudSave()}}
function changeRouteDate(value){routeDate=value;cloudRevision=0;dirty();updateCloudUi('已切換行程日期；請先載入該日期，或建立新的行程。')}
function changeReportYear(value){reportYear=Number(value);dirty();render()}
function reportStats(rows){let channels=new Map;for(let x of rows){let name=x.channel||x.group||'未分類',s=channels.get(name)||{name,stores:0,short:0,gap:0};s.stores++;s.short+=!x.met?1:0;s.gap+=visitGap(x);channels.set(name,s)}return [...channels.values()].sort((a,b)=>b.gap-a.gap)}
function renderReport(){let days=work(),rows=scopeRecords(),gap=rows.reduce((n,x)=>n+visitGap(x),0);document.getElementById('workdays').textContent=days??'待更新';document.getElementById('reportDays').textContent=days??'待更新';document.getElementById('reportGap').textContent=gap;document.getElementById('reportPace').textContent=days>0?Math.ceil(gap/days)+' 次／天':days===0?'本月已無工作日':'尚無假日日曆';document.getElementById('calendarNote').textContent=holidaysByYear[reportYear]?'週六、週日、國定假日及補假休息；剩餘天數包含今天（若為工作日）。':'此年度尚未載入國定假日，請更新日曆後使用工作日統計。';let box=document.getElementById('channelReport');box.replaceChildren();for(let s of reportStats(rows)){let card=document.createElement('article');card.className='card';card.innerHTML='<h3>'+esc(s.name)+'</h3><div class="statusrow"><span>'+s.stores+' 間店</span><b class="red">'+s.short+' 間缺訪 · 欠 '+s.gap+' 次</b></div><p class="notice">'+(days>0?'平均每天需補 '+(s.gap/days).toFixed(1)+' 次':'')+'</p>';card.appendChild(makeAction('查看此通路缺訪',()=>{document.getElementById('search').value=s.name;missingOnly=true;groups.clear();render();switchView('list')}));box.appendChild(card)}if(!rows.length)box.innerHTML='<div class="empty">先匯入拜訪統計與客戶資料，即可查看各通路訪況。</div>'}
const baseRender=render;render=function(){baseRender();renderReport();renderRouteStarts();document.getElementById('routeHint').textContent=routeHint;document.getElementById('tripRouteHint').textContent=routeHint;document.querySelectorAll('.suggestBtn').forEach(b=>b.disabled=routeBusy)};
const baseSelectMonth=selectMonth;selectMonth=function(m){baseSelectMonth(m);document.getElementById('reportMonth').value=String(m);dirty()};
function renderRouteStarts(){let s=document.getElementById('routeStart'),prev=s.value;s.innerHTML='<option value="first">目前第 1 間店出發</option><option value="location">從我的位置出發</option>'+selectedRecords().filter(x=>validGps(x.gps)).map(x=>'<option value="'+esc(x.code)+'">'+esc(x.name)+'</option>').join('');s.value=[...s.options].some(o=>o.value===prev)?prev:'first'}
function distanceKm(a,b){let rad=Math.PI/180,dl=(b[0]-a[0])*rad,dg=(b[1]-a[1])*rad,v=Math.sin(dl/2)**2+Math.cos(a[0]*rad)*Math.cos(b[0]*rad)*Math.sin(dg/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(Math.max(0,1-v)))}
function orderByDistance(rows,start){let left=[...rows],out=[],point=start;while(left.length){let best=0;for(let i=1;i<left.length;i++)if(distanceKm(point,left[i].gps)<distanceKm(point,left[best].gps))best=i;let x=left.splice(best,1)[0];out.push(x);point=x.gps}return out}
function getPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('定位不可用'));navigator.geolocation.getCurrentPosition(p=>resolve([p.coords.latitude,p.coords.longitude]),()=>reject(Error('無法取得位置，請選擇店家當起點')),{enableHighAccuracy:true,timeout:12000})})}
function removeRouteLine(){if(routeLine&&map){map.removeLayer(routeLine);routeLine=null}}
async function suggestRoute(){if(routeBusy)return;let selected=selectedRecords(),rows=selected.filter(x=>validGps(x.gps));if(rows.length<2)return toast('至少選取 2 間有座標的店家');routeBusy=true;render();try{let startValue=document.getElementById('routeStart').value,startPoint;if(startValue==='location')startPoint=await getPosition();else{let first=rows.find(x=>x.code===startValue)||rows[0];rows=[first,...rows.filter(x=>x!==first)];startPoint=first.gps}let ordered=startValue==='location'?orderByDistance(rows,startPoint):[rows[0],...orderByDistance(rows.slice(1),startPoint)];let points=startValue==='location'?[startPoint,...ordered.map(x=>x.gps)]:ordered.map(x=>x.gps);let route=null;if(points.length<=40){try{let res=await fetch('https://router.project-osrm.org/trip/v1/driving/'+points.map(p=>p[1]+','+p[0]).join(';')+'?source=first&destination=last&roundtrip=false&geometries=geojson&overview=full',{signal:AbortSignal.timeout(18000)});let data=await res.json();if(!res.ok||data.code!=='Ok'||data.waypoints?.length!==points.length||!data.trips?.[0])throw Error('no route');let indices=data.waypoints.map((x,i)=>({i,order:x.waypoint_index})).sort((a,b)=>a.order-b.order).map(x=>x.i);ordered=indices.filter(i=>startValue!=='location'||i!==0).map(i=>ordered[startValue==='location'?i-1:i]);route=data.trips[0]}catch(e){route=null}}chosen=new Set([...ordered.map(x=>x.code),...selected.filter(x=>!validGps(x.gps)).map(x=>x.code)]);persistTrip();routeHint=route?'道路建議：'+(route.distance/1000).toFixed(1)+' 公里 · 約 '+Math.ceil(route.duration/60)+' 分鐘（未含停留及即時交通）':'依直線距離建議順序；道路服務未回應或店點過多，請以實際導航為準';if(selected.length>rows.length)routeHint+='；'+(selected.length-rows.length)+' 間缺座標保留在行程末尾';document.getElementById('mapScope').value='selected';fitNext=true;switchView('map');if(route?.geometry&&map){routeLine=L.geoJSON(route.geometry,{style:{color:'#283d7d',weight:5,opacity:.75}}).addTo(map)}render();toast('已安排 1 → 2 → 3，仍可到行程調整')}catch(e){toast(e.message||'無法建議路線')}finally{routeBusy=false;render()}}
// Import handlers replace customer attributes by code, keeping visit statistics separate.
document.getElementById('customerFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}),items=parseCustomerRows(rows);if(!items.length)throw Error('empty');upsertCustomers(items);document.getElementById('customerStatus').textContent='已更新 '+items.length+' 筆，同代碼使用最新資料；登入後會自動儲存。';toast('客戶已更新，拜訪統計保留')}catch(e){toast('匯入失敗，請確認 Excel 含店家代碼欄位')}finally{e.target.value=''}};
document.getElementById('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1}),items=parseRows(rows).map(x=>({...x,year:reportYear}));if(!items.length)throw Error('empty');let byKey=new Map(excel.map(x=>[(x.year||reportYear)+'_'+x.code,x]));items.forEach(x=>{byKey.set(reportYear+'_'+x.code,x);pendingVisits.add(x.code)});excel=[...byKey.values()];dirty();document.getElementById('fileStatus').textContent='已更新 '+reportYear+' 年 '+items.length+' 筆訪況（含 0 次）；登入後會自動儲存。';render()}catch(e){toast('拜訪統計匯入失敗，請確認檔案格式')}finally{e.target.value=''}};
const baseSaveStore=saveStore;saveStore=function(){let code=document.getElementById('sCode').value.trim(),name=document.getElementById('sName').value.trim();if(!code||!name)return toast('請填寫店家代碼與名稱');baseSaveStore();let x=db.find(x=>x.code===code);if(x){let visits=x.visits;upsertCustomers([{...x,gps:gps[code]||null}]);let index=excel.findIndex(z=>z.code===code&&(z.year||reportYear)===reportYear),v={...x,visits,year:reportYear};if(index>=0)excel[index]=v;else excel.push(v);pendingVisits.add(code);dirty();render()}};
const baseImportGps=importGps;importGps=function(){let codes=document.getElementById('gpsText').value.split(/\r?\n/).map(l=>l.trim().split(/\s+/)[0]).filter(Boolean);baseImportGps();codes.forEach(c=>pendingCustomers.add(c));dirty()};
clearGps=function(){if(!confirm('清空測試區座標？此變更會自動同步至雲端。'))return;gps={};customerDb=customerDb.map(x=>({...x,gps:null}));db=db.map(x=>({...x,gps:null}));excel=excel.map(x=>({...x,gps:null}));markCustomers(mergedSources());render();toast('測試區座標已清空')};
copyOriginal=function(){let oldCustomers=JSON.parse(localStorage.getItem('route-manager-customer-master-v1')||'[]'),oldStores=JSON.parse(localStorage.getItem('route-manager-v1')||'[]'),oldGps=JSON.parse(localStorage.getItem('route-manager-gps-v1')||'{}');if(!oldCustomers.length&&!oldStores.length)return toast('此瀏覽器沒有舊版暫存，請改用 Excel 匯入');upsertCustomers([...oldCustomers,...oldStores].map(x=>({...x,gps:oldGps[x.code]||x.gps||null})));toast('已複製舊版客戶到測試區；登入後會自動儲存')};
loadCloud=async function(){return loadFromCloud()};
const baseLoadDemo=loadDemo;loadDemo=function(){baseLoadDemo();db.filter(x=>x.code.startsWith('DEMO-')).forEach(x=>{pendingCustomers.add(x.code);pendingVisits.add(x.code);if(!excel.some(z=>z.code===x.code&&(z.year||reportYear)===reportYear))excel.push({...x,year:reportYear})});dirty()};
document.getElementById('reportMonth').innerHTML=document.getElementById('monthSelect').innerHTML;document.getElementById('reportMonth').value=String(month);
document.getElementById('routeDate').value=routeDate;document.getElementById('reportYear').value=String(reportYear);
let cachedGuest=JSON.parse(localStorage.getItem(accountKey())||'null');if(cachedGuest)restoreState(cachedGuest);else{mergedSources().forEach(x=>pendingCustomers.add(x.code));excel.forEach(x=>pendingVisits.add(x.code));cacheState()}
render();updateCloudUi();switchView(matchMedia('(max-width:600px)').matches?'map':'list');initCloud().catch(e=>updateCloudUi('Firebase 套件暫時無法載入，可先使用本機草稿'));

async function retryAutoSync(){autoSaveBlocked=false;document.getElementById('syncRecovery').classList.add('hide');scheduleCloudSave()}
async function useCloudVersion(){await loadFromCloud();if(!localDirty){autoSaveBlocked=false;document.getElementById('syncRecovery').classList.add('hide')}}
async function checkTodayRoute(){if(routeDate===todayRouteDate()||cloudBusy)return;routeDate=todayRouteDate();chosen.clear();cloudRevision=0;routeHint='';removeRouteLine();let t=taipeiToday();month=t.month;reportYear=t.year;document.getElementById('routeDate').value=routeDate;document.getElementById('monthSelect').value=String(month);document.getElementById('reportMonth').value=String(month);document.getElementById('reportYear').value=String(reportYear);cacheState();render();if(cloudUser&&!localDirty)await loadFromCloud(true);updateCloudUi('已切換今天；每天重新安排路線，客戶與訪況持續保留。')}
setInterval(checkTodayRoute,15000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkTodayRoute();if(cloudUser&&!localDirty&&!cloudBusy){if(typeof resumePlannerCloud==='function')resumePlannerCloud();else loadFromCloud(true);}else scheduleCloudSave()}});
window.addEventListener('online',retryAutoSync);
