// Fixed depot round trips and dense planning UI, confined to the test page.
const DEFAULT_DEPOT=Object.freeze({name:'台酒龍潭營業所',address:'',gps:[24.86877,121.25675]});let DEPOT=structuredClone(DEFAULT_DEPOT);
let depotMarker=null;
const mergedSwitchView=switchView;
switchView=function(view){mergedSwitchView(view==='trip'?'map':view)};
renderRouteStarts=function(){};
const denseVisibleRecords=visibleRecords;
visibleRecords=function(){let rows=denseVisibleRecords(),status=document.getElementById('visitStatus').value,sort=document.getElementById('storeSort').value;rows=rows.filter(x=>status==='all'||(status==='missing'?visitGap(x)>0:status==='selected'?chosen.has(x.code):x.met));return rows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'zh-Hant'):sort==='channel'?(a.channel||a.group).localeCompare(b.channel||b.group,'zh-Hant')||visitGap(b)-visitGap(a):visitGap(b)-visitGap(a)||a.name.localeCompare(b.name,'zh-Hant'))};
storeCard=function(x){let gap=visitGap(x),card=document.createElement('article');card.className='store'+(chosen.has(x.code)?' selected':'');card.innerHTML='<label class="selectlabel"><input type="checkbox" aria-label="將 '+esc(x.name)+' 加入行程" '+(chosen.has(x.code)?'checked':'')+'></label><div class="storeidentity"><h3>'+esc(x.name)+'</h3><div class="meta">'+esc(x.code)+' · '+esc(x.owner||'未指定業務')+'</div></div><div class="storechannel">'+esc(x.channel||x.group)+'<small>'+esc(x.grade)+'</small></div><div class="visitnumbers"><span class="period">'+(isQuarterly(x)?'季':'月')+'</span><span aria-label="應訪 '+x.req+' 次">'+x.req+'</span><span aria-label="已訪 '+visitCount(x)+' 次">'+visitCount(x)+'</span><b class="'+(gap?'missing':'met')+'" aria-label="尚缺 '+gap+' 次">'+gap+'</b></div><div class="storelocation">'+(validGps(x.gps)?'<button aria-label="在地圖查看 '+esc(x.name)+'">定位</button>':'<span class="notice">缺座標</span>')+'</div>';card.querySelector('input').onchange=e=>choose(x.code,e.target.checked);card.querySelector('button')?.addEventListener('click',()=>focusStore(x.code));return card};
const denseResetFilters=resetFilters;
resetFilters=function(){document.getElementById('visitStatus').value='all';document.getElementById('storeSort').value='gap';denseResetFilters()};
function depotStop(label){let row=document.createElement('div');row.className='depot-stop';row.innerHTML='<span class="depot-icon">◎</span><div><small>'+label+' · 固定</small><b>'+DEPOT.name+'</b></div>';if(label==='返回'){let a=document.createElement('a');a.className='navlink';a.href=navigateUrl(DEPOT);a.target='_blank';a.rel='noopener noreferrer';a.textContent='返所導航';row.appendChild(a)}return row}
const mergedRenderTrip=renderTrip;
renderTrip=function(){mergedRenderTrip();let box=document.getElementById('tripList');box.prepend(depotStop('出發'));box.appendChild(depotStop('返回'));document.getElementById('routeStopCount').textContent=selectedRecords().length+' 間店';};
const mergedEnsureMap=ensureMap;
ensureMap=function(){let ok=mergedEnsureMap();if(ok&&!depotMarker){depotMarker=L.marker(DEPOT.gps,{icon:L.divIcon({className:'',html:'<div class="depot-pin">所</div>',iconSize:[36,36],iconAnchor:[18,18]})}).addTo(map).bindPopup(DEPOT.name);}return ok};
fitMap=function(){if(!map)return;map.fitBounds(L.latLngBounds([DEPOT.gps,...mapRows.map(x=>x.gps)]),{padding:[35,35],maxZoom:15})};
suggestRoute=async function(){if(routeBusy)return;let selected=selectedRecords(),rows=selected.filter(x=>validGps(x.gps));if(!rows.length)return toast('請先選取至少 1 間有座標的店家');routeBusy=true;render();try{let ordered=orderByDistance(rows,DEPOT.gps),points=[DEPOT.gps,...ordered.map(x=>x.gps)],route=null;if(points.length<=40){try{let res=await fetch('https://router.project-osrm.org/trip/v1/driving/'+points.map(p=>p[1]+','+p[0]).join(';')+'?source=first&destination=any&roundtrip=true&geometries=geojson&overview=full',{signal:AbortSignal.timeout(18000)}),data=await res.json();if(!res.ok||data.code!=='Ok'||data.waypoints?.length!==points.length||!data.trips?.[0])throw Error('no route');ordered=data.waypoints.map((x,i)=>({i,order:x.waypoint_index})).filter(x=>x.i>0).sort((a,b)=>a.order-b.order).map(x=>ordered[x.i-1]);route=data.trips[0];}catch(e){route=null}}chosen=new Set([...ordered.map(x=>x.code),...selected.filter(x=>!validGps(x.gps)).map(x=>x.code)]);persistTrip();routeHint=route?'預估路程 '+(route.distance/1000).toFixed(1)+' 公里 · 約 '+Math.ceil(route.duration/60)+' 分鐘':'依直線距離排序';if(selected.length>rows.length)routeHint+=' '+(selected.length-rows.length)+' 間缺座標未納入道路路線。';document.getElementById('mapScope').value='selected';fitNext=true;switchView('map');if(route?.geometry&&map)routeLine=L.geoJSON(route.geometry,{style:{color:'#2563eb',weight:5,opacity:.8}}).addTo(map);render();toast('已安排營業所 → 店家 → 營業所')}finally{routeBusy=false;render()}};
render();switchView(matchMedia('(max-width:600px)').matches?'map':'list');
