// Shared company visit frequencies and administrator usage overview.
const PLANNER_ADMIN_EMAIL='gaexp8213@gmail.com';
let sharedRules=null,sharedRuleRevision=0,sharedRulesStop=null,adminPresenceStop=null,lastSharedUser=null,sessionBusy=false,frequencyDraftRevision=0;
const sharedRuleRef=()=>firebaseApi.doc(firestore,'route_map_test_shared','frequencyRules');
function isPlannerAdmin(){return !!cloudUser&&cloudUser.email===PLANNER_ADMIN_EMAIL&&cloudUser.emailVerified!==false;}
function reportRulePairs(){const pairs=new Map();for(const x of excel){if(isClosedStore(x)||closedStoreCodes.has(String(x.code)))continue;const channel=String(x.channel||'').trim(),grade=String(x.grade||'').trim();if(channel&&grade)pairs.set(channel+'|'+ruleGrade(grade),{channel,grade});}return [...pairs.values()].sort((a,b)=>a.channel.localeCompare(b.channel,'zh-Hant')||a.grade.localeCompare(b.grade,'zh-Hant'));}
// Match frequencies against the same report fields used by the dropdowns.
const reportFrequencyFor=frequencyFor;frequencyFor=function(x){const report=x.code?excel.find(r=>String(r.code)===String(x.code)&&(r.year||reportYear)===reportYear):null;return reportFrequencyFor(report?{...x,channel:report.channel||x.channel,grade:report.grade||x.grade}:x);};
const privateRestoreState=restoreState;restoreState=function(s){privateRestoreState(s);if(sharedRules){ruleConfig=structuredClone(sharedRules);render();}};
const privateLoadFromCloud=loadFromCloud;loadFromCloud=async function(initial=false){await privateLoadFromCloud(initial);if(sharedRules){ruleConfig=structuredClone(sharedRules);render();}};
function defaultSharedRules(){return {version:4,entries:[...structuredClone(V4_DEFAULTS),...['C','C級','C 級'].map(grade=>({channel:'*',grade,period:'quarter',count:1}))],monthly:{},quarterly:[],fnbOnlyA:false};}
const rulesInfo=rulesModal.querySelector('.notice');rulesInfo.textContent='通路與階級直接取自拜訪統計表，只能選取。這是全站共用規則，修改後會影響所有使用者的缺訪計算。';
rulesModal.querySelector('footer .primary').textContent='確認全站變更';
openRules=function(){if(!cloudUser)return toast('請先 Google 登入');const pairs=reportRulePairs();if(!pairs.length)return toast('請先更新拜訪統計，才能帶入通路與階級選項');frequencyDraftRevision=sharedRuleRevision;frequencyDraft=pairs.map(x=>{let r=frequencyFor(x);return {...x,period:r?.period||'month',count:Number(r?.count||0)};});drawFrequencyRules();openModal('rulesModal');};
addFrequencyRule=function(){const pair=reportRulePairs()[0];if(!pair)return toast('請先更新拜訪統計');frequencyDraft.push({...pair,period:'month',count:1});drawFrequencyRules();};
drawFrequencyRules=function(){const pairs=reportRulePairs(),channels=[...new Set(pairs.map(x=>x.channel))],box=document.getElementById('frequencyRows');box.replaceChildren();frequencyDraft.forEach((r,i)=>{const grades=[...new Set(pairs.filter(x=>x.channel===r.channel).map(x=>x.grade))];let row=document.createElement('div');row.className='frequency-row';row.innerHTML='<label>通路<select aria-label="規則 '+(i+1)+' 通路">'+channels.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('')+'</select></label><label>店家階級<select aria-label="規則 '+(i+1)+' 等級">'+grades.map(g=>'<option value="'+esc(g)+'">'+esc(g)+'</option>').join('')+'</select></label><label>週期<select aria-label="規則 '+(i+1)+' 週期"><option value="month">每月</option><option value="quarter">每季</option></select></label><div class="counter"><button aria-label="減少規則 '+(i+1)+' 次數">−</button><output>'+r.count+'</output><button aria-label="增加規則 '+(i+1)+' 次數">＋</button></div><button aria-label="刪除規則 '+(i+1)+'">移除</button>';const select=row.querySelectorAll('select');select[0].value=r.channel;select[0].onchange=e=>{r.channel=e.target.value;r.grade=pairs.find(x=>x.channel===r.channel)?.grade||'';drawFrequencyRules();};select[1].value=r.grade;select[1].onchange=e=>r.grade=e.target.value;select[2].value=r.period;select[2].onchange=e=>r.period=e.target.value;const buttons=row.querySelectorAll('button');buttons[0].onclick=()=>{r.count=Math.max(0,r.count-1);drawFrequencyRules();};buttons[1].onclick=()=>{r.count=Math.min(99,r.count+1);drawFrequencyRules();};buttons[2].onclick=()=>{frequencyDraft.splice(i,1);drawFrequencyRules();};box.append(row);});};
const confirmRulesModal=document.createElement('div');confirmRulesModal.id='sharedRulesConfirm';confirmRulesModal.className='modal';confirmRulesModal.innerHTML='<div class="dialog"><h2>再次確認：修改所有人的訪頻</h2><p>這次變更會立即套用到所有帳戶，重新計算各店應訪次數、缺訪統計與選店資訊。</p><p id="sharedRulesSummary" class="notice"></p><label class="shared-confirm-label"><input id="sharedRulesConsent" type="checkbox">我確認要修改全站共用規則</label><footer><button onclick="closeModal(\'sharedRulesConfirm\')">返回檢查</button><button id="sharedRulesSubmit" class="primary" disabled onclick="commitSharedRules()">確定更新所有人的規則</button></footer></div>';document.body.append(confirmRulesModal);
document.getElementById('sharedRulesConsent').onchange=e=>document.getElementById('sharedRulesSubmit').disabled=!e.target.checked;
saveRules=function(){if(!cloudUser)return toast('請先 Google 登入');const allowed=new Set(reportRulePairs().map(x=>x.channel+'|'+x.grade)),seen=new Set();for(const r of frequencyDraft){const key=r.channel+'|'+r.grade,canonical=r.channel+'|'+ruleGrade(r.grade);if(!allowed.has(key)||seen.has(canonical)||!['month','quarter'].includes(r.period)||!Number.isInteger(r.count)||r.count<0||r.count>99)return toast('請選取報表中的通路與階級；同通路同階級只能有一條規則');seen.add(canonical);}document.getElementById('sharedRulesSummary').textContent='本次設定 '+frequencyDraft.length+' 個通路／階級組合。';document.getElementById('sharedRulesConsent').checked=false;document.getElementById('sharedRulesSubmit').disabled=true;openModal('sharedRulesConfirm');};
async function commitSharedRules(){if(!cloudUser||!document.getElementById('sharedRulesConsent').checked)return;const user=cloudUser,entries=structuredClone(frequencyDraft),baseRevision=frequencyDraftRevision;const button=document.getElementById('sharedRulesSubmit');button.disabled=true;try{let result;await firebaseApi.runTransaction(firestore,async t=>{const old=await t.get(sharedRuleRef()),current=old.exists()?old.data():null;if((current?.revision||0)!==baseRevision)throw Error('共用規則剛被更新，請關閉後重新檢查再確認');const config=structuredClone(current?.ruleConfig||defaultSharedRules());const visible=new Set(reportRulePairs().map(x=>x.channel+'|'+ruleGrade(x.grade)));config.entries=config.entries.filter(x=>!visible.has(x.channel+'|'+ruleGrade(x.grade)));config.entries.push(...entries);if(config.entries.length>300)throw Error('共用規則超過 300 條，請聯絡管理者整理');result=config;t.set(sharedRuleRef(),{ruleConfig:config,revision:baseRevision+1,updatedAt:firebaseApi.serverTimestamp(),updatedBy:user.uid,confirmed:true});});sharedRules=result;sharedRuleRevision=baseRevision+1;ruleConfig=structuredClone(result);cacheState();render();closeModal('sharedRulesConfirm');closeModal('rulesModal');toast('已更新全站訪頻規則');}catch(e){toast(e.message||'共用規則更新失敗');}finally{button.disabled=!document.getElementById('sharedRulesConsent').checked;}}
const privacyNote=document.createElement('p');privacyNote.className='notice';privacyNote.textContent='登入與開啟網站會記錄帳戶、時間、IP 與 IP 概略地區，僅管理者可查看。地區不是 GPS 定位。';document.getElementById('panel-data').querySelector('.intro').after(privacyNote);
const adminCard=document.createElement('article');adminCard.className='card hide';adminCard.id='plannerAdminCard';adminCard.innerHTML='<h3>管理者 · 使用帳戶</h3><p class="notice">近 5 分鐘有活動表示近期使用，並非保證仍在線上。IP 地區可能受電信出口或 VPN 影響。紀錄自此功能啟用起累積。</p><div id="adminAccountSummary"></div><div id="adminAccounts"></div><h3 style="margin-top:20px">最近登入／開啟紀錄</h3><button onclick="loadAdminHistory()">重新整理紀錄</button><div id="adminHistory"></div>';document.getElementById('panel-data').append(adminCard);
function displayAccessTime(value){const d=value?.toDate?value.toDate():value?new Date(value):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'—';}
function accessTable(rows,history=false){return '<div class="access-scroll"><table class="access-table"><thead><tr><th>帳戶</th><th>'+ (history?'開啟時間':'近期活動')+'</th><th>Google 登入時間</th><th>IP</th><th>概略地區</th><th>裝置</th></tr></thead><tbody>'+rows.map(x=>'<tr><td><b>'+esc(x.name||'')+'</b><br>'+esc(x.email||'')+'</td><td>'+esc(displayAccessTime(history?x.at:x.lastSeen))+'</td><td>'+esc(displayAccessTime(x.loginAt))+'</td><td>'+esc(x.ip||'未知')+'</td><td>'+esc([x.country,x.region,x.city].filter(Boolean).join(' / ')||'未知')+'</td><td>'+esc(x.device||'未知')+'</td></tr>').join('')+'</tbody></table></div>';}
async function loadAdminHistory(){if(!isPlannerAdmin())return;try{const q=firebaseApi.query(firebaseApi.collection(firestore,'route_map_test_access'),firebaseApi.orderBy('at','desc'),firebaseApi.limit(100)),snap=await firebaseApi.getDocs(q);document.getElementById('adminHistory').innerHTML=accessTable(snap.docs.map(x=>x.data()),true);}catch{document.getElementById('adminHistory').textContent='紀錄暫時無法讀取，請重新整理。';}}
async function recordPlannerSession(kind='open'){if(!cloudUser||sessionBusy)return;sessionBusy=true;try{const user=cloudUser;await fetch(VISIT_BACKEND.replace(/\/$/,'')+'/session',{method:'POST',headers:{Authorization:'Bearer '+await user.getIdToken(),'Content-Type':'application/json'},body:JSON.stringify({kind})});}catch{}finally{sessionBusy=false;}}
async function connectSharedAccount(){const uid=cloudUser?.uid;if(uid===lastSharedUser)return;lastSharedUser=uid;sharedRulesStop?.();adminPresenceStop?.();sharedRulesStop=adminPresenceStop=null;sharedRules=null;sharedRuleRevision=0;adminCard.classList.toggle('hide',!isPlannerAdmin());document.getElementById('adminAccounts').replaceChildren();document.getElementById('adminHistory').replaceChildren();if(!cloudUser||!firebaseApi)return;sharedRulesStop=firebaseApi.onSnapshot(sharedRuleRef(),snap=>{sharedRules=snap.exists()?snap.data().ruleConfig:defaultSharedRules();sharedRuleRevision=snap.exists()?snap.data().revision||0:0;ruleConfig=structuredClone(sharedRules);render();},()=>toast('共用訪頻暫時無法載入，請重新整理'));await recordPlannerSession('open');if(isPlannerAdmin()){adminPresenceStop=firebaseApi.onSnapshot(firebaseApi.collection(firestore,'route_map_test_presence'),snap=>{const rows=snap.docs.map(x=>x.data()).sort((a,b)=>(b.lastSeen?.toMillis?.()||0)-(a.lastSeen?.toMillis?.()||0));const recent=rows.filter(x=>Date.now()-(x.lastSeen?.toMillis?.()||0)<300000).length;document.getElementById('adminAccountSummary').textContent=rows.length+' 個使用帳戶 · '+recent+' 個近期活動';document.getElementById('adminAccounts').innerHTML=accessTable(rows);},()=>document.getElementById('adminAccounts').textContent='管理紀錄暫時無法讀取');loadAdminHistory();}}
setInterval(connectSharedAccount,1000);setInterval(()=>{if(!document.hidden)recordPlannerSession('heartbeat');},120000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)recordPlannerSession('heartbeat');});
const adminStyle=document.createElement('style');adminStyle.textContent='.shared-confirm-label{display:flex;align-items:center;gap:10px;margin:20px 0}.shared-confirm-label input{flex:none}.access-scroll{overflow:auto}.access-table{width:100%;border-collapse:collapse;font-size:13px}.access-table th,.access-table td{padding:12px;text-align:left;border-bottom:1px solid var(--line);min-width:140px;max-width:280px;overflow-wrap:anywhere}.access-table th{background:#edf5f3}.access-table td:last-child{font-size:11px}';document.head.append(adminStyle);