const usageLabels23={customers:'客戶與座標',visits:'拜訪統計',routes:'行程',settings:'設定與常用路線',workSnapshots:'工作報表索引',workRecords:'工作自檢',work:'工作資料'};
function usageTable23(headers,rows){const table=document.createElement('table');table.className='manager-table';const head=table.createTHead().insertRow();headers.forEach(t=>{const th=document.createElement('th');th.textContent=t;head.append(th);});const body=table.createTBody();rows.forEach(values=>{const row=body.insertRow();values.forEach(v=>{row.insertCell().textContent=v;});});return table;}
const usageFormat23=n=>Number(n)>=1048576?(Number(n)/1048576).toFixed(2)+' MB':(Number(n)/1024).toFixed(1)+' KB';
const originalUsage23=refreshSupabaseUsage;
refreshSupabaseUsage=async function(){await originalUsage23();const box=document.getElementById('supabaseUsageResult');if(!isPlannerAdmin()||!plannerAccessReady()||box.children.length<2||box.querySelector('#usageDetails23'))return;const details=document.createElement('details');details.id='usageDetails23';const summary=document.createElement('summary');summary.textContent='容量明細與其他用量';details.append(summary);while(box.children.length>1)details.append(box.children[1]);box.append(details);try{const uid=cloudUser.uid,data=plannerResult(await supabasePlannerClient.rpc('planner_usage_breakdown'));if(cloudUser?.uid!==uid||!isPlannerAdmin())return;const note=document.createElement('p');note.className='notice';note.textContent='資料類型與帳戶為資料內容估算；資料表另含索引及系統空間。';details.prepend(note);const chart=document.createElement('div');chart.className='usage-bars23';const rows=data.categories||[],max=Math.max(1,...rows.map(x=>Number(x.bytes)));for(const row of rows){const line=document.createElement('div'),name=document.createElement('span'),bar=document.createElement('i'),value=document.createElement('b');name.textContent=usageLabels23[row.bucket]||row.bucket;bar.style.width=(Number(row.bytes)/max*100)+'%';value.textContent=usageFormat23(row.bytes)+' · '+row.records+' 筆';line.append(name,bar,value);chart.append(line);}details.append(chart);for(const [title,headers,values] of [['各帳戶',['帳戶','筆數','資料容量'],(data.people||[]).map(x=>[x.email,x.records,usageFormat23(x.bytes)])],['資料表與索引',['資料表','資料表容量','索引容量'],(data.relations||[]).map(x=>[x.name,usageFormat23(x.table_bytes),usageFormat23(x.index_bytes)])]]){const heading=document.createElement('h4');heading.textContent=title;const scroll=document.createElement('div');scroll.className='access-scroll';scroll.append(usageTable23(headers,values));details.append(heading,scroll);}}catch(e){const error=document.createElement('p');error.textContent='容量明細讀取失敗：'+e.message;details.append(error);}};
document.getElementById('supabaseUsageRefresh').onclick=refreshSupabaseUsage;
const previewModal23=document.createElement('div');previewModal23.id='previewModal23';previewModal23.className='modal';previewModal23.innerHTML='<div class="preview-dialog23"><div class="preview-toolbar23"><b id="previewPerson23"></b><button id="previewClose23">關閉模擬</button></div><iframe title="訪員模擬檢視" sandbox="allow-scripts allow-popups" referrerpolicy="strict-origin-when-cross-origin"></iframe></div>';document.body.append(previewModal23);
let previewSource23=null,previewGeneration23=0;
document.getElementById('previewClose23').onclick=()=>{previewGeneration23++;previewSource23=null;previewModal23.querySelector('iframe').removeAttribute('src');closeModal('previewModal23');};
window.addEventListener('message',e=>{const frame=previewModal23.querySelector('iframe');if(e.source!==frame.contentWindow||e.data?.kind!=='planner-preview-ready'||!previewSource23||!isPlannerAdmin())return;frame.contentWindow.postMessage({kind:'planner-preview-data',...previewSource23},'*');});
async function openPreview23(person){if(!isPlannerAdmin()||!plannerAccessReady())return;const generation=++previewGeneration23,uid=cloudUser.uid;document.getElementById('previewPerson23').textContent='正在載入 '+person.email;openModal('previewModal23');try{let documents=[];for(let from=0;;from+=1000){const page=plannerResult(await supabasePlannerClient.from('planner_documents').select('*').eq('owner_id',person.uid).order('bucket').order('document_id').range(from,from+999));documents.push(...page);if(page.length<1000)break;}const shared=plannerResult(await supabasePlannerClient.from('planner_shared_rules').select('*'));if(generation!==previewGeneration23||cloudUser?.uid!==uid||!isPlannerAdmin())return;if(!managerPeople.has(person.uid))throw Error('此帳戶已移除');previewSource23={person:{uid:person.uid,email:person.email,name:person.name},documents,rules:shared[0]?.data||null};document.getElementById('previewPerson23').textContent=person.email+' · 模擬檢視';previewModal23.querySelector('iframe').src='preview.html?v=20261005-23';}catch(e){document.getElementById('previewPerson23').textContent='無法模擬：'+e.message;}}
const managerRender23=renderManagerOverview;renderManagerOverview=function(){managerRender23();if(!managerAllowed())return;const entries=managerEntries();document.querySelectorAll('#managerVisitors .manager-person-row').forEach((row,i)=>{const person=entries[i]?.person;if(!person)return;const actions=document.createElement('div');actions.className='manager-actions23';const preview=makeAction('模擬檢視',()=>openPreview23(person));actions.append(preview);const remove=row.querySelector('.remove-planner');if(remove)actions.append(remove);else{const label=document.createElement('span');label.textContent='主使用者';actions.append(label);}row.append(actions);});};
const syncReceiptCard23=document.createElement('article');syncReceiptCard23.className='card';syncReceiptCard23.innerHTML='<h3>資料更新</h3><div id="syncReceipt23" role="status">正在讀取更新紀錄…</div>';document.getElementById('panel-data').append(syncReceiptCard23);
let receiptUid23=null,receiptStop23=null;
let receiptData23=null,receiptWork23=null;
const receiptDraw23=drawReceipt23;drawReceipt23=function(data){const latest=items=>items.map(x=>x.updatedAt).filter(Boolean).sort().at(-1),fallback={customers:customerMaster?.exportedAt?{sourceAt:customerMaster.exportedAt,count:customerDb.length}:null,visits:latest(excel)?{fetchedAt:latest(excel),count:excel.filter(x=>Number(x.year)===reportYear).length}:null,work:receiptWork23};receiptDraw23({...fallback,...(data||{})});};
const receiptConnect23=connectReceipt23;connectReceipt23=function(){const uid=plannerAccessReady()?cloudUser.uid:null;if(uid!==receiptUid23){receiptData23=null;receiptWork23=null;}receiptConnect23();};
const receiptRender23=render;render=function(){receiptRender23();drawReceipt23(receiptData23);};
let dailyNoticeKey23='';
const dailyRpc23=dailyRpc;dailyRpc=async function(action,lease=null){const result=await dailyRpc23(action,lease);if(action==='claim'&&result.status==='done'){const key=cloudUser.uid+':'+result.day;if(dailyNoticeKey23!==key){dailyNoticeKey23=key;toast('今天的公司資料已更新，直接載入'+(result.finishedAt?' · '+displayAccessTime(result.finishedAt):''));}}return result;};
function drawReceipt23(data){const box=document.getElementById('syncReceipt23');box.replaceChildren();for(const [key,label] of [['customers','客戶與座標'],['visits','訪況'],['work','工作自檢']]){const item=data?.[key],p=document.createElement('p');p.textContent=label+'：'+(item?displayAccessTime(item.sourceAt||item.fetchedAt)+' · '+Number(item.count)+' 筆':'尚無更新紀錄');box.append(p);}const p=document.createElement('p');p.className='notice';p.textContent='每天首次開啟會更新全部資料，今天更新完成後，再開啟會直接載入。';box.append(p);}
function connectReceipt23(){const uid=plannerAccessReady()?cloudUser.uid:null;if(uid===receiptUid23)return;receiptStop23?.();receiptUid23=uid;if(!uid){drawReceipt23(null);return;}firebaseApi.getDocs(cloudCollection('workSnapshots')).then(snapshot=>{if(cloudUser?.uid!==uid)return;const periods=workWindow(currentWorkPeriod()).periods,items=snapshot.docs.map(d=>d.data()).filter(x=>periods.includes(x.period));if(items.length)receiptWork23={sourceAt:items.map(x=>x.updatedAt).filter(Boolean).sort().at(-1),count:items.reduce((n,x)=>n+Number(x.count||0),0)};drawReceipt23(receiptData23);}).catch(()=>{});receiptStop23=firebaseApi.onSnapshot(firebaseApi.doc(cloudCollection('settings'),'syncReceipt'),s=>{if(cloudUser?.uid===uid){receiptData23=s.exists()?s.data():null;drawReceipt23(receiptData23);}},e=>{document.getElementById('syncReceipt23').textContent='更新紀錄讀取失敗：'+e.message;});}
const companyUpdate23=updateCompanyVisits;updateCompanyVisits=async function(dataset='visits'){const uid=cloudUser?.uid,result=await companyUpdate23(dataset);if(result?.success&&cloudUser?.uid===uid){const ref=firebaseApi.doc(cloudCollection('settings'),'syncReceipt');try{await firebaseApi.runTransaction(firestore,async tx=>{const old=await tx.get(ref),data=old.exists()?old.data():{},receipt={sourceAt:result.sourceAt||null,fetchedAt:new Date().toISOString()};if(['customers','all'].includes(dataset))data.customers={...receipt,count:result.customerCount??customerDb.length};if(['visits','all'].includes(dataset))data.visits={...receipt,count:result.visitCount??excel.filter(x=>Number(x.year)===reportYear).length};if(dataset==='work')data.work={...receipt,count:result.workCount??0};tx.set(ref,data);});}catch(e){showUpdateIssue('資料已更新，但更新紀錄儲存失敗：'+e.message);return {success:false,error:e.message};}}return result;};
const dailyStatus23=setSyncStatus;setSyncStatus=function(message){dailyStatus23(message);if(dailyRefreshActive){document.getElementById('companyWaitMessage').textContent='正在更新今天的客戶與座標、訪況及近兩個月工作紀錄。今天完成後再次開啟不用重新等待。\n'+message;}};
setInterval(connectReceipt23,1500);connectReceipt23();
const style23=document.createElement('style');style23.textContent='.manager-person-row{display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:0!important;border:1px solid var(--line);border-radius:14px;overflow:hidden;background:white}.manager-person-row>.manager-visitor{width:100%;height:100%;flex:1;border:0;border-radius:0}.manager-actions23{display:flex;align-items:center;justify-content:flex-end;gap:8px;min-height:48px;padding:6px 10px;border-top:1px solid var(--line)}.manager-actions23 button{min-height:34px;margin:0!important;font-size:12px;padding:5px 10px}.manager-actions23 span{font-size:12px;color:var(--muted)}#usageDetails23 summary{cursor:pointer;font-size:13px;margin:12px 0}.usage-bars23>div{position:relative;padding:8px 0;display:grid;grid-template-columns:1fr auto;gap:4px;border-bottom:1px solid var(--line);font-size:12px}.usage-bars23 i{grid-column:1/-1;height:7px;background:#176b61;border-radius:6px;grid-row:2}.preview-dialog23{width:98vw;height:96dvh;background:white;border-radius:12px;display:flex;flex-direction:column;overflow:hidden}.preview-toolbar23{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:8px 12px;font-size:13px}.preview-dialog23 iframe{border:0;width:100%;flex:1;background:#edf2f5}#previewModal23{padding:8px;z-index:3000}#syncReceipt23 p{font-size:13px;line-height:1.5;margin:8px 0}';document.head.append(style23);
releaseButton.textContent='v1.23';releaseButton.setAttribute('aria-label','版本 v1.23，查看更新紀錄');const entry23=document.createElement('article');entry23.className='release-entry';entry23.innerHTML='<b>v1.23</b><time>2026-10-05</time><p>管理者容量分類、帳戶用量及唯讀模擬檢視；收折其他用量、修正訪員卡片對齊；每日更新顯示來源時間與筆數。</p>';releaseHistory.querySelector('h2').after(entry23);
