// Route-only points and notes never enter company customer/visit collections.
const cache28=cacheState;cacheState=function(){cache28();const key=accountKey(),data=JSON.parse(localStorage.getItem(key)||'{}');data.extraStops=routeExtras28;data.notes=routeNotes28;localStorage.setItem(key,JSON.stringify(data));};
const restore28=restoreState;restoreState=function(data){restoreRouteDetails28(data);restore28(data);};
const selected28=selectedRecords;selectedRecords=function(){const all=new Map(records().map(x=>[x.code,x]));for(const x of Object.values(routeExtras28))all.set(x.code,x);return [...chosen].map(code=>all.get(code)).filter(Boolean);};
function stopKind28(x){if(x.kind)return x.kind;const owner=document.getElementById('ownerFilter').value||customerMaster?.preferredOwner||'';return owner&&x.owner&&x.owner!==owner?'support':'own';}
const persist28=persistTrip;persistTrip=function(){for(const code of Object.keys(routeNotes28))if(!chosen.has(code))delete routeNotes28[code];for(const code of Object.keys(routeExtras28))if(!chosen.has(code))delete routeExtras28[code];persist28();};

const purge28=purgeClosedStores;purgeClosedStores=function(items){const result=purge28(items);let changed=false;for(const [code,x] of Object.entries(routeExtras28))if(x.kind==='support'&&closedStoreCodes.has(x.companyCode)){chosen.delete(code);delete routeExtras28[code];delete routeNotes28[code];changed=true;}if(changed)dirty();return result;};
function addRoutePoint28(point){if(!plannerAccessReady())return;if(chosen.size>=300)return toast('行程最多 300 點');if(!validGps(point.gps))return toast('此地點沒有可用座標');const existing=Object.values(routeExtras28).find(x=>x.kind===point.kind&&x.name===point.name&&JSON.stringify(x.gps)===JSON.stringify(point.gps));const x=existing||{...point,code:'route:'+crypto.randomUUID()};routeExtras28[x.code]=x;chosen.add(x.code);persistTrip();fitNext=true;render();toast('已加入 '+x.name);drawExtraResults28();}
const extraDrawer28=document.createElement('div');extraDrawer28.id='extraRouteDrawer28';extraDrawer28.className='modal credential-drawer';extraDrawer28.innerHTML='<div class="dialog"><button class="drawer-close" aria-label="關閉其他地點" onclick="closeModal(\'extraRouteDrawer28\')">✕</button><h2>其他地點</h2><div class="extra-tabs28"><button id="supportTab28">支援店家</button><button id="privateTab28">私人地點</button></div><form id="extraSearchForm28"><input id="extraSearch28" type="search" maxlength="180" placeholder="店名、代碼或負責人" aria-label="搜尋其他地點"><button class="primary">搜尋</button></form><p id="extraStatus28" role="status"></p><div id="extraResults28"></div><details id="coordinateEntry28" hidden><summary>直接輸入座標</summary><form id="coordinateForm28"><label>地點名稱<input id="coordinateName28" required maxlength="180"></label><label>緯度<input id="coordinateLat28" type="number" step="any" min="-90" max="90" required></label><label>經度<input id="coordinateLng28" type="number" step="any" min="-180" max="180" required></label><button class="primary">加入行程</button></form></details></div>';document.body.append(extraDrawer28);
let extraMode28='support',placeResults28=[],placeController28=null;
function openExtra28(){if(!plannerAccessReady())return;openModal('extraRouteDrawer28');drawExtraResults28();document.getElementById('extraSearch28').focus();}
const extraButton28=makeAction('其他地點',openExtra28);extraButton28.id='extraRouteButton28';document.querySelector('.customer-table-header').append(extraButton28);
function setExtraMode28(mode){placeController28?.abort();extraMode28=mode;document.getElementById('extraSearch28').value='';document.getElementById('extraSearch28').placeholder=mode==='support'?'店名、代碼或負責人':'餐廳、郵局、地點或地址';document.getElementById('coordinateEntry28').hidden=mode!=='personal';document.getElementById('extraStatus28').textContent='';drawExtraResults28();}
document.getElementById('supportTab28').onclick=()=>setExtraMode28('support');document.getElementById('privateTab28').onclick=()=>setExtraMode28('personal');
function drawExtraResults28(){const box=document.getElementById('extraResults28');box.replaceChildren();document.getElementById('supportTab28').classList.toggle('primary',extraMode28==='support');document.getElementById('privateTab28').classList.toggle('primary',extraMode28==='personal');const term=document.getElementById('extraSearch28').value.trim().toLowerCase();const rows=extraMode28==='support'?records().filter(x=>stopKind28(x)==='support'&&[x.name,x.code,x.owner,x.channel].join(' ').toLowerCase().includes(term)):placeResults28;for(const x of rows.slice(0,80)){const row=document.createElement('article');row.className='extra-result28';const text=document.createElement('div'),name=document.createElement('b'),sub=document.createElement('small');name.textContent=x.name;sub.textContent=extraMode28==='support'?(x.owner||'')+' · '+x.code:String(x.description||'');text.append(name,sub);const already=extraMode28==='support'?(chosen.has(x.code)||Object.values(routeExtras28).some(y=>y.kind==='support'&&y.companyCode===x.code)):Object.values(routeExtras28).some(y=>y.kind==='personal'&&y.name===x.name&&JSON.stringify(y.gps)===JSON.stringify(x.gps));const add=makeAction(already?'已加入':'＋ 加入',()=>{if(extraMode28==='support'){addRoutePoint28({name:x.name,gps:x.gps,kind:'support',owner:x.owner,companyCode:x.code});}else addRoutePoint28({name:x.name,gps:x.gps,kind:'personal'});});add.disabled=already||!validGps(x.gps);row.append(text,add);box.append(row);}if(!rows.length)box.textContent=extraMode28==='support'?'目前名冊沒有符合的其他負責人店家':'輸入地點名稱後搜尋';}
document.getElementById('extraSearch28').oninput=()=>{if(extraMode28==='support')drawExtraResults28();};
document.getElementById('extraSearchForm28').onsubmit=async event=>{event.preventDefault();if(extraMode28==='support')return drawExtraResults28();const term=document.getElementById('extraSearch28').value.trim();if(!term)return;placeController28?.abort();const ctrl=new AbortController(),uid=cloudUser?.uid;placeController28=ctrl;const status=document.getElementById('extraStatus28');status.textContent='搜尋中…';try{const response=await fetch('https://photon.komoot.io/api/?'+new URLSearchParams({q:term,limit:'8',bbox:'119,21,123,26'}),{signal:AbortSignal.any([ctrl.signal,AbortSignal.timeout(15000)]),referrerPolicy:'no-referrer'});if(!response.ok)throw Error('地點搜尋暫時無法使用');const data=await response.json();if(ctrl!==placeController28||uid!==cloudUser?.uid||extraMode28!=='personal')return;placeResults28=(data.features||[]).filter(x=>Array.isArray(x.geometry?.coordinates)).map(x=>({name:String(x.properties?.name||x.properties?.street||term),description:[x.properties?.city,x.properties?.district,x.properties?.street,x.properties?.housenumber].filter(Boolean).join(' '),gps:[x.geometry.coordinates[1],x.geometry.coordinates[0]]})).filter(x=>validGps(x.gps));status.textContent=placeResults28.length?'選擇要加入的地點':'沒有找到；可改用完整地址或直接輸入座標';drawExtraResults28();}catch(error){if(ctrl!==placeController28||uid!==cloudUser?.uid)return;status.textContent=error.name==='AbortError'?'':error.name==='TimeoutError'?'搜尋逾時，請重試':error.message;}finally{if(placeController28===ctrl)placeController28=null;}};
document.getElementById('coordinateForm28').onsubmit=event=>{event.preventDefault();addRoutePoint28({name:document.getElementById('coordinateName28').value.trim(),gps:[Number(document.getElementById('coordinateLat28').value),Number(document.getElementById('coordinateLng28').value)],kind:'personal'});};
function manualOrder28(from,to){const codes=[...chosen],i=codes.indexOf(from),j=codes.indexOf(to);if(i<0||j<0||i===j)return;codes.splice(i,1);codes.splice(j,0,from);abortAutoRoute();autoRouteEnabled=false;localStorage.setItem(autoPreferenceStorage(),'false');saveAutoPreference();chosen=new Set(codes);autoRouteDone='';persistTrip();render();}
// Long press on the handle only; scrolling outside handles remains native.
let drag28=null;
function bindDrag28(handle,row,code){handle.onpointerdown=event=>{if(event.button!==0)return;const start={id:event.pointerId,code,row,x:event.clientX,y:event.clientY,active:false};drag28=start;handle.setPointerCapture(event.pointerId);start.timer=setTimeout(()=>{if(drag28!==start)return;start.active=true;row.classList.add('dragging28');navigator.vibrate?.(20);},320);};handle.onpointermove=event=>{const d=drag28;if(!d||d.id!==event.pointerId)return;if(!d.active){if(Math.hypot(event.clientX-d.x,event.clientY-d.y)>12){clearTimeout(d.timer);drag28=null;}return;}event.preventDefault();document.querySelectorAll('.triprow.drop28').forEach(x=>x.classList.remove('drop28'));const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('.triprow[data-code]');if(target&&target!==d.row){d.target=target.dataset.code;target.classList.add('drop28');}else d.target=null;if(event.clientY<90)window.scrollBy(0,-12);else if(event.clientY>innerHeight-100)window.scrollBy(0,12);};const end=event=>{const d=drag28;if(!d||d.id!==event.pointerId)return;clearTimeout(d.timer);drag28=null;d.row.classList.remove('dragging28');document.querySelectorAll('.drop28').forEach(x=>x.classList.remove('drop28'));if(event.type!=='pointercancel'&&d.active&&d.target)manualOrder28(d.code,d.target);};handle.onpointerup=end;handle.onpointercancel=end;handle.onkeydown=event=>{if(!['ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const codes=[...chosen],i=codes.indexOf(code),other=codes[i+(event.key==='ArrowUp'?-1:1)];if(other)manualOrder28(code,other);};}
renderTrip=function(){if(drag28?.active)return;const box=document.getElementById('tripList');box.replaceChildren();const rows=selectedRecords();document.getElementById('routeStopCount').textContent=rows.length+' 個地點';if(!rows.length){box.append(makeAction('去選店家',()=>switchView('list')));return;}for(const [i,x] of rows.entries()){const kind=stopKind28(x),row=document.createElement('article');row.className='triprow route-'+kind+'28';row.dataset.code=x.code;const handle=document.createElement('button');handle.className='drag-handle28';handle.textContent='⠿';handle.setAttribute('aria-label','長按拖曳 '+x.name+'；鍵盤上下鍵調整');const num=document.createElement('div');num.className='tripnum';num.textContent=i+1;const text=document.createElement('div');text.className='triptext';const name=document.createElement('b');name.textContent=x.name;const meta=document.createElement('div');meta.className='meta';meta.textContent=kind==='personal'?'私人地點':kind==='support'?'支援 · '+(x.owner||'其他訪員'):'我的店家';const note=document.createElement('input');note.className='route-note28';note.maxLength=1000;note.placeholder='當次路線備註';note.setAttribute('aria-label',x.name+' 路線備註');note.value=routeNotes28[x.code]||'';note.oninput=()=>{if(note.value)routeNotes28[x.code]=note.value;else delete routeNotes28[x.code];dirty();};text.append(name,meta,note);const actions=document.createElement('div');actions.className='tripactions';if(validGps(x.gps)){const nav=document.createElement('a');nav.className='navlink primary popup-nav22';nav.href=navigateUrl(x);nav.target='_blank';nav.rel='noopener noreferrer';nav.textContent='導航';actions.append(nav);}actions.append(makeAction('移除',()=>choose(x.code,false)));row.append(handle,num,text,actions);bindDrag28(handle,row,x.code);box.append(row);}};
const map28=updateMap;updateMap=function(fit){map28(fit);for(const [i,x] of mapRows.entries()){const kind=stopKind28(x);markers.get(x.code)?.setIcon(L.divIcon({className:'',html:'<div class="pin route-'+kind+'28">'+(i+1)+'</div>',iconSize:[32,32],iconAnchor:[16,16]}));}};
const style28=document.createElement('style');style28.textContent='.extra-tabs28{display:flex;gap:8px;margin:12px 0}#extraSearchForm28{display:flex;gap:8px}#extraSearch28{min-width:0;flex:1}.extra-result28{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #dce5e9}.extra-result28 small{display:block;color:var(--muted)}#extraResults28{max-height:55dvh;overflow:auto}.triprow{grid-template-columns:32px 30px minmax(0,1fr) auto!important}.drag-handle28{touch-action:none;cursor:grab;font-size:25px;padding:0;min-width:30px;min-height:48px;background:none;border:0}.route-note28{width:100%;min-height:36px;margin-top:6px;font-size:14px}.dragging28{opacity:.55}.drop28{outline:2px solid #0f766e}.pin.route-support28{background:#d97706!important}.pin.route-personal28{background:#8b5cf6!important}.pin.route-own28{background:#2563eb!important}.triprow.route-support28{border-left:4px solid #d97706}.triprow.route-personal28{border-left:4px solid #8b5cf6}#extraRouteButton28{white-space:nowrap}.tripactions .navlink{color:white!important}@media(max-width:600px){.triprow{gap:5px!important;padding:10px 7px!important}.triprow .tripactions{flex-direction:column!important}.triptext{min-width:0}.triptext>b{overflow-wrap:anywhere}}';document.head.append(style28);
releaseButton.textContent='v1.28';releaseButton.setAttribute('aria-label','版本 v1.28，查看更新紀錄');const entry28=document.createElement('article');entry28.className='release-entry';entry28.innerHTML='<b>v1.28</b><time>2026-10-07</time><p>支援店家與私人地點；路線點分類顏色；長按拖曳順序；當次備註隨行程同步，移除點時清除。</p>';releaseHistory.querySelector('h2').after(entry28);render();
