// Five personal favourite routes, isolated by the existing owner RLS.
let favoritesUid22=null,favoritesStop22=null,favorites22=[],favoritesBusy22=false;
const favoriteRef22=()=>firebaseApi.doc(cloudCollection('settings'),'favoriteRoutes');
const favoriteDrawer22=document.createElement('div');favoriteDrawer22.id='favoriteRoutesDrawer';favoriteDrawer22.className='modal credential-drawer';favoriteDrawer22.innerHTML='<div class="dialog"><button class="drawer-close" onclick="closeModal(\'favoriteRoutesDrawer\')" aria-label="關閉常用路線">✕</button><h2>常用路線 <small id="favoritesCount22"></small></h2><div id="favoritesList22"></div><form id="favoritesSave22"><label>路線名稱<input id="favoriteName22" maxlength="40" placeholder="例如：龍潭週一路線" required></label><button class="primary" type="submit">儲存目前行程</button></form><p id="favoritesStatus22" role="status"></p></div>';document.body.append(favoriteDrawer22);
const favoriteButton22=makeAction('☆ 常用路線',()=>{drawFavorites22();openModal('favoriteRoutesDrawer');});favoriteButton22.id='favoriteRoutesButton';customerHeader.append(favoriteButton22);
function normalizeFavorites22(data){return Array.isArray(data?.routes)?data.routes.slice(0,5).filter(r=>r&&typeof r.id==='string'&&typeof r.name==='string'&&Array.isArray(r.codes)).map(r=>({...r,name:r.name.slice(0,40),codes:r.codes.filter(c=>typeof c==='string').slice(0,300)})):[];}
function drawFavorites22(){const active=favorites22.filter(r=>r.active!==false);document.getElementById('favoritesCount22').textContent=active.length+'/5';document.getElementById('favoritesList22').replaceChildren(...active.map(r=>{const row=document.createElement('article');row.className='favorite-row22';const name=document.createElement('b');name.textContent=r.name;const count=document.createElement('small');count.textContent=r.codes.length+' 間店';const actions=document.createElement('div');actions.append(makeAction('套用',()=>applyFavorite22(r)),makeAction('更新',()=>saveFavorite22(r.id,r.name)),makeAction('移除',()=>mutateFavorites22(list=>list.map(x=>x.id===r.id?{...x,active:false}:x))));row.append(name,count,actions);return row;}));if(!active.length)document.getElementById('favoritesList22').textContent='選好店家後，儲存常用路線。';const removed=favorites22.find(r=>r.active===false);if(removed)document.getElementById('favoritesList22').append(makeAction('復原「'+removed.name+'」',()=>mutateFavorites22(list=>list.map(x=>x.id===removed.id?{...x,active:true}:x))));document.querySelector('#favoritesSave22 button').disabled=favoritesBusy22||active.length>=5;favoriteDrawer22.querySelectorAll('button:not(.drawer-close)').forEach(b=>{if(favoritesBusy22)b.disabled=true;});}
async function mutateFavorites22(change){if(!plannerAccessReady()||favoritesBusy22)return;const uid=cloudUser.uid,ref=favoriteRef22();favoritesBusy22=true;document.getElementById('favoritesStatus22').textContent='儲存中…';drawFavorites22();try{let next;await firebaseApi.runTransaction(firestore,async tx=>{const snap=await tx.get(ref);if(cloudUser?.uid!==uid)throw Error('登入帳戶已變更');next=change(normalizeFavorites22(snap.exists()?snap.data():null));if(next.filter(r=>r.active!==false).length>5)throw Error('常用路線最多五組');tx.set(ref,{routes:next,updatedAt:firebaseApi.serverTimestamp()});});if(cloudUser?.uid===uid){favorites22=next;document.getElementById('favoritesStatus22').textContent='已儲存';}}catch(e){if(cloudUser?.uid===uid)document.getElementById('favoritesStatus22').textContent=e.message||'儲存失敗，請重試';}finally{favoritesBusy22=false;drawFavorites22();}}
async function saveFavorite22(id=null,name=null){const codes=selectedRecords().map(x=>String(x.code));if(!codes.length){document.getElementById('favoritesStatus22').textContent='請先選取店家';return;}const label=(name||document.getElementById('favoriteName22').value).trim();if(!label)return;await mutateFavorites22(list=>{const route={id:id||crypto.randomUUID(),name:label,codes,extraStops:structuredClone(routeExtras28),active:true,depotStart:autoDepotStart,autoRouteEnabled};if(id)return list.map(r=>r.id===id?route:r);if(list.filter(r=>r.active!==false).length>=5)throw Error('常用路線最多五組');const free=list.findIndex(r=>r.active===false);if(free>=0)list[free]=route;else list.push(route);return list;});}
document.getElementById('favoritesSave22').onsubmit=e=>{e.preventDefault();saveFavorite22();};
async function applyFavorite22(route){if(!plannerAccessReady())return;const available=new Set([...records().map(x=>String(x.code)),...Object.keys(route.extraStops||{})]),codes=route.codes.filter(c=>available.has(c));if(!codes.length){document.getElementById('favoritesStatus22').textContent='這組路線目前沒有可用的店家';return;}abortAutoRoute();const retainedNotes=routeNotes28;restoreRouteDetails28({extraStops:route.extraStops,notes:retainedNotes});chosen=new Set(codes);autoRouteEnabled=route.autoRouteEnabled!==false;autoDepotStart=route.depotStart!==false;localStorage.setItem(autoPreferenceStorage(),String(autoRouteEnabled));localStorage.setItem(depotPreferenceStorage(),String(autoDepotStart));autoRouteDone='';autoRouteGeometry=null;persistTrip();saveAutoPreference();fitNext=true;closeModal('favoriteRoutesDrawer');switchView('map');render();toast('已套用 '+route.name+(codes.length<route.codes.length?' · '+(route.codes.length-codes.length)+' 間已不在目前客戶名冊':''));}
function connectFavorites22(){const uid=plannerAccessReady()?cloudUser.uid:null;if(uid===favoritesUid22)return;favoritesStop22?.();favoritesStop22=null;favoritesUid22=uid;favorites22=[];document.getElementById('favoritesStatus22').textContent='';drawFavorites22();if(!uid)return;favoritesStop22=firebaseApi.onSnapshot(favoriteRef22(),snap=>{if(cloudUser?.uid!==uid)return;favorites22=normalizeFavorites22(snap.exists()?snap.data():null);drawFavorites22();},e=>{if(cloudUser?.uid===uid)document.getElementById('favoritesStatus22').textContent=e.message||'常用路線載入失敗';});}
const favoriteRender22=render;render=function(){favoriteRender22();connectFavorites22();};setInterval(connectFavorites22,1500);
// Keep a clear, coordinate-based navigation button in every store popup.
const popupMap22=updateMap;updateMap=function(fit){const openCode22=[...markers].find(([code,marker])=>marker.isPopupOpen())?.[0];popupMap22(fit);for(const x of mapRows){const marker=markers.get(x.code);if(!marker)continue;const popup=document.createElement('div'),name=document.createElement('b');name.textContent=x.name;const nav=document.createElement('a');nav.className='navlink primary popup-nav22';nav.textContent='導航';nav.href=navigateUrl(x);nav.target='_blank';nav.rel='noopener noreferrer';popup.append(name,nav,makeAction(chosen.has(x.code)?'移出行程':'加入行程',()=>choose(x.code,!chosen.has(x.code))));marker.bindPopup(popup);if(x.code===openCode22)marker.openPopup();}};
document.querySelector('.manager-channel').open=true;
const usageRender22=refreshSupabaseUsage;refreshSupabaseUsage=async function(){await usageRender22();for(const el of document.querySelectorAll('#supabaseUsageResult p'))if(el.textContent.includes('尚未接上管理 API'))el.textContent='檔案與網路流量：請至 Supabase 後台查看';};document.getElementById('supabaseUsageRefresh').onclick=refreshSupabaseUsage;
const favStyle22=document.createElement('style');favStyle22.textContent='.customer-table-header{flex-wrap:wrap;gap:8px}#favoriteRoutesButton{min-height:36px;padding:6px 10px;font-size:13px}.favorite-row22{display:grid;grid-template-columns:1fr auto;gap:6px;padding:14px 0;border-bottom:1px solid var(--line)}.favorite-row22>div{grid-column:1/-1;display:flex;gap:6px}.favorite-row22 button{min-height:36px;padding:5px 12px;font-size:13px}#favoritesSave22{margin-top:20px}#favoritesSave22>button{width:100%;margin-top:10px}#favoritesCount22{font-size:13px;color:var(--muted)}.popup-nav22{display:flex;margin-top:10px;min-height:44px;width:100%}';document.head.append(favStyle22);
releaseButton.textContent='v1.22';releaseButton.setAttribute('aria-label','版本 v1.22，查看更新紀錄');const entry22=document.createElement('article');entry22.className='release-entry';entry22.innerHTML='<b>v1.22</b><time>2026-10-05</time><p>每個帳戶五組常用路線、同步保存與一鍵套用；店點導航；各通路訪況預設展開；簡化用量提示。</p>';releaseHistory.querySelector('h2').after(entry22);render();
const navContrast22=document.createElement('style');navContrast22.textContent='.leaflet-container a.popup-nav22,.leaflet-container a.navlink.primary{color:#fff!important;background:#087f68!important;text-decoration:none!important;font-weight:700}.leaflet-container a.popup-nav22:hover{background:#066653!important;color:#fff!important}';document.head.append(navContrast22);
const mobileNav22=document.createElement('style');mobileNav22.textContent="@font-face{font-family:'LukeSignature';src:url('allura-regular.ttf') format('truetype');font-display:swap}.luke-signature{font-family:'LukeSignature',cursive!important;font-size:25px!important;font-style:normal!important;font-weight:400!important;letter-spacing:.3px;opacity:.7}@media(max-width:600px){.luke-signature{font-size:22px!important}.bottomnav{padding:8px 4px calc(8px + env(safe-area-inset-bottom))!important}.bottomnav button{min-height:66px!important;padding:7px 2px!important;font-size:12px!important;line-height:1.25!important}.bottomnav .icon{font-size:26px!important;height:29px!important}.bottomnav .icon svg{width:27px!important;height:27px!important}body[data-mobile-view='map'] #map{height:calc(100dvh - 194px - env(safe-area-inset-bottom))!important}body[data-mobile-view='map'] .shell{padding-bottom:96px!important}}";document.head.append(mobileNav22);
refreshSupabaseUsage=async function(){if(!isPlannerAdmin()||!plannerAccessReady()||supabaseUsageBusy)return;supabaseUsageBusy=true;const uid=cloudUser.uid,button=document.getElementById('supabaseUsageRefresh');button.disabled=true;try{const data=plannerResult(await supabasePlannerClient.rpc('planner_database_usage'));if(cloudUser?.uid!==uid||!isPlannerAdmin())return;const used=Number(data.database_bytes),stored=Number(data.storage_bytes);if(!Number.isFinite(used)||!Number.isFinite(stored))throw Error('容量資料格式不符');const box=document.getElementById('supabaseUsageResult');box.replaceChildren();for(const text of ['資料庫 '+(used/1048576).toFixed(1)+'／500 MB · 剩餘 '+Math.max(0,(524288000-used)/1048576).toFixed(1)+' MB','檔案儲存 '+(stored/1048576).toFixed(1)+' MB · '+Number(data.storage_files)+' 個檔案','傳輸快照 '+data.egress_gb_snapshot+' GB · 快取傳輸 '+data.cached_egress_gb_snapshot+' GB','傳輸為官方後台快照 '+data.egress_snapshot_date+'；非即時更新']){const p=document.createElement('p');p.textContent=text;box.append(p);}const link=document.createElement('a');link.href='https://supabase.com/dashboard/org/lkdwhqyppahcgaljfpzu/usage?projectRef=kzzyeoehfbvslxfcyayi';link.target='_blank';link.rel='noopener noreferrer';link.textContent='查看官方最新用量';box.append(link);const time=document.createElement('p');time.className='notice';time.textContent='容量查詢 '+displayAccessTime(data.measured_at);box.append(time);supabaseUsageLast=Date.now();}catch(e){document.getElementById('supabaseUsageResult').textContent=e.message||'用量查詢失敗';}finally{supabaseUsageBusy=false;button.disabled=false;}};
document.getElementById('supabaseUsageRefresh').onclick=refreshSupabaseUsage;
