// Narrow server catalogue: never reads other users' documents, notes or credentials.
let supportRows29=[],supportTotal29=0,supportOffset29=0,supportGeneration29=0,supportTimer29=null,supportUid29=null,supportBusy29=false;
const supportCount29=document.createElement('p');supportCount29.id='supportCount29';supportCount29.className='notice';document.getElementById('extraResults28').before(supportCount29);
const supportMore29=makeAction('載入更多',()=>loadSupport29(true));supportMore29.id='supportMore29';supportMore29.hidden=true;document.getElementById('extraResults28').after(supportMore29);
async function loadSupport29(more=false){if(!plannerAccessReady()||extraMode28!=='support')return;const uid=cloudUser.uid,term=document.getElementById('extraSearch28').value.trim();if(more&&supportBusy29)return;const generation=++supportGeneration29;supportBusy29=true;const status=document.getElementById('extraStatus28');status.textContent='正在載入全體客戶…';if(!more){supportRows29=[];supportOffset29=0;supportTotal29=0;drawExtraResults28();}try{const data=plannerResult(await supabasePlannerClient.rpc('planner_support_customers',{search_term:term,page_offset:more?supportOffset29:0}));if(generation!==supportGeneration29||uid!==cloudUser?.uid||extraMode28!=='support')return;if(!Array.isArray(data?.items)||!Number.isSafeInteger(data.total))throw Error('客戶名冊格式不符');const incoming=data.items.filter(x=>x&&typeof x.code==='string'&&typeof x.name==='string');supportRows29=more?[...supportRows29,...incoming]:incoming;supportOffset29+=data.items.length;supportTotal29=data.total;supportUid29=uid;status.textContent='';drawExtraResults28();}catch(error){if(generation!==supportGeneration29||uid!==cloudUser?.uid||extraMode28!=='support')return;status.textContent='全體客戶載入失敗：'+String(error.message||error);supportRows29=[];supportTotal29=0;drawExtraResults28();}finally{if(generation===supportGeneration29){supportBusy29=false;supportMore29.disabled=false;}}}
const results29=drawExtraResults28;drawExtraResults28=function(){if(extraMode28!=='support'){supportCount29.hidden=true;supportMore29.hidden=true;return results29();}supportCount29.hidden=false;supportCount29.textContent='全體客戶 '+supportTotal29+' 間';document.getElementById('supportTab28').classList.add('primary');document.getElementById('privateTab28').classList.remove('primary');const box=document.getElementById('extraResults28');box.replaceChildren();for(const x of supportRows29){const row=document.createElement('article');row.className='extra-result28';const text=document.createElement('div'),name=document.createElement('b'),sub=document.createElement('small');name.textContent=x.name;sub.textContent=(x.owner||'未指定訪員')+' · '+x.code+(x.channel?' · '+x.channel:'');text.append(name,sub);const own=records().find(y=>y.code===x.code&&stopKind28(y)==='own');const added=chosen.has(x.code)||Object.values(routeExtras28).some(y=>y.kind==='support'&&y.companyCode===x.code);const add=makeAction(added?'已加入':'＋ 加入',()=>{if(own)choose(own.code,true);else addRoutePoint28({name:x.name,gps:x.gps,kind:'support',owner:x.owner,companyCode:x.code});drawExtraResults28();});add.disabled=added||!validGps(x.gps);row.append(text,add);box.append(row);}if(!supportRows29.length)box.textContent=supportBusy29?'載入中…':'沒有符合的客戶';supportMore29.hidden=supportOffset29>=supportTotal29;supportMore29.disabled=supportBusy29;};
const openSupport29=openExtra28;openExtra28=function(){openSupport29();if(extraMode28==='support')loadSupport29();};extraButton28.onclick=openExtra28;
const mode29=setExtraMode28;setExtraMode28=function(mode){clearTimeout(supportTimer29);supportGeneration29++;supportBusy29=false;mode29(mode);if(mode==='support')loadSupport29();};
document.getElementById('extraSearch28').oninput=()=>{if(extraMode28!=='support')return;clearTimeout(supportTimer29);supportGeneration29++;supportTimer29=setTimeout(()=>loadSupport29(),300);};
const searchForm29=document.getElementById('extraSearchForm28').onsubmit;document.getElementById('extraSearchForm28').onsubmit=event=>{if(extraMode28==='support'){event.preventDefault();clearTimeout(supportTimer29);loadSupport29();}else return searchForm29(event);};
const render29=render;render=function(){if(supportUid29&&supportUid29!==cloudUser?.uid){supportGeneration29++;supportRows29=[];supportTotal29=0;supportOffset29=0;supportUid29=null;}render29();};
releaseButton.textContent='v1.29';releaseButton.setAttribute('aria-label','版本 v1.29，查看更新紀錄');const entry29=document.createElement('article');entry29.className='release-entry';entry29.innerHTML='<b>v1.29</b><time>2026-10-07</time><p>所有訪員可搜尋全站最新客戶名冊，加入支援路線；保留個人訪況、行程與帳密隔離。</p>';releaseHistory.querySelector('h2').after(entry29);
