// Compact mobile map controls and actual driving geometry.
const ROAD_ROUTE_SERVICE21='https://router.project-osrm.org';
let roadRoutesAllowed21=true; // Owner approved OSRM coordinate transmission.
let roadState21={key:'',status:'idle',route:null,error:''},roadController21=null,roadTimer21=null,roadRetry21=0;
const roadCache21=new Map();let roadFittedKey21='';
function roadPoints21(){const pts=selectedRecords().filter(x=>validGps(x.gps)).map(x=>x.gps.map(Number));if(!pts.length)return [];if(autoDepotStart)pts.unshift(DEPOT.gps.map(Number));pts.push(DEPOT.gps.map(Number));return pts;}
function roadKey21(){return JSON.stringify([cloudUser?.uid||'',roadPoints21()]);}
function paintRoad21(){if(!map)return;removeRouteLine();if(activeView!=='map')return;const key=roadKey21();if(roadState21.key===key&&roadState21.route){routeLine=L.geoJSON(roadState21.route.geometry,{style:{color:'#2563eb',weight:5,opacity:.85},interactive:false}).addTo(map);if(roadFittedKey21!==key){roadFittedKey21=key;requestAnimationFrame(()=>{if(routeLine&&activeView==='map'){map.invalidateSize({pan:false});map.fitBounds(routeLine.getBounds(),{padding:[30,35],maxZoom:15});}});}}}
drawPlannedConnections=paintRoad21;
function roadText21(){if(!roadPoints21().length)return '';if(!roadRoutesAllowed21)return '行車路線待啟用';if(roadState21.key!==roadKey21()||roadState21.status==='loading')return '正在計算行車路線…';if(roadState21.status==='error')return roadState21.error+' · 點此重試';const r=roadState21.route;return r?'預估路程 '+(r.distance/1000).toFixed(1)+' 公里 · 約 '+Math.ceil(r.duration/60)+' 分鐘':'';}
function scheduleRoad21(){if(!roadRoutesAllowed21||!plannerAccessReady()||activeView!=='map'||routeBusy)return;const key=roadKey21(),points=roadPoints21();if(!points.length){clearTimeout(roadTimer21);roadController21?.abort();roadState21={key,status:'idle',route:null,error:''};paintRoad21();return;}
 if(roadState21.key===key&&(['loading','done'].includes(roadState21.status)||Date.now()<roadRetry21))return;
 clearTimeout(roadTimer21);roadController21?.abort();roadState21={key,status:'loading',route:null,error:''};roadTimer21=setTimeout(()=>fetchRoad21(key,points),700);
}
async function fetchRoad21(key,points){const cached=roadCache21.get(key);if(cached){roadState21={key,status:'done',route:cached,error:''};render();return;}const ctrl=new AbortController();roadController21=ctrl;let timeout=setTimeout(()=>ctrl.abort(),20000);try{
 if(points.length>100)throw Error('單次最多 99 間店，請分段安排行程');
 const coordinates=points.map(([lat,lng])=>lng+','+lat).join(';');const response=await fetch(ROAD_ROUTE_SERVICE21+'/route/v1/driving/'+coordinates+'?overview=full&geometries=geojson&steps=false',{signal:ctrl.signal,referrerPolicy:'strict-origin-when-cross-origin'});if(!response.ok)throw Error('道路服務暫時無法回應（'+response.status+'）');const data=await response.json(),r=data.routes?.[0];if(data.code!=='Ok'||!r||!Number.isFinite(r.distance)||!Number.isFinite(r.duration)||r.geometry?.type!=='LineString'||!Array.isArray(r.geometry.coordinates)||r.geometry.coordinates.length<2)throw Error('這組店點無法取得行車路線');
 if(key!==roadKey21()||roadController21!==ctrl)return;roadCache21.set(key,{distance:r.distance,duration:r.duration,geometry:r.geometry});if(roadCache21.size>8)roadCache21.delete(roadCache21.keys().next().value);roadState21={key,status:'done',route:roadCache21.get(key),error:''};roadRetry21=0;render();
 }catch(error){if(roadController21!==ctrl||key!==roadKey21())return;roadState21={key,status:'error',route:null,error:ctrl.signal.aborted?'道路服務回應逾時':String(error.message||error)};roadRetry21=Infinity;render();}finally{clearTimeout(timeout);if(roadController21===ctrl)roadController21=null;}}
const hint21=document.getElementById('routeHint');hint21.onclick=()=>{if(roadState21.status==='error'){roadRetry21=0;roadState21.key='';render();}};hint21.setAttribute('role','status');
const mapControls21=document.querySelector('.route-controls');mapControls21.replaceChildren(pick20,document.querySelector('.suggestBtn'),depotChoice,clearRouteButton);pick20.textContent='＋ 選店';clearRouteButton.textContent='清空';clearRouteButton.setAttribute('aria-label','取消全部行程');depotChoice.lastChild.textContent='營業所';
const autoButton21=updateAutoRouteButton;updateAutoRouteButton=function(){autoButton21();document.querySelector('.suggestBtn').textContent='自動安排';};
const frame21=document.querySelector('.mapframe'),tools21=document.querySelector('.maptools');frame21.append(tools21);tools21.querySelector('button[onclick="locateMe()"]')?.setAttribute('aria-label','我的位置');
const mapIcons21={report:'<circle cx="12" cy="12" r="8"/><path d="M12 4v8l5 3M4 12h8"/>',work:'<path d="M9 4H6v17h14V4h-3M9 3h8v4H9zM9 12l2 2 5-5M9 18h7"/>'};
for(const [view,shape] of Object.entries(mapIcons21)){const icon=document.querySelector('.bottomnav [data-view="'+view+'"] .icon');if(icon)icon.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" width="23" height="23" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+shape+'</svg>';}
const plainMarkers21=updateMap;updateMap=function(fit){plainMarkers21(fit);for(const [i,x] of mapRows.entries())markers.get(x.code)?.setIcon(L.divIcon({className:'',html:'<div class="pin route-stop21" aria-label="'+esc((i+1)+'. '+x.name)+'">'+(i+1)+'</div>',iconSize:[32,32],iconAnchor:[16,16]}));};
document.querySelector('.legend').classList.add('hide');
let resizeTimer21=null,mapResizeObserver21=null,attachedMap21=null;
function resizeMap21(){clearTimeout(resizeTimer21);resizeTimer21=setTimeout(()=>{if(map&&activeView==='map'){map.invalidateSize({pan:false,debounceMoveend:true});}},100);}
function attachMap21(){if(!map||attachedMap21===map)return;attachedMap21=map;if(typeof ResizeObserver==='function'){mapResizeObserver21=new ResizeObserver(resizeMap21);mapResizeObserver21.observe(document.getElementById('map'));}
 map.eachLayer(layer=>{if(!(layer instanceof L.TileLayer))return;layer.on('tileerror',event=>{const tile=event.tile;if(!tile||!tile.src)return;const tries=Number(tile.dataset.retry21||0);if(tries>=2)return;tile.dataset.retry21=String(tries+1);setTimeout(()=>{if(tile.isConnected&&activeView==='map'&&navigator.onLine)tile.src=tile.src;},(tries+1)*3000);});layer.on('load',()=>{if(document.querySelectorAll('#map img.leaflet-tile-loaded').length>0&&!document.querySelector('#map img.leaflet-tile:not(.leaflet-tile-loaded)'))document.getElementById('mapAccessNotice').classList.add('hide');});});resizeMap21();}
window.addEventListener('resize',resizeMap21);window.visualViewport?.addEventListener('resize',resizeMap21);window.addEventListener('online',()=>{if(map&&activeView==='map')map.eachLayer(l=>{if(l instanceof L.TileLayer)l.redraw();});if(roadState21.status==='error'){roadRetry21=0;roadState21.key='';render();}});
const mapSwitch21=switchView;switchView=function(view){if(view==='list'){status20.value='missing';reportSpecialStatus20='';}mapSwitch21(view);if(view==='map'){resizeMap21();setTimeout(resizeMap21,350);}render();};
status20.value='missing';
const compactMapStyle21=document.createElement('style');compactMapStyle21.textContent=`
.route-controls{grid-template-columns:auto auto auto auto!important;justify-content:start;gap:8px!important}.route-controls>button{min-width:0!important;width:auto!important;white-space:nowrap}.route-controls .depot-choice{white-space:nowrap;font-size:13px!important}.route-note#routeHint{font-size:17px!important;margin:0 0 6px!important;padding:3px 0!important;line-height:1.25!important;min-height:22px}.route-stop21{background:#2563eb!important}.mapframe{position:relative}.mapframe .maptools{position:absolute;z-index:500;right:8px;top:8px;display:flex;gap:5px;margin:0}.mapframe .maptools button{background:#ffffffed;min-height:34px;padding:5px 9px;font-size:12px}.mapframe .maptools select{display:none}.bottomnav .icon svg{display:block;margin:auto}#routeHint{cursor:default}#routeHint.road-failure21{cursor:pointer;color:#a43b2d!important}
@media(max-width:600px){body[data-mobile-view="map"] header{padding:7px 10px!important}body[data-mobile-view="map"] .brand img{width:34px;height:34px}body[data-mobile-view="map"] .shell{padding:6px 8px 80px!important}body[data-mobile-view="map"] .route-controls{display:grid!important;grid-template-columns:1fr 1.12fr 1.05fr .72fr!important;gap:4px!important;margin:0 0 4px!important;justify-content:stretch}body[data-mobile-view="map"] .route-controls>button{padding:5px 4px!important;min-height:36px!important;font-size:12px!important;width:100%!important;margin:0!important}body[data-mobile-view="map"] .depot-choice{grid-column:auto!important;font-size:12px!important;gap:4px;min-height:36px!important;justify-content:center;padding:0}body[data-mobile-view="map"] .depot-choice input{width:17px;height:17px}body[data-mobile-view="map"] #routeHint{font-size:15px!important;line-height:1.25!important;margin:0 0 5px!important;padding:2px 0!important;min-height:20px}body[data-mobile-view="map"] #map{height:calc(100dvh - 174px)!important;min-height:260px!important}body[data-mobile-view="map"] .mapframe{border-radius:14px}body[data-mobile-view="map"] .maplayout{gap:8px}body[data-mobile-view="map"] #mapAccessNotice{position:fixed;bottom:79px;left:12px;right:12px;z-index:600;padding:8px 10px!important;margin:0!important;box-shadow:0 3px 18px #17323a22;font-size:12px!important}body[data-mobile-view="map"] #mapAccessNotice button{font-size:11px;padding:3px 8px;min-height:28px}body[data-mobile-view="map"] .mapframe .maptools{width:auto}body[data-mobile-view="map"] .mapframe .maptools button{flex:none!important;min-height:32px;font-size:11px!important;padding:5px 8px}.bottomnav{padding:6px!important}.bottomnav button{min-height:56px}.bottomnav .icon{height:25px}}
`;document.head.append(compactMapStyle21);
const render21=render;render=function(){render21();attachMap21();scheduleRoad21();hint21.textContent=roadText21();hint21.title=roadState21.error||'道路服務估計，未含停留及即時交通';hint21.classList.toggle('road-failure21',roadState21.status==='error');paintRoad21();};
showMapAccessNotice=function(local){const box=document.getElementById('mapAccessNotice');box.classList.remove('hide');box.replaceChildren(document.createTextNode(local?'請開啟線上巡店地圖':'部分地圖未載入 '),makeAction('重載地圖',()=>{if(map){map.invalidateSize({pan:false});map.eachLayer(layer=>{if(layer instanceof L.TileLayer)layer.redraw();});}box.classList.add('hide');}));};
releaseButton.textContent='v1.21';releaseButton.setAttribute('aria-label','版本 v1.21，查看更新紀錄');const entry21=document.createElement('article');entry21.className='release-entry';entry21.innerHTML='<b>v1.21</b><time>2026-10-05</time><p>手機地圖擴大、單行控制列；圖磚尺寸校正與重試；統一店點顏色；預設缺訪清單；訪況與工作自檢圖示；實際道路路線與行車里程時間。</p>';releaseHistory.querySelector('h2').after(entry21);render();

