// Explicit rejoining refreshes owner policies, credentials and subscriptions together.
let rejoining27=false,switchingAccount27=false;
async function performRejoin27(){const uid=cloudUser?.uid;if(!uid||rejoining27||switchingAccount27)return;rejoining27=true;const button=document.getElementById('gateAction');button.disabled=true;document.getElementById('gateStatus').textContent='正在重新加入…';try{plannerResult(await supabasePlannerClient.rpc('planner_join'));if(cloudUser?.uid!==uid)return;const members=plannerResult(await supabasePlannerClient.from('planner_members').select('id,active').eq('id',uid));if(!members.some(x=>x.id===uid&&x.active===true))throw Error('帳號尚未重新啟用，請重試');location.reload();}catch(error){if(cloudUser?.uid===uid)document.getElementById('gateStatus').textContent='重新加入未完成：'+updateReason(error);}finally{rejoining27=false;refreshAccountGate();}}
rejoinPlanner=performRejoin27;
// Older gate timers may retain a direct onclick function reference. Route the
// revoked-account click here before those handlers, including Safari.
gate.addEventListener('click',event=>{if(event.target.closest?.('#gateAction')&&cloudUser&&membershipRevoked){event.preventDefault();event.stopImmediatePropagation();performRejoin27();}},true);
async function switchGoogleAccount27(){if(switchingAccount27)return;switchingAccount27=true;refreshAccountGate();try{if(visitSyncBusy)cancelVisitSync();abortAutoRoute();clearTimeout(autoSaveTimer);autoSaveBlocked=true;document.getElementById('ttlAccount').value='';document.getElementById('ttlPassword').value='';for(const id of ['credentialDrawer','updateIssue'])closeModal(id);companyWaitDepth=0;endCompanyWait();await initCloud();await authApi.signOut(cloudAuth);ttlBinding=null;ttlBindingUid=null;await authApi.signInWithPopup(cloudAuth,new authApi.GoogleAuthProvider());}catch(error){document.getElementById('gateStatus').textContent='切換帳號未完成：'+updateReason(error);}finally{switchingAccount27=false;refreshAccountGate();}}
const switchGate27=document.createElement('button');switchGate27.id='gateSwitchGoogle27';switchGate27.textContent='切換 Google 帳號';switchGate27.onclick=switchGoogleAccount27;gate.append(switchGate27);
const gateIdentity27=document.createElement('small');gateIdentity27.id='gateIdentity27';gate.insertBefore(gateIdentity27,document.getElementById('gateAction'));
const switchDrawer27=document.createElement('button');switchDrawer27.id='drawerSwitchGoogle27';switchDrawer27.type='button';switchDrawer27.textContent='切換 Google 帳號';switchDrawer27.onclick=switchGoogleAccount27;document.querySelector('#credentialDrawer .dialog').append(switchDrawer27);
const switchWait27=document.createElement('button');switchWait27.id='waitSwitchGoogle27';switchWait27.textContent='切換 Google 帳號';switchWait27.onclick=switchGoogleAccount27;companyWait.querySelector('.company-wait-card').append(switchWait27);
const gateRefresh27=refreshAccountGate;refreshAccountGate=function(){gateRefresh27();switchGate27.classList.toggle('hide',!cloudUser);switchDrawer27.classList.toggle('hide',!cloudUser);switchWait27.classList.toggle('hide',!cloudUser||plannerAccessReady());gateIdentity27.textContent=cloudUser?.email||'';for(const button of [switchGate27,switchDrawer27,switchWait27])button.disabled=switchingAccount27||rejoining27;if(switchingAccount27||rejoining27)document.getElementById('gateAction').disabled=true;};
const style27=document.createElement('style');style27.textContent='#gateIdentity27{color:var(--muted);margin:0 0 14px;overflow-wrap:anywhere}#gateSwitchGoogle27{margin-top:12px}#drawerSwitchGoogle27{display:block;width:100%;margin-top:18px}';document.head.append(style27);refreshAccountGate();
releaseButton.textContent='v1.27';releaseButton.setAttribute('aria-label','版本 v1.27，查看更新紀錄');const entry27=document.createElement('article');entry27.className='release-entry';entry27.innerHTML='<b>v1.27</b><time>2026-10-07</time><p>修正移除帳號重新加入後的資料載入；尚未完成業務王設定也能切換 Google 帳號。</p>';releaseHistory.querySelector('h2').after(entry27);
