// Administrator-only, read-only work checks. Reuse the exact personal self-check rules.
const allWorkCard24=document.createElement('article');allWorkCard24.className='card manager-work24';allWorkCard24.innerHTML='<div class="manager-work-head24"><h3>全員工作缺失</h3><button id="managerWorkRefresh24">重新整理</button></div><div id="managerWorkStatus24" role="status"></div><div id="managerWorkTotals24"></div><div id="managerWorkPeople24"></div>';
document.getElementById('managerVisitors').before(allWorkCard24);
let allWorkKey24='',allWorkGeneration24=0,allWorkStates24=new Map(),allWorkQueue24=[],allWorkRunning24=0;
function validWorkMeta24(meta){return meta&&meta.version===1&&Number.isInteger(meta.chunks)&&meta.chunks>=0&&meta.chunks<=200&&Number.isInteger(meta.count)&&meta.count>=0&&meta.count<=50000&&Array.isArray(meta.columns)&&/^[a-f0-9]{32}$/.test(meta.requestId);}
async function readManagerWork24(person,period,generation){const state=allWorkStates24.get(person.uid);if(!state)return;const current=()=>generation===allWorkGeneration24&&managerAllowed()&&allWorkStates24.get(person.uid)===state;
 try{const collection=name=>firebaseApi.collection(firestore,'route_map_test_users',person.uid,name),ref=firebaseApi.doc(collection('workSnapshots'),period),snap=await firebaseApi.getDoc(ref);if(!current())return;if(!snap.exists()){state.status='missing';return;}const meta=snap.data();if(!validWorkMeta24(meta))throw Error('工作報表格式不符');const items=[];
  for(let offset=0;offset<meta.chunks;offset+=8){const parts=await Promise.all(Array.from({length:Math.min(8,meta.chunks-offset)},(_,i)=>firebaseApi.getDoc(firebaseApi.doc(collection('workRecords'),period+'_'+meta.requestId+'_'+(offset+i)))));if(!current())return;for(const part of parts){if(!part.exists()||!Array.isArray(part.data().items))throw Error('工作資料尚未載入完整');items.push(...part.data().items);}}
  if(items.length!==meta.count)throw Error('工作資料筆數不符');const ids=new Set();for(const item of items){if(!item||typeof item.id!=='string'||ids.has(item.id)||['code','name','owner','checkInAt','completedAt'].some(key=>typeof item[key]!=='string'))throw Error('工作紀錄格式不符');ids.add(item.id);}const latest=await firebaseApi.getDoc(ref);if(!current())return;if(!latest.exists()||latest.data().requestId!==meta.requestId)throw Error('工作資料更新中，請重新整理');state.meta=meta;state.source=items;state.status='ready';
 }catch(e){if(current()){state.status='error';state.error=e.message||'讀取失敗';}}
 finally{if(current())drawManagerWork24();}
}
function pumpManagerWork24(){while(allWorkRunning24<3&&allWorkQueue24.length){const job=allWorkQueue24.shift();if(job.generation!==allWorkGeneration24)continue;allWorkRunning24++;readManagerWork24(job.person,job.period,job.generation).finally(()=>{allWorkRunning24--;pumpManagerWork24();});}}
function connectManagerWork24(force=false){if(!managerAllowed()){if(allWorkKey24){allWorkGeneration24++;allWorkKey24='';allWorkStates24.clear();allWorkQueue24=[];document.getElementById('managerWorkPeople24').replaceChildren();document.getElementById('managerWorkTotals24').replaceChildren();}return;}const people=[...managerPeople.values()],key=cloudUser.uid+':'+managerPeriod+':'+people.map(p=>p.uid).sort().join('|');if(!force&&key===allWorkKey24){drawManagerWork24();return;}allWorkKey24=key;allWorkGeneration24++;allWorkStates24=new Map(people.map(person=>[person.uid,{person,status:'loading',source:[],meta:null}]));allWorkQueue24=people.map(person=>({person,period:managerPeriod,generation:allWorkGeneration24}));drawManagerWork24();pumpManagerWork24();}
function workDetail24(row){const detail=document.createElement('details');detail.className='manager-work-record24';const summary=document.createElement('summary');summary.textContent=(row.name||row.code||'未指定店家')+' · '+(row.day||'日期未提供')+' · '+row.flags.filter(id=>WORK_CHECK_TYPES.some(t=>t.id===id)).map(id=>WORK_CHECK_TYPES.find(t=>t.id===id).name).join('、');detail.append(summary);for(const text of ['店家代碼 '+(row.code||'—'),'到點 '+(row.checkInAt||'—')+' · 離點 '+(row.completedAt||'—'),'停留 '+formatWorkSeconds(row.seconds),'備註 '+(row.note||'未填')]){const p=document.createElement('p');p.textContent=text;detail.append(p);}if(row.previous){const p=document.createElement('p');p.textContent='上一點 '+row.previous.name+' · 離點 '+(row.previous.endAt||'—');detail.append(p);}if(row.flags.includes('signal')){const p=document.createElement('p');p.textContent='衛星訊號欄：'+(row.signalValue||'（空白）');detail.append(p);}return detail;}
function drawManagerWork24(){if(!managerAllowed())return;const root=document.getElementById('managerWorkPeople24');root.replaceChildren();const states=[...allWorkStates24.values()].filter(s=>managerPeople.has(s.person.uid)&&(!managerUid||s.person.uid===managerUid)),ready=states.filter(s=>s.status==='ready'),analyses=new Map(ready.map(s=>{const personState=managerStates.get(s.person.uid),owner=personState?.master?.preferredOwner||personState?.route?.owner||'';if(s.analysisOwner!==owner||!s.analysis){s.analysisOwner=owner;s.analysis=analyzeWorkRecords(s.source,{period:managerPeriod,owner,columns:s.meta.columns});}return [s.person.uid,s.analysis];}));
 document.getElementById('managerWorkStatus24').textContent=managerPeriod+' · '+ready.length+'/'+states.length+' 個帳戶已載入';const totals=document.getElementById('managerWorkTotals24');totals.replaceChildren();const flagged=[...analyses.values()].reduce((n,a)=>n+a.stats.flagged,0);const total=document.createElement('b');total.textContent=ready.length?'缺失工作 '+flagged+' 筆'+(ready.length<states.length?'（已載入帳戶）':''):'缺失工作：待取得資料';totals.append(total);for(const type of WORK_CHECK_TYPES){const count=[...analyses.values()].reduce((n,a)=>n+(a.categories.find(x=>x.id===type.id)?.count||0),0),tag=document.createElement('span');tag.textContent=type.name+' '+(ready.length?count:'—');totals.append(tag);}
 for(const state of states){const personState=managerStates.get(state.person.uid),label=personState?.master?.preferredOwner||state.person.name||state.person.email,card=document.createElement('details');card.className='manager-work-person24';card.open=state.open===true;card.addEventListener('toggle',()=>{state.open=card.open;});const summary=document.createElement('summary'),title=document.createElement('b'),metric=document.createElement('span');title.textContent=label;const analysis=analyses.get(state.person.uid);metric.textContent=state.status==='ready'?(analysis.stats.flagged+' 筆缺失'):(state.status==='missing'?'本月未同步工作':state.status==='error'?'讀取失敗':'載入中…');summary.append(title,metric);card.append(summary);const account=document.createElement('small');account.textContent=state.person.email;card.append(account);
  if(!analysis){const text=document.createElement('p');text.textContent=state.error||'更新工作紀錄後即可分析。';card.append(text);root.append(card);continue;}const time=document.createElement('p');time.className='notice';time.textContent='資料更新 '+displayAccessTime(state.meta.updatedAt)+' · '+analysis.stats.total+' 筆工作';card.append(time);const chips=document.createElement('div');chips.className='manager-work-types24';const records=document.createElement('div');let filter=state.filter||'all',shown=50;const draw=()=>{records.replaceChildren();const flaggedRows=analysis.rows.filter(r=>r.flags.some(id=>WORK_CHECK_TYPES.some(t=>t.id===id))&&(filter==='all'||r.flags.includes(filter))).sort((a,b)=>(b.start||0)-(a.start||0));flaggedRows.slice(0,shown).forEach(row=>records.append(workDetail24(row)));if(flaggedRows.length>shown)records.append(makeAction('顯示更多',()=>{shown+=50;draw();}));if(!flaggedRows.length){const p=document.createElement('p');p.textContent='未發現此類缺失';records.append(p);}chips.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.type===filter));};
  for(const category of [{id:'all',name:'全部缺失',count:analysis.stats.flagged},...analysis.categories]){const button=makeAction(category.name+' '+category.count,()=>{filter=category.id;state.filter=filter;shown=50;draw();});button.dataset.type=category.id;if(category.id!=='all'&&category.limit!==null&&category.count>category.limit)button.classList.add('over-limit');chips.append(button);}const unknown=analysis.categories.find(c=>c.id==='signal')?.unknown;if(unknown){const p=document.createElement('p');p.className='notice';p.textContent=unknown+' 筆缺少衛星訊號原欄位，未納入該項判定';card.append(p);}card.append(chips,records);let initialized=false;card.addEventListener('toggle',()=>{if(card.open&&!initialized){initialized=true;draw();}});if(card.open){initialized=true;draw();}root.append(card);
 }if(!states.length)root.textContent='尚無使用者資料';
}
document.getElementById('managerWorkRefresh24').onclick=()=>connectManagerWork24(true);
const managerWorkRender24=renderManagerOverview;renderManagerOverview=function(){managerWorkRender24();connectManagerWork24();};
const managerWorkSwitch24=switchView;switchView=function(view){managerWorkSwitch24(view);if(view!=='admin')connectManagerWork24();};
const managerWorkStyle24=document.createElement('style');managerWorkStyle24.textContent='.manager-work24{margin:16px 0}.manager-work-head24{display:flex;justify-content:space-between;align-items:center;gap:8px}.manager-work-head24 button{min-height:34px;padding:6px 12px;font-size:12px}#managerWorkStatus24{font-size:12px;color:var(--muted);margin-bottom:12px}#managerWorkTotals24,.manager-work-types24{display:flex;flex-wrap:wrap;gap:7px;margin:12px 0}#managerWorkTotals24>span{font-size:12px;background:#eef5f2;border-radius:8px;padding:6px 9px}#managerWorkTotals24>b{width:100%;font-size:18px}.manager-work-person24{border:1px solid var(--line);border-radius:12px;padding:12px;margin:8px 0}.manager-work-person24>summary{display:flex;justify-content:space-between;gap:12px;cursor:pointer;font-size:14px}.manager-work-person24>small{display:block;font-size:11px;color:var(--muted);margin-top:5px;overflow-wrap:anywhere}.manager-work-types24 button{font-size:12px;min-height:34px;padding:6px 9px}.manager-work-types24 .active{background:var(--green);color:white}.manager-work-types24 .over-limit{border-color:var(--red)}.manager-work-record24{padding:10px;background:#f8faf9;border-radius:8px;border:1px solid var(--line);margin:6px 0;font-size:13px}.manager-work-record24 summary{cursor:pointer;line-height:1.6}.manager-work-record24 p{font-size:12px;line-height:1.6;margin:6px 0;overflow-wrap:anywhere}';document.head.append(managerWorkStyle24);
releaseButton.textContent='v1.24';releaseButton.setAttribute('aria-label','版本 v1.24，查看更新紀錄');const entry24=document.createElement('article');entry24.className='release-entry';entry24.innerHTML='<b>v1.24</b><time>2026-10-05</time><p>管理總覽新增全員工作缺失，依月份、訪員與異常類型查看明細；未同步及讀取失敗明確標示。</p>';releaseHistory.querySelector('h2').after(entry24);
