// Persistent routes and a focused visit list on the same page.
const status20=document.getElementById('visitStatus');
status20.innerHTML='<option value="missing">尚缺訪次</option><option value="required">應訪店家</option><option value="all">全部店家</option>';status20.value='all';
const sort20=document.getElementById('storeSort');sort20.classList.add('hide');
const channel20=document.createElement('select');channel20.id='customerChannel';channel20.setAttribute('aria-label','通路別篩選');sort20.after(channel20);
let reportSpecialStatus20='';
status20.onchange=()=>{reportSpecialStatus20='';render();};
channel20.onchange=()=>{channelFocus=channel20.value;groups.clear();render();};
visibleRecords=function(){const term=document.getElementById('search').value.trim().toLowerCase(),state=reportSpecialStatus20||status20.value;return scopeRecords().filter(x=>(!term||[x.name,x.code,x.channel,x.type,x.owner].join(' ').toLowerCase().includes(term))&&(!channelFocus||(x.channel||x.group)===channelFocus)&&(state==='all'||state==='missing'&&visitGap(x)>0||state==='required'&&visitRequirementState(x)==='required'||state==='met'&&visitRequirementState(x)==='required'&&visitCount(x)>=x.req||state==='unset'&&visitRequirementState(x)==='unset')).sort((a,b)=>visitGap(b)-visitGap(a)||a.name.localeCompare(b.name,'zh-Hant'));};
const reportList20=document.createElement('section');reportList20.id='reportCustomerList';
for(const el of [customerHeader,fullSearch,listTools,fullTableHead,document.getElementById('storeList')])reportList20.append(el);
listPanel.append(reportList20);
showVisitRequirement=function(state){channelFocus='';groups.clear();document.getElementById('search').value='';reportSpecialStatus20=['met','unset'].includes(state)?state:'';status20.value=reportSpecialStatus20?'all':state;render();reportList20.scrollIntoView({block:'start',behavior:'smooth'});};
const report20=renderReport;renderReport=function(){report20();document.querySelectorAll('#channelReport tbody tr').forEach(tr=>{const b=tr.querySelector('button');if(!b)return;const name=b.textContent;b.onclick=()=>{channelFocus=name==='全通路'?'':name;groups.clear();reportSpecialStatus20='';status20.value='all';render();reportList20.scrollIntoView({block:'start',behavior:'smooth'});};});};
const search20=document.getElementById('search');search20.oninput=()=>render();
resetFilters=function(){channelFocus='';groups.clear();missingOnly=false;reportSpecialStatus20='';status20.value='all';search20.value='';render();};
const work20=renderWorkPanel;renderWorkPanel=function(){work20();document.querySelectorAll('#workDashboard .work-stats .stat').forEach(el=>{if(/^(總工作|完成工作|服務點|待核對工作)/.test(el.querySelector('label')?.textContent||''))el.remove();});};
const routeControls20=document.querySelector('.route-controls'),pick20=[...routeControls20.querySelectorAll('button')].find(b=>b.getAttribute('onclick')?.includes("switchView('list')"));
pick20.textContent='選店安排';pick20.classList.add('primary');
const options20=document.createElement('div');options20.className='route-toggles20';options20.append(document.querySelector('.suggestBtn'),depotChoice);
routeControls20.replaceChildren(pick20,clearRouteButton,options20);
const originalAutoButton20=updateAutoRouteButton;updateAutoRouteButton=function(){originalAutoButton20();const b=document.querySelector('.suggestBtn');b.textContent='自動安排';b.setAttribute('aria-label','自動安排');};
const routeStyle20=document.createElement('style');routeStyle20.textContent=`
.route-controls{display:grid!important;grid-template-columns:1fr auto;gap:10px!important;align-items:center;margin-bottom:12px}.route-controls>button{font-size:15px!important;min-height:44px!important}.route-controls>button:first-child{justify-self:start;min-width:150px}.route-controls #clearAllRoute{font-weight:500;color:#667b7b;background:transparent;border-color:#d3dfdf}.route-toggles20{grid-column:1/-1;display:flex;gap:12px;align-items:center;padding:10px 12px;background:#e8f1ef;border-radius:10px}.route-toggles20 .suggestBtn{font-size:14px!important;min-height:38px!important;margin:0!important;padding:7px 12px!important}.route-toggles20 .depot-choice{margin:0;min-height:38px;font-size:14px!important;grid-column:auto!important}.route-note#routeHint{font-size:clamp(16px,2.1vw,20px)!important;font-weight:600;padding:10px 0;white-space:normal;line-height:1.45}.work-stats{grid-template-columns:repeat(2,minmax(0,1fr))!important}.table-controls{flex-direction:row!important}.table-controls select{width:50%!important}.table-controls #storeSort{display:none!important}#customerChannel{display:block!important}.report-list-note{font-size:12px;color:var(--muted)}
@media(max-width:600px){body[data-mobile-view="report"] #reportCustomerList{display:block!important}body[data-mobile-view="report"] #reportCustomerList .customer-table-header{display:flex!important}body[data-mobile-view="report"] #reportCustomerList .customer-search{display:block!important}body[data-mobile-view="report"] #reportCustomerList .store-table-head{display:grid!important}body[data-mobile-view="report"] #reportCustomerList #storeList{display:grid!important}body[data-mobile-view="report"] #reportCustomerList .listtools{display:none!important}.route-controls>button:first-child{min-width:0;width:100%;justify-self:stretch}.route-toggles20{justify-content:space-between;gap:6px}.route-note#routeHint{font-size:17px!important}.table-controls select{min-height:38px!important;font-size:12px!important}}
`;document.head.append(routeStyle20);
function routeEstimate20(){const rows=selectedRecords(),points=rows.filter(x=>validGps(x.gps)).map(x=>x.gps.map(Number));if(!points.length)return '';if(autoDepotStart)points.unshift(DEPOT.gps.map(Number));points.push(DEPOT.gps.map(Number));const km=points.reduce((sum,p,i)=>sum+(i?distanceKm(points[i-1],p):0),0);return '直線估算 '+km.toFixed(1)+' 公里 · 約 '+Math.ceil(km/30*60)+' 分鐘';}
const render20=render;render=function(){render20();const channels=[...new Set(scopeRecords().map(x=>x.channel||x.group||'未分類'))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));channel20.innerHTML='<option value="">全部通路</option>'+channels.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('');channel20.value=channelFocus;document.getElementById('routeHint').textContent=routeEstimate20();document.getElementById('routeHint').title='以點對點直線距離及平均時速 30 公里估算；不含停留、道路繞行及即時交通';customerHeader.querySelector('h3').textContent=reportSpecialStatus20==='unset'?'待設訪頻清單':status20.value==='missing'?'缺訪清單':status20.value==='required'?'應訪清單':'客戶清單';};
releaseButton.textContent='v1.20';releaseButton.setAttribute('aria-label','版本 v1.20，查看更新紀錄');const entry20=document.createElement('article');entry20.className='release-entry';entry20.innerHTML='<b>v1.20</b><time>2026-10-05</time><p>行程持續保留至手動清空；訪況直接查看清單；通路篩選、路線控制列與路程估算；精簡工作自檢統計。</p>';releaseHistory.querySelector('h2').after(entry20);render();
document.getElementById('managerDate').closest('label').classList.add('hide');
