// Unified visit overview and scheduling; account-scoped frequency settings.
let channelFocus='',frequencyDraft=[];
const V4_DEFAULTS=Object.entries(DEFAULT_RULES.monthly).map(([grade,count])=>({channel:'*',grade,period:'month',count})).filter((r,i,all)=>all.findIndex(z=>ruleGrade(z.grade)===ruleGrade(r.grade))===i);
function migrateFrequency(){if(ruleConfig.version!==4){let entries=structuredClone(V4_DEFAULTS),known=new Set(entries.map(r=>ruleGrade(r.grade)));for(let grade of ruleConfig.quarterly||[]){let g=ruleGrade(grade);if(!known.has(g)){entries.push({channel:'*',grade:g,period:'quarter',count:1});known.add(g);}}for(let [grade,count] of Object.entries(ruleConfig.monthly||{})){let g=ruleGrade(grade);if(!known.has(g)){entries.push({channel:'*',grade:g,period:'month',count:Number(count)||0});known.add(g);}}ruleConfig={version:4,entries,monthly:{...DEFAULT_RULES.monthly},quarterly:[],fnbOnlyA:false};}}
function frequencyFor(x){migrateFrequency();let grade=ruleGrade(x.grade),channel=x.channel||x.group||(isFnb(x)?'即飲通路':/^連鎖超市/.test(grade)?'連鎖超市':/^量販/.test(grade)?'量販通路':'傳統通路');return ruleConfig.entries.find(r=>r.channel===channel&&ruleGrade(r.grade)===grade)||ruleConfig.entries.find(r=>r.channel==='*'&&ruleGrade(r.grade)===grade)||null;}
isQuarterly=x=>frequencyFor(x)?.period==='quarter';
required=x=>Number(frequencyFor(x)?.count||0);
const v4Records=records;records=function(){return v4Records().map(x=>({...x,frequencyMissing:!frequencyFor(x),met:visitCount(x)>=x.req}));};
const v4StoreCard=storeCard;storeCard=function(x){let row=v4StoreCard(x);if(x.frequencyMissing){let numbers=row.querySelector('.visitnumbers');numbers.textContent='未設定訪頻';numbers.classList.add('notice');numbers.style.display='block';row.querySelector('.storechannel').title='請在訪頻規則中設定這個等級';}return row;};
const v4Visible=visibleRecords;visibleRecords=function(){return v4Visible().filter(x=>!channelFocus||(x.channel||x.group)===channelFocus);};
const v4Reset=resetFilters;resetFilters=function(){let owner=document.getElementById('ownerFilter').value;channelFocus='';v4Reset();document.getElementById('ownerFilter').value=owner;render();};
const v4Switch=switchView;
switchView=function(view){let mobile=matchMedia('(max-width:600px)').matches;v4Switch(view==='report'?'list':view);activeView=mobile&&view==='report'?'report':(view==='report'?'list':view);document.body.dataset.mobileView=activeView;document.querySelector('#panel-list > .intro h2').textContent=mobile?(activeView==='report'?'訪況':'選店排程'):'訪況與選店';document.querySelectorAll('.bottomnav [data-view]').forEach(e=>{let active=e.dataset.view===activeView;e.classList.toggle('active',active);e.setAttribute('aria-current',active?'page':'false');});if(view==='map'){document.getElementById('mapScope').value='selected';updateMap(true);requestAnimationFrame(()=>{map?.invalidateSize();fitMap();});}};

const overview=document.getElementById('panel-report');overview.className='visit-overview';document.getElementById('panel-list').querySelector('.intro').after(overview);
overview.innerHTML='<div class="report-controls"><label>年度<select id="reportYear" onchange="changeReportYear(this.value)"><option value="2026">2026 年</option><option value="2027">2027 年</option></select></label><label>月份<select id="reportMonth" onchange="selectMonth(Number(this.value))"></select></label><button onclick="openRules()">調整訪頻規則</button></div><div class="overview-grid"><article class="card"><h3>全通路缺訪總覽</h3><div id="visitChart"></div><p id="calendarNote" class="notice"></p><p class="notice">剩餘工作日 <b id="reportDays"></b> 天 · 週末、國定假日與補假休息</p></article><article class="card priority-card"><h3>缺訪最多店家</h3><div id="priorityStore"></div></article></div><h3 class="channel-title">依通路查看與選店</h3><div id="channelReport" class="channel-buttons"></div><span id="reportGap" hidden></span><span id="reportPace" hidden></span>';
document.getElementById('reportMonth').innerHTML=document.getElementById('monthSelect').innerHTML;
document.getElementById('reportMonth').value=month;document.getElementById('reportYear').value=reportYear;
document.getElementById('missingBtn').classList.add('hide');document.getElementById('workdays').parentElement.classList.add('hide');
document.getElementById('panel-list').querySelector('.stats').classList.add('hide');document.getElementById('groups').classList.add('hide');document.getElementById('listPlanSummary').classList.add('hide');document.getElementById('monthSelect').closest('label').classList.add('hide');document.getElementById('visitStatus').value='missing';
document.querySelectorAll('.bottomnav button[data-view="report"]').forEach(e=>e.innerHTML='<span class="icon">▥</span><span>訪況</span>');
document.querySelectorAll('.tabs [data-view="list"]').forEach(e=>e.textContent='訪況與選店');document.querySelectorAll('.bottomnav [data-view="list"]').forEach(e=>e.innerHTML='<span class="icon">☷</span><span>選店排程</span>');
renderReport=function(){let rows=scopeRecords(),short=rows.filter(x=>visitGap(x)>0),unknown=rows.filter(x=>x.frequencyMissing).length,met=rows.length-short.length-unknown,percent=rows.length?Math.round(met/rows.length*100):0,days=work();document.getElementById('workdays').textContent=days??'待更新';document.getElementById('reportDays').textContent=days??'待更新';document.getElementById('reportGap').textContent=rows.reduce((n,x)=>n+visitGap(x),0);document.getElementById('calendarNote').textContent=holidaysByYear[reportYear]?'依分析月份與目前轄區計算；每季規則合計該季實訪。':'此年度尚未載入國定假日日曆。';document.getElementById('visitChart').innerHTML='<div class="chart-content"><div class="visit-donut" role="img" aria-label="全通路 '+short.length+' 間缺訪、'+met+' 間達標" style="--progress:'+percent+'%;--covered:'+(rows.length?Math.round((rows.length-unknown)/rows.length*100):0)+'%"><div><b>'+short.length+'</b><span>間缺訪</span></div></div><div class="chart-legend"><p><i class="dot red-dot"></i>未達標 <b>'+short.length+'</b> 間</p><p><i class="dot green-dot"></i>已達標 <b>'+met+'</b> 間</p><p>待設訪頻 <b>'+unknown+'</b> 間</p><p>目前轄區 <b>'+rows.length+'</b> 間</p><p class="notice">達標率 '+percent+'%</p></div></div>';
let max=Math.max(0,...short.map(visitGap)),top=short.filter(x=>visitGap(x)===max).sort((a,b)=>a.name.localeCompare(b.name,'zh-Hant')),box=document.getElementById('priorityStore');box.replaceChildren();if(top.length){let x=top[0],info=document.createElement('div');info.innerHTML='<h2>'+esc(x.name)+'</h2><p class="notice">'+esc(x.channel||x.group)+' · '+esc(x.grade)+' · '+esc(x.code)+'</p><p class="priority-number">'+max+' <small>次未完成</small></p><p class="notice">'+(isQuarterly(x)?'本季':'本月')+'應訪 '+x.req+' 次，已訪 '+visitCount(x)+' 次'+(top.length>1?'；另有 '+(top.length-1)+' 間並列':'')+'</p>';box.append(info,makeAction(chosen.has(x.code)?'已加入行程':'＋ 加入今日行程',()=>choose(x.code,!chosen.has(x.code))),makeAction('查看缺訪清單',()=>{channelFocus='';document.getElementById('search').value='';document.getElementById('visitStatus').value='missing';document.getElementById('storeSort').value='gap';groups.clear();render();document.getElementById('storeList').scrollIntoView({behavior:'smooth'});}));}else box.innerHTML='<h2>'+(rows.length?(unknown?'目前無缺訪；仍有待設規則店家':'全部店家已達標'):'尚無客戶資料')+'</h2><p class="notice">'+(rows.length?(unknown?'請調整訪頻規則，才能判定尚未設定的店家。':'可直接選店安排下一趟行程。'):'先到資料頁更新公司資料。')+'</p>';
let channels=document.getElementById('channelReport');channels.replaceChildren();function button(name,count,total,focus){let b=makeAction(name,()=>{channelFocus=focus;groups.clear();document.getElementById('search').value='';render();});b.innerHTML='<b>'+esc(name)+'</b><span>'+count+' 間缺訪 / '+total+' 間店</span>';b.classList.toggle('active',channelFocus===focus);b.setAttribute('aria-pressed',String(channelFocus===focus));channels.append(b);}button('全通路',short.length,rows.length,'');for(let c of reportStats(rows))button(c.name,c.short,c.stores,c.name);};
const rulesModal=document.getElementById('rulesModal');rulesModal.innerHTML='<div class="dialog frequency-dialog"><h2>訪頻規則</h2><p class="notice">先套用公司每月規則；可針對特定通路新增規則。特定通路優先於「全通路」，0 次表示免訪。A／B 與 A級／B級視為同級；未設定等級不列入應訪。</p><div id="frequencyRows"></div><button onclick="addFrequencyRule()">＋ 新增通路／等級規則</button><footer><button onclick="closeModal(\'rulesModal\')">取消</button><button class="primary" onclick="saveRules()">儲存並套用</button></footer></div>';
openRules=function(){migrateFrequency();frequencyDraft=structuredClone(ruleConfig.entries);drawFrequencyRules();openModal('rulesModal');};
function addFrequencyRule(){frequencyDraft.push({channel:'*',grade:'',period:'month',count:1});drawFrequencyRules();}
function drawFrequencyRules(){let channels=[...new Set(records().map(x=>x.channel||x.group))],box=document.getElementById('frequencyRows');box.replaceChildren();frequencyDraft.forEach((r,i)=>{let row=document.createElement('div');row.className='frequency-row';row.innerHTML='<label>通路<select aria-label="規則 '+(i+1)+' 通路"><option value="*">全通路</option>'+[...new Set([...channels,r.channel])].filter(c=>c&&c!=='*').map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('')+'</select></label><label>等級<input aria-label="規則 '+(i+1)+' 等級" value="'+esc(r.grade)+'" placeholder="例如 五大A"></label><label>週期<select aria-label="規則 '+(i+1)+' 週期"><option value="month">每月</option><option value="quarter">每季</option></select></label><div class="counter"><button aria-label="減少規則 '+(i+1)+' 次數">−</button><output>'+r.count+'</output><button aria-label="增加規則 '+(i+1)+' 次數">＋</button></div><button class="rule-remove" aria-label="刪除規則 '+(i+1)+'">移除</button>';let sels=row.querySelectorAll('select');sels[0].value=r.channel;sels[0].onchange=e=>r.channel=e.target.value;sels[1].value=r.period;sels[1].onchange=e=>r.period=e.target.value;row.querySelector('input').oninput=e=>r.grade=e.target.value.trim();let buttons=row.querySelectorAll('button');buttons[0].onclick=()=>{r.count=Math.max(0,r.count-1);drawFrequencyRules();};buttons[1].onclick=()=>{r.count=Math.min(99,r.count+1);drawFrequencyRules();};buttons[2].onclick=()=>{frequencyDraft.splice(i,1);drawFrequencyRules();};box.append(row);});}
saveRules=function(){let keys=new Set();for(let r of frequencyDraft){let key=r.channel+'|'+ruleGrade(r.grade);if(!r.grade||keys.has(key))return toast('請填寫等級；同通路、同等級只能有一條規則。');keys.add(key);}ruleConfig={version:4,entries:structuredClone(frequencyDraft),monthly:{},quarterly:[],fnbOnlyA:false};dirty();closeModal('rulesModal');render();toast('訪頻規則已套用，正在自動儲存');};
const v4Style=document.createElement('style');v4Style.textContent='.overview-grid{display:grid;grid-template-columns:1.15fr 1fr;gap:16px;margin:18px 0}.chart-content{display:flex;align-items:center;gap:26px}.visit-donut{width:170px;height:170px;flex:none;border-radius:50%;background:conic-gradient(var(--green) 0 var(--progress),var(--red) var(--progress) var(--covered),#dce5ea var(--covered) 100%);display:grid;place-items:center}.visit-donut>div{background:white;width:130px;height:130px;border-radius:50%;display:flex;flex-direction:column;align-items:center;justify-content:center}.visit-donut b{font-size:38px}.visit-donut span{color:var(--muted)}.dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:8px}.red-dot{background:var(--red)}.green-dot{background:var(--green)}.priority-card{background:#fffaf5}.priority-card h2{font-size:23px;overflow-wrap:anywhere}.priority-number{font-size:40px;font-weight:800;color:var(--red);margin:12px 0}.priority-number small{font-size:16px}.priority-card button{margin:4px 6px 0 0}.channel-buttons{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}.channel-buttons button{flex-direction:column;align-items:flex-start;min-width:150px;padding:12px 18px}.channel-buttons span{font-size:12px;font-weight:400}.channel-buttons .active{background:var(--ink);color:white;border-color:var(--ink)}.channel-title{margin-top:24px}.frequency-dialog{width:min(960px,100%)}.frequency-row{display:grid;grid-template-columns:1.2fr 1fr 100px 150px 65px;gap:10px;align-items:end;padding:12px 0;border-bottom:1px solid var(--line)}.frequency-row label{font-size:12px;color:var(--muted)}.frequency-row input,.frequency-row select{margin-top:5px}.counter{display:flex;align-items:center;justify-content:space-between;gap:5px}.counter button{width:44px;padding:8px}.counter output{font-size:22px;font-weight:800}.frequency-dialog footer{position:sticky;bottom:-22px;background:white;padding:16px 0;margin-top:12px}.bottomnav{grid-template-columns:repeat(3,1fr)}@media(max-width:600px){.overview-grid{grid-template-columns:1fr}.chart-content{gap:14px;font-size:14px}.visit-donut{width:120px;height:120px}.visit-donut>div{width:92px;height:92px}.visit-donut b{font-size:32px}.channel-buttons{display:grid;grid-template-columns:1fr 1fr}.channel-buttons button{min-width:0;width:100%;padding:12px}.frequency-row{grid-template-columns:1fr 1fr;gap:8px}.frequency-row label:nth-child(3){grid-column:1}.rule-remove{grid-column:1/-1}.bottomnav button{font-size:12px}.report-controls{grid-template-columns:1fr 1fr}.report-controls button{grid-column:1/-1}.visit-overview .card{padding:16px}}';document.head.append(v4Style);
migrateFrequency();render();switchView(activeView);

const TTL_CREDENTIAL_KEY="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6fq/bCee5CMJEI2gCxqngkelsJBe8f3Lh5Cd0mq1Kn+4V8RVqMED342e0v9M81Zd/L2hTu7Kv3+TeJpcqqo+lQ30tEAqb37vJW/EJV+1qAsjw+9cqjTlm5RcBFGM350OJRRehFZxm3MaLCBwPJ0ZFaIK6xsRNGFKwAdqWK2b40PYCtzHmP8RgwYU+0VWOM79ifZwng8EQCqG/jS23udlBBPm0rotIfb6vZ1mBnt5W7x3S7gO/4wxVeXwpewxSeX+LraHmE+qL9jS5f1SBqtVhbWcJQ8xUs22CIczRdDNkYJejiUGWB1McG2xv+wpEWTEfEjXSAATCuBOSsemmJehfQIDAQAB";

let ttlBindingUid=null,ttlBinding=null;
const ttlCard=document.createElement('article');ttlCard.className='card';ttlCard.style.marginBottom='16px';ttlCard.innerHTML='<h3>我的業務王帳號</h3><p class="notice">綁定目前 Google 帳號，只讀取你自己的公司客戶與訪況。帳密加密保存至你的 Supabase 資料區；更新時交由 GitHub 工作解密登入，不會回顯密碼。系統管理者與可修改更新工作的協作者能使用解密私鑰，請只綁定你授權本系統使用的帳號。</p><p id="ttlBindingStatus" class="notice" role="status">登入 Google 後設定。</p><form id="ttlBindingForm" autocomplete="off"><div class="formgrid"><label>業務王帳號<input id="ttlAccount" type="text" autocomplete="off" maxlength="180" placeholder="你的公司登入帳號"></label><label>業務王密碼<input id="ttlPassword" type="password" autocomplete="new-password" maxlength="180" placeholder="輸入密碼"></label></div><button type="submit" class="primary">加密儲存帳號</button><button type="button" onclick="unlinkTtlAccount()">解除綁定</button></form>';
document.getElementById('panel-data').querySelector('.intro').after(ttlCard);
async function loadTtlBinding(){let user=cloudUser;if(!user){ttlBinding=null;ttlBindingUid=null;document.getElementById('ttlBindingStatus').textContent='登入 Google 後設定。';document.getElementById('ttlAccount').value='';document.getElementById('ttlPassword').value='';return;}try{let snap=await firebaseApi.getDoc(firebaseApi.doc(cloudCollection('settings'),'ttlCredential'));if(cloudUser?.uid!==user.uid)return;ttlBinding=snap.exists()&&snap.data().envelope?snap.data():null;ttlBindingUid=user.uid;document.getElementById('ttlBindingStatus').textContent=ttlBinding?'已綁定個人業務王帳號；可按一鍵更新驗證登入。':'尚未綁定；請輸入你自己的業務王帳號與密碼。';}catch{ttlBinding=null;document.getElementById('ttlBindingStatus').textContent='無法讀取綁定設定，請檢查網路後重試。';}}
async function personalCredential(){if(!cloudUser)throw Error('請先 Google 登入');if(ttlBindingUid!==cloudUser.uid)await loadTtlBinding();if(!ttlBinding?.envelope)throw Error('請到資料頁先綁定自己的業務王帳號。');return ttlBinding.envelope;}
document.getElementById('ttlBindingForm').onsubmit=async e=>{e.preventDefault();if(!cloudUser)return toast('請先 Google 登入');if(visitSyncBusy)return toast('更新中，請稍後再變更帳號');let user=cloudUser,account=document.getElementById('ttlAccount').value.trim(),password=document.getElementById('ttlPassword').value;if(!account||!password||/[\r\n]/.test(account+password))return toast('請填寫有效的帳號與密碼');let button=e.target.querySelector('[type="submit"]');button.disabled=true;try{let key=await crypto.subtle.importKey('spki',syncBytes(TTL_CREDENTIAL_KEY),{name:'RSA-OAEP',hash:'SHA-256'},false,['encrypt']),aes=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),aad=new TextEncoder().encode('ttl-credential:'+user.uid),plain=new TextEncoder().encode(JSON.stringify({version:1,uid:user.uid,account,password})),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},aes,plain),wrapped=await crypto.subtle.encrypt({name:'RSA-OAEP'},key,await crypto.subtle.exportKey('raw',aes));plain.fill(0);password='';if(cloudUser?.uid!==user.uid)throw Error('登入帳號已變更，請重新設定');let envelope=JSON.stringify({version:1,iv:syncBase64(iv),wrappedKey:syncBase64(wrapped),ciphertext:syncBase64(cipher)}),data={version:1,envelope,updatedAt:firebaseApi.serverTimestamp()};let batch=firebaseApi.writeBatch(firestore);batch.set(firebaseApi.doc(cloudCollection('settings'),'ttlCredential'),data);await batch.commit();ttlBinding=data;ttlBindingUid=user.uid;document.getElementById('ttlAccount').value='';document.getElementById('ttlPassword').value='';document.getElementById('ttlBindingStatus').textContent='已加密儲存；請按客戶＋訪況一起更新驗證登入。';toast('個人帳號已綁定');}catch(e){toast(e.message||'綁定失敗，請重試');}finally{document.getElementById('ttlPassword').value='';button.disabled=false;}};
async function unlinkTtlAccount(){if(visitSyncBusy)return toast('更新中，請稍後再解除綁定');if(!cloudUser)return toast('請先 Google 登入');let user=cloudUser;try{let batch=firebaseApi.writeBatch(firestore);batch.set(firebaseApi.doc(cloudCollection('settings'),'ttlCredential'),{version:1,envelope:null,updatedAt:firebaseApi.serverTimestamp()});await batch.commit();if(cloudUser?.uid===user.uid){ttlBinding=null;document.getElementById('ttlBindingStatus').textContent='已解除綁定，更新前需重新填寫帳密。';}}catch{toast('解除綁定失敗，請重試');}}
let lastTtlUser;setInterval(()=>{if(cloudUser?.uid!==lastTtlUser){lastTtlUser=cloudUser?.uid;loadTtlBinding();}},1000);

// Mobile selection stays focused; visit analysis has its own tab.
const selectionSummary=document.createElement('div');selectionSummary.className='selection-summary';selectionSummary.innerHTML='<div class="selection-total">總客戶數 <strong id="selectionTotal">0</strong></div><button onclick="openStore()">＋ 新增店家</button><div id="scheduleChannels" class="channel-buttons"></div>';
document.querySelector('#panel-list > .intro').after(selectionSummary);
const v5RenderReport=renderReport;renderReport=function(){v5RenderReport();let rows=scopeRecords(),box=document.getElementById('scheduleChannels');document.getElementById('selectionTotal').textContent=rows.length;box.replaceChildren();function chip(name,items,key){let b=makeAction(name,()=>{channelFocus=key;document.getElementById('search').value='';groups.clear();render();});b.innerHTML='<b>'+esc(name)+'</b><span>應訪 '+items.filter(x=>x.req>0).length+' 家 · 缺訪 '+items.filter(x=>visitGap(x)>0).length+' 家</span>';b.classList.toggle('active',channelFocus===key);b.setAttribute('aria-pressed',String(channelFocus===key));box.append(b);}chip('全通路',rows,'');for(let c of reportStats(rows))chip(c.name,rows.filter(x=>(x.channel||x.group)===c.name),c.name);};
const recovery=document.getElementById('syncRecovery');const recoveryCard=document.createElement('article');recoveryCard.className='card sync-recovery-card';recoveryCard.innerHTML='<h3>同步問題處理</h3><p class="notice">只有同步失敗或不同裝置的版本衝突時才需處理，本機草稿會保留。重試同步會重新上傳草稿；使用雲端版本會先確認，再載入另一裝置的版本。</p>';recoveryCard.append(recovery);document.getElementById('panel-data').append(recoveryCard);
const v5CloudUi=updateCloudUi;updateCloudUi=function(message){v5CloudUi(message);recoveryCard.classList.toggle('hide',recovery.classList.contains('hide'));};
const cleanMobile=document.createElement('style');cleanMobile.textContent='.selection-summary{display:none}.sync-recovery-card{margin-top:16px}@media(max-width:600px){.bottomnav{grid-template-columns:repeat(4,1fr)}body[data-mobile-view="list"] .visit-overview{display:none}body[data-mobile-view="list"] #panel-list>.intro .notice{display:none}body[data-mobile-view="list"] .selection-summary{display:grid;grid-template-columns:1fr auto;align-items:center;gap:12px;margin-bottom:12px}.selection-total{font-size:13px}.selection-total strong{font-size:26px;margin-left:8px}.selection-summary #scheduleChannels{grid-column:1/-1;display:flex;overflow-x:auto;flex-wrap:nowrap;margin:0;padding-bottom:5px}.selection-summary #scheduleChannels button{flex:none;min-width:150px}.selection-summary button{min-height:44px}.filterbar .searchfield{grid-column:1/-1}.selection-summary .channel-buttons span{white-space:nowrap}body[data-mobile-view="report"] #panel-list>.intro>button,body[data-mobile-view="report"] #panel-list>.intro .notice,body[data-mobile-view="report"] #panel-list>.card,body[data-mobile-view="report"] #panel-list>.planner-options,body[data-mobile-view="report"] #panel-list>.listtools,body[data-mobile-view="report"] #panel-list>.store-table-head,body[data-mobile-view="report"] #storeList{display:none}body[data-mobile-view="map"] .syncbar{display:none}body[data-mobile-view="map"] header .sub{display:none}body[data-mobile-view="map"] #panel-map>.intro{display:none}body[data-mobile-view="map"] .route-controls .depot-tag{display:none}body[data-mobile-view="map"] .route-controls{display:grid;grid-template-columns:1fr 1fr}body[data-mobile-view="map"] .route-controls .suggestBtn{font-size:12px;padding:8px}body[data-mobile-view="map"] .maptools{gap:6px}body[data-mobile-view="map"] .maptools button{flex:1;font-size:12px}body[data-mobile-view="map"] .maptools select{display:none}body[data-mobile-view="map"] #map{height:58dvh;min-height:340px}body[data-mobile-view="map"] #routeHint:empty{display:none}body[data-mobile-view="map"] .legend{margin-top:8px;font-size:11px}body[data-mobile-view="map"] .maplayout>div>p{display:none}}';document.head.append(cleanMobile);
const v5FitMap=fitMap;fitMap=function(){if(!map)return;let points=[DEPOT.gps,...selectedRecords().filter(x=>validGps(x.gps)).map(x=>x.gps)];if(document.getElementById('mapScope').value!=='selected')return v5FitMap();map.fitBounds(L.latLngBounds(points),{padding:[24,24],maxZoom:15});};
focusStore=function(code){let x=scopeRecords().find(x=>x.code===code);if(!x||!validGps(x.gps))return;switchView('map');document.getElementById('mapScope').value=chosen.has(code)?'selected':'filtered';updateMap(false);requestAnimationFrame(()=>{map.setView(x.gps,16);markers.get(code)?.openPopup();});};
let lastFittedStops='';const v5Render=render;render=function(){v5Render();if(activeView==='map'){let signature=selectedRecords().filter(x=>validGps(x.gps)).map(x=>x.code+':'+x.gps.join(',')).join('|');if(signature!==lastFittedStops){lastFittedStops=signature;requestAnimationFrame(()=>fitMap());}}};
let lastMobile=matchMedia('(max-width:600px)').matches;window.addEventListener('resize',()=>{let current=matchMedia('(max-width:600px)').matches;if(current!==lastMobile){lastMobile=current;switchView(activeView);}});
render();updateCloudUi();switchView(activeView);
