// Compact settings and mandatory account onboarding.
const compactData=document.getElementById('panel-data');
document.querySelector('.headeractions')?.remove();
document.querySelectorAll('button[onclick="openStore()"],.cloud-help,#panel-data .footer-note').forEach(e=>e.remove());
compactData.querySelectorAll('.intro .notice,.card>p:not([id]),.customer-sync-card details').forEach(e=>{if(e.querySelector('#customerFile')){e.classList.add('hide');}else e.remove();});
compactData.querySelector('.intro h2').textContent='資料與設定';
const settingsTabs=document.createElement('div');settingsTabs.className='settings-tabs';settingsTabs.innerHTML='<button class="active" onclick="selectSettingsTab(false)">資料與設定</button><button id="adminSettingsTab" class="hide" onclick="selectSettingsTab(true)">登入紀錄</button>';compactData.querySelector('.intro').after(settingsTabs);
const settingsContent=document.createElement('div');settingsContent.id='compactSettings';settingsTabs.after(settingsContent);
const responsibility=compactData.querySelector('.responsibility-bar');settingsContent.append(responsibility);responsibility.querySelector('label').firstChild.textContent='負責人員';responsibility.querySelector('div').classList.add('hide');
const accountButton=document.createElement('button');accountButton.id='companyAccountButton';accountButton.textContent='業務王帳號';accountButton.onclick=()=>showCredentialDrawer();responsibility.append(accountButton);
const grid=compactData.querySelector('.data-grid');settingsContent.append(grid);
for(const [selector,label,dataset] of [['.visit-sync-card','更新訪況','visits'],['.customer-sync-card','更新客戶與座標','all']]){const card=grid.querySelector(selector);card.querySelector('h3').remove();const buttons=card.querySelectorAll('.visitSyncBtn');buttons[0].textContent=label;buttons[0].onclick=()=>updateCompanyVisits(dataset);for(const b of [...buttons].slice(1))b.remove();card.querySelectorAll('p').forEach(e=>e.classList.add('hide'));}
const syncStatus=document.getElementById('visitSyncStatus');syncStatus.classList.remove('hide');settingsContent.append(syncStatus);syncStatus.textContent='';
const ruleCard=[...grid.querySelectorAll('.card')].find(e=>e.querySelector('button[onclick="openRules()"]'));ruleCard.classList.add('wide-settings');ruleCard.querySelector('h3').textContent='店點與拜訪設定';ruleCard.querySelector('button').textContent='訪頻規則';
adminCard.querySelector('.notice')?.remove();adminCard.querySelector('h3').textContent='使用帳戶';
const drawer=document.createElement('div');drawer.id='credentialDrawer';drawer.className='modal credential-drawer';drawer.innerHTML='<div class="dialog"><button class="drawer-close" onclick="closeModal(\'credentialDrawer\')" aria-label="關閉帳號設定">✕</button></div>';drawer.querySelector('.dialog').append(ttlCard);document.body.append(drawer);ttlCard.querySelector('p:not([id])')?.remove();ttlCard.style.marginBottom='0';ttlCard.classList.remove('card');
const credentialForm=document.getElementById('ttlBindingForm');credentialForm.querySelector('[type="submit"]').textContent='儲存並測試';credentialForm.querySelector('[type="button"]').textContent='重新設定';
const testBinding=document.createElement('button');testBinding.id='testExistingBinding';testBinding.className='primary';testBinding.textContent='測試已綁定帳號';testBinding.onclick=verifyCompanyBinding;ttlCard.append(testBinding);
const gate=document.createElement('section');gate.id='accountGate';gate.innerHTML='<img src="route-map-logo.svg" alt="巡店地圖"><h1>巡店地圖</h1><p id="gateMessage">正在確認登入…</p><button id="gateAction" class="primary">Google 登入</button><p id="gateStatus" role="status"></p>';document.body.append(gate);
let bindingTesting=false,gateLastUid=null,settingsAdminSelected=false;
function plannerAccessReady(){return !!cloudUser&&ttlBindingUid===cloudUser.uid&&!!ttlBinding?.envelope&&ttlBinding.verified===true;}
function selectSettingsTab(admin){settingsAdminSelected=admin;if(admin&&!isPlannerAdmin())return;settingsContent.classList.toggle('hide',admin);adminCard.classList.toggle('hide',!admin);settingsTabs.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===(admin?1:0)));}
function refreshAccountGate(){if(!cloudUser)closeModal('credentialDrawer');const ready=plannerAccessReady();document.body.classList.toggle('account-blocked',!ready);gate.classList.toggle('hide',ready);const message=document.getElementById('gateMessage'),action=document.getElementById('gateAction');message.textContent=!cloudUser?'先登入 Google 帳號':ttlBindingUid!==cloudUser.uid?'正在載入帳號設定…':'設定業務王帳號，完成連線測試';action.textContent=!cloudUser?'Google 登入':'設定業務王帳號';action.disabled=bindingTesting;action.onclick=()=>cloudUser?showCredentialDrawer():loginCloud();document.getElementById('adminSettingsTab').classList.toggle('hide',!isPlannerAdmin());adminCard.classList.toggle('hide',!isPlannerAdmin()||!settingsAdminSelected);if(gateLastUid!==cloudUser?.uid){gateLastUid=cloudUser?.uid;selectSettingsTab(false);}document.getElementById('companyAccountButton').textContent='業務王帳號';const bound=ttlBindingUid===cloudUser?.uid&&ttlBinding;testBinding.classList.toggle('hide',!bound||ready);credentialForm.classList.toggle('bound-account',ready);document.getElementById('ttlBindingStatus').textContent=bindingTesting?'正在測試連線…':ready?'已連線 · '+(ttlBinding.accountLabel||'已綁定帳號'):bound?'已儲存，請測試連線':'輸入你的業務王帳號與密碼';}
function showCredentialDrawer(){if(!cloudUser)return loginCloud();refreshAccountGate();openModal('credentialDrawer');}
async function verifyCompanyBinding(){if(bindingTesting||!cloudUser||!ttlBinding?.envelope)return;bindingTesting=true;const user=cloudUser,envelope=ttlBinding.envelope;refreshAccountGate();try{const result=await updateCompanyVisits('all');if(!result?.success)throw Error(result?.error||document.getElementById('visitSyncStatus').textContent||'連線測試未完成');if(cloudUser?.uid!==user.uid||ttlBinding?.envelope!==envelope)throw Error('帳號已變更，請重新測試');if(!result.accountLabel||typeof result.accountLabel!=='string'||result.accountLabel.length>180)throw Error('請重新整理後再測試');syncStatus.textContent='更新完成';const data={...ttlBinding,verified:true,accountLabel:result.accountLabel,verifiedAt:firebaseApi.serverTimestamp()};const batch=firebaseApi.writeBatch(firestore);batch.set(firebaseApi.doc(cloudCollection('settings'),'ttlCredential'),data);await batch.commit();if(cloudUser?.uid!==user.uid)return;ttlBinding=data;document.getElementById('gateStatus').textContent='';closeModal('credentialDrawer');render();switchView('map');toast('業務王連線成功');}catch(e){if(cloudUser?.uid!==user.uid)return;document.getElementById('gateStatus').textContent=e.message;document.getElementById('ttlBindingStatus').textContent=e.message;toast(e.message);}finally{bindingTesting=false;refreshAccountGate();}}
const saveCredential=credentialForm.onsubmit;credentialForm.onsubmit=async e=>{await saveCredential(e);if(ttlBinding?.envelope&&!ttlBinding.verified)await verifyCompanyBinding();refreshAccountGate();};
const compactLoadBinding=loadTtlBinding;loadTtlBinding=async function(){await compactLoadBinding();refreshAccountGate();};
const compactUnlink=unlinkTtlAccount;unlinkTtlAccount=async function(){await compactUnlink();refreshAccountGate();};
const tableHead=document.querySelector('.store-table-head');if(tableHead){tableHead.children[1].textContent='店家';const controls=document.createElement('div');controls.className='table-controls';controls.append(document.getElementById('visitStatus'),document.getElementById('storeSort'));tableHead.children[3].replaceChildren(controls);document.getElementById('visitStatus').setAttribute('aria-label','訪況篩選');document.getElementById('storeSort').setAttribute('aria-label','店家排序');document.querySelector('.planner-options')?.classList.add('hide');}
const searchField=document.querySelector('.searchfield');const searchRow=document.createElement('div');searchRow.className='compact-search';const channels=document.createElement('div');channels.append(document.getElementById('scheduleChannels'));searchRow.append(channels,searchField);selectionSummary.append(searchRow);document.querySelectorAll('.channel-title').forEach(e=>e.remove());
const compactCard=storeCard;storeCard=function(x){const row=compactCard(x);if(frequencyFor(x)?.period==='none'){const n=row.querySelector('.visitnumbers');n.textContent='無規定';n.style.display='block';}return row;};
const originalRequired=required;required=x=>frequencyFor(x)?.period==='none'?0:originalRequired(x);
rulesInfo.textContent='全站共用規則';
const compactStyle=document.createElement('style');compactStyle.textContent=`
.account-blocked>header,.account-blocked>.shell,.account-blocked>.bottomnav{display:none!important}#accountGate{position:fixed;inset:0;z-index:1500;background:#edf2f5;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px;text-align:center}#accountGate.hide{display:none}#accountGate img{width:76px;height:76px}#accountGate button{min-width:230px}#gateStatus{max-width:450px;color:#be4d38}.credential-drawer{z-index:1600;justify-content:flex-end;padding:0}.credential-drawer .dialog{height:100%;max-height:100%;width:min(440px,100%);border-radius:18px 0 0 18px;padding:28px;position:relative}.drawer-close{position:absolute;right:16px;top:16px}.credential-drawer .formgrid{grid-template-columns:1fr}.credential-drawer h3{margin:20px 0}.credential-drawer form>button{margin:12px 8px 0 0}.bound-account .formgrid,.bound-account [type=submit]{display:none}.settings-tabs{display:flex;gap:8px;margin-bottom:16px}.settings-tabs .active{background:var(--ink);color:white}#compactSettings>.data-grid{gap:12px}#compactSettings .visit-sync-card,#compactSettings .customer-sync-card{padding:0;border:0;background:none}#compactSettings .data-actions{margin:0}#compactSettings .visitSyncBtn{width:100%;min-height:60px;font-size:16px}.wide-settings{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:20px}.wide-settings h3{margin:0}.wide-settings button{min-width:180px}.responsibility-bar{flex-wrap:wrap;justify-content:space-between}.responsibility-bar label{flex:1}.syncbar .notice,#customerStatus,#customerMasterStatus,#responsibilitySummary,#panel-data>.notice{display:none!important}.store-table-head,.store,.store.selected{grid-template-columns:36px minmax(130px,240px) minmax(95px,1fr) minmax(210px,1fr) 55px;gap:8px}.table-controls{display:flex;gap:6px}.table-controls select{min-width:0;width:50%;font-size:12px;min-height:36px;padding:4px}.selection-summary{display:block}body[data-mobile-view="report"] .selection-summary{display:none!important}.compact-search{display:grid;grid-template-columns:1fr 1fr;align-items:start;gap:12px;width:100%}.compact-search>*{min-width:0}.compact-search #scheduleChannels{max-width:100%}.compact-search .channel-buttons{margin:0}.compact-search .searchfield{min-width:0}.selection-summary>#scheduleChannels{display:none}.storeidentity .meta{overflow-wrap:anywhere;font-size:11px}.storeidentity h3{font-size:15px}.brand .sub{display:none}#panel-data .intro{margin-bottom:10px}
@media(max-width:600px){body[data-mobile-view="list"] .selection-summary{display:block!important}body[data-mobile-view="list"] #panel-list>.card{display:none!important}.store-table-head>span:nth-child(2){grid-column:2}.store-table-head>span:nth-child(4){grid-column:4}.credential-drawer{align-items:flex-end}.credential-drawer .dialog{height:auto;max-height:90dvh;width:100%;border-radius:20px 20px 0 0;padding:24px}.store-table-head{display:grid;grid-template-columns:0 1fr 0 1.2fr 0;padding:8px}.store-table-head>span:nth-child(3),.store-table-head>span:nth-child(5){display:none}.store,.store.selected{grid-template-columns:30px minmax(100px,1fr) minmax(120px,1fr);gap:6px;padding:10px 8px}.storechannel{grid-column:2;grid-row:2}.visitnumbers{grid-column:3;grid-row:1;font-size:15px}.storelocation{grid-column:3;grid-row:2}.compact-search{gap:8px}.compact-search .channel-buttons{grid-template-columns:1fr}.compact-search .channel-buttons button{padding:8px;min-height:40px}.wide-settings{padding:16px}.wide-settings h3{font-size:15px}.wide-settings button{min-width:120px}.responsibility-bar label{min-width:0}.responsibility-bar{display:flex;gap:8px}.responsibility-bar button{font-size:13px;padding:8px}#compactSettings .data-grid{grid-template-columns:1fr 1fr}.table-controls{flex-direction:column}.table-controls select{width:100%;min-height:30px}.selection-summary{display:block}.selection-total{margin-bottom:10px}.syncbar{padding:10px!important}}
`;document.head.append(compactStyle);
refreshAccountGate();setInterval(refreshAccountGate,700);
