// Explicit update outcomes and an administrator catalogue of active visitors' reports.
const updateIssue=document.createElement('div');updateIssue.id='updateIssue';updateIssue.className='modal credential-drawer';updateIssue.innerHTML='<div class="dialog"><h2>更新未完成</h2><p id="updateIssueReason" role="alert"></p><footer><button onclick="closeModal(\'updateIssue\')">關閉</button><button id="updateIssueRetry" class="primary">重試</button></footer></div>';document.body.append(updateIssue);
let lastUpdateDataset='visits';
function updateReason(error){const message=String(error?.message||error||'更新未完成，請重試').slice(0,500);if(/Failed to fetch|NetworkError|network-request-failed/i.test(message))return '無法連線更新服務，請確認網路後重試';if(/permission-denied/i.test(message))return 'Supabase 拒絕儲存，請聯絡管理者檢查權限';if(/resource[-_]exhausted|quota/i.test(message)&&!message.startsWith('Supabase '))return 'Supabase 用量已達限制，請稍後再試';return message;}
function showUpdateIssue(reason){const text=updateReason(reason);setSyncStatus('更新未完成：'+text);document.getElementById('updateIssueReason').textContent=text;openModal('updateIssue');}
const checkedCompanyUpdate=updateCompanyVisits;
updateCompanyVisits=async function(dataset='visits'){lastUpdateDataset=dataset;const updateUid27=cloudUser?.uid;let result;try{result=await checkedCompanyUpdate(dataset);if(cloudUser?.uid!==updateUid27)return {success:false,error:'登入帳號已變更'};if(!result?.success)showUpdateIssue(result?.error||document.getElementById('visitSyncStatus').textContent||'更新未啟動，請稍後重試');return result||{success:false,error:'更新未啟動'};}catch(error){if(cloudUser?.uid!==updateUid27)return {success:false,error:'登入帳號已變更'};visitSyncBusy=false;visitSyncAbort=null;document.querySelectorAll('.visitSyncBtn').forEach(b=>b.disabled=false);companyWaitDepth=0;endCompanyWait();showUpdateIssue(error);return {success:false,error:updateReason(error)};}};
document.getElementById('updateIssueRetry').onclick=()=>{closeModal('updateIssue');updateCompanyVisits(lastUpdateDataset);};
// Reuse the owner's verified Google token, refreshing once if the backend reports expiry.
const checkedGithubApi=visitGithubApi;visitGithubApi=async function(path,options={}){try{return await checkedGithubApi(path,options);}catch(error){if(error.status!==401||!cloudUser)throw error;await cloudUser.getIdToken(true);return checkedGithubApi(path,options);}};

// Share identical Firestore subscriptions across the manager, roster, and rules views.
const originalCloudMessage=cloudMessage;cloudMessage=function(error){if(error?.code==='deadline-exceeded')return '雲端讀取逾時，請稍後重試';if(/resource[-_]exhausted|quota/i.test(String(error?.code)+' '+String(error?.message)))return 'Supabase 免費讀取額度已用完，請待額度恢復後重試';if(/unauthenticated|auth\/user-token-expired/i.test(String(error?.code)))return 'Google 登入已過期，請重新登入';return originalCloudMessage(error);};
let lastFullCloudLoad=0,resumeCloudPending=false;
const measuredCloudLoad=loadFromCloud;loadFromCloud=async function(initial=false){try{return await measuredCloudLoad(initial);}finally{lastFullCloudLoad=Date.now();}};
async function resumePlannerCloud(){if(resumeCloudPending||cloudBusy||localDirty||!cloudUser)return;if(Date.now()-lastFullCloudLoad>300000)return loadFromCloud(true);const uid=cloudUser.uid,date=routeDate,generation=editGeneration;resumeCloudPending=true;try{const snap=await firebaseApi.getDoc(routeRef());if(cloudUser?.uid!==uid||routeDate!==date||localDirty||cloudBusy||generation!==editGeneration)return;const data=snap.exists()?snap.data():null;restoreRouteDetails28(data);chosen=new Set(data?.codes||[]);cloudRevision=data?.revision||0;routeHint='';autoRouteDone='';fitNext=true;cacheState();render();}catch(error){updateCloudUi(cloudMessage(error));}finally{resumeCloudPending=false;}}
let historyRows17=[],historyLoaded17=0,historyUid17=null,historyBusy17=false;
loadAdminHistory=async function(force=false){if(!isPlannerAdmin())return;if(historyUid17!==cloudUser.uid){historyUid17=cloudUser.uid;historyRows17=[];historyLoaded17=0;}if(historyBusy17)return;if(!force&&Date.now()-historyLoaded17<180000){document.getElementById('adminHistory').innerHTML=accessTable(historyRows17,true);return;}historyBusy17=true;const uid=cloudUser.uid;try{const q=firebaseApi.query(firebaseApi.collection(firestore,'route_map_test_access'),firebaseApi.orderBy('at','desc'),firebaseApi.limit(100)),snap=await firebaseApi.getDocs(q);if(cloudUser?.uid!==uid||!isPlannerAdmin())return;historyRows17=snap.docs.map(x=>x.data());historyLoaded17=Date.now();document.getElementById('adminHistory').innerHTML=accessTable(historyRows17,true);}catch(error){document.getElementById('adminHistory').textContent=cloudMessage(error);}finally{historyBusy17=false;}};
adminCard.querySelector('button').onclick=()=>loadAdminHistory(true);
const measuredPlannerSession=recordPlannerSession;let lastHeartbeat17=0;
recordPlannerSession=async function(kind='open'){if(kind==='heartbeat'){if(Date.now()-lastHeartbeat17<120000)return;lastHeartbeat17=Date.now();}return measuredPlannerSession(kind);};
// Streaming SDK retries can otherwise leave the sign-in screen waiting silently.
let gateFailureUid17=null,gateFailure17='',gateProbeTimer17=null;
const errorAwareGate=refreshAccountGate;refreshAccountGate=function(){errorAwareGate();if(cloudUser?.uid===gateFailureUid17&&!plannerAccessReady()&&gateFailure17){document.getElementById('gateStatus').textContent=gateFailure17;document.getElementById('gateRetry17').classList.remove('hide');}else document.getElementById('gateRetry17')?.classList.add('hide');};
const gateRetry17=document.createElement('button');gateRetry17.id='gateRetry17';gateRetry17.className='hide';gateRetry17.textContent='重試';gateRetry17.onclick=()=>location.reload();document.getElementById('accountGate').append(gateRetry17);
function probeGate17(){const uid=cloudUser?.uid||null;if(uid===gateFailureUid17)return;gateFailureUid17=uid;gateFailure17='';clearTimeout(gateProbeTimer17);if(!uid)return;gateProbeTimer17=setTimeout(async()=>{if(cloudUser?.uid!==uid||plannerAccessReady())return;try{await visitGithubApi('/actions/workflows/'+VISIT_WORKFLOW);}catch(error){if(cloudUser?.uid===uid){gateFailure17=updateReason(error);refreshAccountGate();}}},8000);}
setInterval(probeGate17,1000);probeGate17();
let catalogueUser=null,catalogueRosterStop=null,catalogueStates=new Map(),catalogueStops=new Map(),catalogueGeneration=0,catalogueTimer=null,catalogueAlertKey='';
function catalogueActive(uid){return uid===cloudUser?.uid||catalogueStates.get(uid)?.controlReady===true&&catalogueStates.get(uid)?.control?.active!==false;}
function catalogueRows(){return [...catalogueStates.values()].filter(s=>catalogueActive(s.uid)).flatMap(s=>s.visits.filter(x=>!isClosedStore(x)&&!s.closed.has(String(x.code))));}
const personalReportPairs=reportRulePairs;reportRulePairs=function(){const pairs=new Map();for(const x of [...personalReportPairs(),...(isPlannerAdmin()?catalogueRows():[])]){const channel=String(x.channel||'').trim(),grade=String(x.grade||'').trim();if(channel&&grade)pairs.set(channel+'|'+ruleGrade(grade),{channel,grade});}return [...pairs.values()].sort((a,b)=>a.channel.localeCompare(b.channel,'zh-Hant')||a.grade.localeCompare(b.grade,'zh-Hant'));};
function unconfiguredPairs(){return reportRulePairs().filter(p=>!(ruleConfig.entries||[]).some(r=>(r.channel===p.channel||r.channel==='*')&&ruleGrade(r.grade)===ruleGrade(p.grade)));}
const frequencyNotice=document.createElement('button');frequencyNotice.id='frequencyNotice';frequencyNotice.className='hide';frequencyNotice.onclick=()=>openModal('frequencyNoticeDialog');ruleCard.prepend(frequencyNotice);
const frequencyNoticeDialog=document.createElement('div');frequencyNoticeDialog.id='frequencyNoticeDialog';frequencyNoticeDialog.className='modal credential-drawer';frequencyNoticeDialog.innerHTML='<div class="dialog"><h2>請設定訪頻規則</h2><div id="frequencyNoticePairs"></div><footer><button onclick="closeModal(\'frequencyNoticeDialog\')">稍後</button><button id="frequencyNoticeSetup" class="primary">前往設定</button></footer></div>';document.body.append(frequencyNoticeDialog);
document.getElementById('frequencyNoticeSetup').onclick=()=>{closeModal('frequencyNoticeDialog');openRules();};
function refreshFrequencyNotice(){if(!isPlannerAdmin()||!plannerAccessReady()){frequencyNotice.classList.add('hide');return;}const pairs=unconfiguredPairs();frequencyNotice.classList.toggle('hide',!pairs.length);frequencyNotice.textContent=pairs.length+' 組通路／等級待設訪頻';document.getElementById('frequencyNoticePairs').replaceChildren(...pairs.map(p=>{const row=document.createElement('p');row.textContent=p.channel+' · '+p.grade;return row;}));const key=JSON.stringify(pairs.map(p=>[p.channel,ruleGrade(p.grade)]));if(pairs.length&&sharedRules&&key!==catalogueAlertKey){catalogueAlertKey=key;const storage='planner-frequency-alert:'+cloudUser.uid;if(sessionStorage.getItem(storage)!==key){sessionStorage.setItem(storage,key);openModal('frequencyNoticeDialog');}}if(!pairs.length){catalogueAlertKey='';closeModal('frequencyNoticeDialog');}}
const visibleAccessTable=accessTable;accessTable=function(rows,history=false){return visibleAccessTable(rows.filter(x=>catalogueActive(x.uid)),history);};
const visibleManagerEntries=managerEntries;managerEntries=function(){return visibleManagerEntries().filter(e=>catalogueActive(e.person.uid)&&e.state?.control?.active!==false);};
const visibleManagerRender=renderManagerOverview;renderManagerOverview=function(){visibleManagerRender();const select=document.getElementById('managerPerson');for(const option of [...select.options])if(option.value&&!catalogueActive(option.value))option.remove();if(managerUid&&!catalogueActive(managerUid)){managerUid='';select.value='';visibleManagerRender();for(const option of [...select.options])if(option.value&&!catalogueActive(option.value))option.remove();}};
function refreshCatalogueViews(){refreshInlineRules();refreshFrequencyNotice();if(managerAllowed())renderManagerOverview();if(isPlannerAdmin()){const rows=[...catalogueStates.values()].filter(s=>catalogueActive(s.uid)).map(s=>s.person).sort((a,b)=>(b.lastSeen?.toMillis?.()||0)-(a.lastSeen?.toMillis?.()||0));document.getElementById('adminAccountSummary').textContent=rows.length+' 個使用帳戶';document.getElementById('adminAccounts').innerHTML=accessTable(rows);loadAdminHistory();}}
function queueCatalogueRefresh(){clearTimeout(catalogueTimer);catalogueTimer=setTimeout(refreshCatalogueViews,150);}
function stopCatalogue(){catalogueGeneration++;catalogueRosterStop?.();catalogueRosterStop=null;for(const stops of catalogueStops.values())stops.forEach(stop=>stop());catalogueStops.clear();catalogueStates.clear();clearTimeout(catalogueTimer);catalogueUser=null;frequencyNotice.classList.add('hide');}
function connectCatalogue(){const uid=isPlannerAdmin()&&plannerAccessReady()?cloudUser.uid:null;if(uid===catalogueUser)return;stopCatalogue();if(!uid||!firebaseApi)return;catalogueUser=uid;const generation=catalogueGeneration;catalogueRosterStop=firebaseApi.onSnapshot(firebaseApi.collection(firestore,'route_map_test_presence'),snap=>{if(generation!==catalogueGeneration)return;const people=snap.docs.map(d=>d.data()).filter(p=>typeof p.uid==='string');const ids=new Set(people.map(p=>p.uid));for(const [id,stops] of catalogueStops)if(!ids.has(id)){stops.forEach(stop=>stop());catalogueStops.delete(id);catalogueStates.delete(id);}for(const person of people){let state=catalogueStates.get(person.uid);if(state){state.person=person;continue;}state={uid:person.uid,person,controlReady:false,control:null,visits:[],closed:new Set()};catalogueStates.set(person.uid,state);const valid=()=>generation===catalogueGeneration;const base=firebaseApi.collection(firestore,'route_map_test_users',person.uid,'settings');const stops=[firebaseApi.onSnapshot(firebaseApi.doc(base,'accessControl'),s=>{if(!valid())return;state.controlReady=true;state.control=s.exists()?s.data():null;queueCatalogueRefresh();},()=>{if(valid()){state.controlReady=false;queueCatalogueRefresh();}}),firebaseApi.onSnapshot(firebaseApi.doc(base,'closedStores'),s=>{if(!valid())return;state.closed=new Set(s.exists()?s.data().codes||[]:[]);queueCatalogueRefresh();}),firebaseApi.onSnapshot(firebaseApi.collection(firestore,'route_map_test_users',person.uid,'visits'),s=>{if(!valid())return;state.visits=s.docs.map(d=>d.data());queueCatalogueRefresh();},()=>{if(valid()){frequencyNotice.textContent='全站訪頻資料讀取失敗，請重新整理';frequencyNotice.classList.remove('hide');}})];catalogueStops.set(person.uid,stops);}queueCatalogueRefresh();},()=>{frequencyNotice.textContent='訪員資料讀取失敗，請重新整理';frequencyNotice.classList.remove('hide');});}
const catalogueRender=render;render=function(){catalogueRender();connectCatalogue();refreshFrequencyNotice();};setInterval(connectCatalogue,1000);connectCatalogue();
releaseButton.textContent='v1.17';releaseButton.setAttribute('aria-label','版本 v1.17，查看更新紀錄');const release17=document.createElement('article');release17.className='release-entry';release17.innerHTML='<b>v1.17</b><time>2026-10-05</time><p>更新失敗明確回報並可重試，公司下載中斷自動重試並加密回報原因；減少切回網頁重複下載、合併管理監聽；管理者帶入全訪員通路與等級、待設訪頻通知；已移除帳戶從管理資料隱藏，重新加入才顯示。</p>';releaseHistory.querySelector('h2').after(release17);
const style17=document.createElement('style');style17.textContent='#updateIssueReason{white-space:pre-wrap;line-height:1.7;overflow-wrap:anywhere}#frequencyNotice{width:100%;margin-bottom:12px;text-align:left;background:#fff4e5;color:#8c4e10;border-color:#e9c79c}#frequencyNoticePairs{max-height:55vh;overflow:auto}';document.head.append(style17);
